// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package openapi

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb "github.com/NerdIT-Tech/tplink-omada-sdk-for-go/models"
)

// V1ItemSitesItemPortalPageRequestBuilder builds and executes requests for operations under \openapi\v1\{omadacId}\sites\{siteId}\portal\page
type V1ItemSitesItemPortalPageRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// V1ItemSitesItemPortalPageRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type V1ItemSitesItemPortalPageRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewV1ItemSitesItemPortalPageRequestBuilderInternal instantiates a new V1ItemSitesItemPortalPageRequestBuilder and sets the default values.
func NewV1ItemSitesItemPortalPageRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitesItemPortalPageRequestBuilder) {
    m := &V1ItemSitesItemPortalPageRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/openapi/v1/{omadacId}/sites/{siteId}/portal/page", pathParameters),
    }
    return m
}
// NewV1ItemSitesItemPortalPageRequestBuilder instantiates a new V1ItemSitesItemPortalPageRequestBuilder and sets the default values.
func NewV1ItemSitesItemPortalPageRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitesItemPortalPageRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1ItemSitesItemPortalPageRequestBuilderInternal(urlParams, requestAdapter)
}
// Post import portal page
// returns a OperationResponseImportedPortalPageResOpenApiVOable when successful
func (m *V1ItemSitesItemPortalPageRequestBuilder) Post(ctx context.Context, body []byte, requestConfiguration *V1ItemSitesItemPortalPageRequestBuilderPostRequestConfiguration)(i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.OperationResponseImportedPortalPageResOpenApiVOable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.CreateOperationResponseImportedPortalPageResOpenApiVOFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.OperationResponseImportedPortalPageResOpenApiVOable), nil
}
// ToPostRequestInformation import portal page
// returns a *RequestInformation when successful
func (m *V1ItemSitesItemPortalPageRequestBuilder) ToPostRequestInformation(ctx context.Context, body []byte, requestConfiguration *V1ItemSitesItemPortalPageRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "*/*")
    requestInfo.SetStreamContentAndContentType(body, "multipart/form-data")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *V1ItemSitesItemPortalPageRequestBuilder when successful
func (m *V1ItemSitesItemPortalPageRequestBuilder) WithUrl(rawUrl string)(*V1ItemSitesItemPortalPageRequestBuilder) {
    return NewV1ItemSitesItemPortalPageRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
