// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package openapi

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V1ItemSitesItemNetworksItemVlansWithVlanItemRequestBuilder builds and executes requests for operations under \openapi\v1\{omadacId}\sites\{siteId}\networks\{networkId}\vlans\{vlan}
type V1ItemSitesItemNetworksItemVlansWithVlanItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewV1ItemSitesItemNetworksItemVlansWithVlanItemRequestBuilderInternal instantiates a new V1ItemSitesItemNetworksItemVlansWithVlanItemRequestBuilder and sets the default values.
func NewV1ItemSitesItemNetworksItemVlansWithVlanItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitesItemNetworksItemVlansWithVlanItemRequestBuilder) {
    m := &V1ItemSitesItemNetworksItemVlansWithVlanItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/openapi/v1/{omadacId}/sites/{siteId}/networks/{networkId}/vlans/{vlan}", pathParameters),
    }
    return m
}
// NewV1ItemSitesItemNetworksItemVlansWithVlanItemRequestBuilder instantiates a new V1ItemSitesItemNetworksItemVlansWithVlanItemRequestBuilder and sets the default values.
func NewV1ItemSitesItemNetworksItemVlansWithVlanItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitesItemNetworksItemVlansWithVlanItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1ItemSitesItemNetworksItemVlansWithVlanItemRequestBuilderInternal(urlParams, requestAdapter)
}
// Switches the switches property
// returns a *V1ItemSitesItemNetworksItemVlansItemSwitchesRequestBuilder when successful
func (m *V1ItemSitesItemNetworksItemVlansWithVlanItemRequestBuilder) Switches()(*V1ItemSitesItemNetworksItemVlansItemSwitchesRequestBuilder) {
    return NewV1ItemSitesItemNetworksItemVlansItemSwitchesRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
