// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package openapi

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb "github.com/NerdIT-Tech/tplink-omada-sdk-for-go/models"
)

// V1ItemSitetemplatesItemMacFiltersDenyRequestBuilder builds and executes requests for operations under \openapi\v1\{omadacId}\sitetemplates\{siteTemplateId}\mac-filters\deny
type V1ItemSitetemplatesItemMacFiltersDenyRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// V1ItemSitetemplatesItemMacFiltersDenyRequestBuilderGetQueryParameters get deny MAC filtering template list.
type V1ItemSitetemplatesItemMacFiltersDenyRequestBuilderGetQueryParameters struct {
    // Start page number. Start from 1.
    Page *int32 "uriparametername:\"page\""
    // Number of entries per page. It should be within the range of 1–1000.
    PageSize *int32 "uriparametername:\"pageSize\""
}
// V1ItemSitetemplatesItemMacFiltersDenyRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type V1ItemSitetemplatesItemMacFiltersDenyRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *V1ItemSitetemplatesItemMacFiltersDenyRequestBuilderGetQueryParameters
}
// NewV1ItemSitetemplatesItemMacFiltersDenyRequestBuilderInternal instantiates a new V1ItemSitetemplatesItemMacFiltersDenyRequestBuilder and sets the default values.
func NewV1ItemSitetemplatesItemMacFiltersDenyRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitetemplatesItemMacFiltersDenyRequestBuilder) {
    m := &V1ItemSitetemplatesItemMacFiltersDenyRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/openapi/v1/{omadacId}/sitetemplates/{siteTemplateId}/mac-filters/deny?page={page}&pageSize={pageSize}", pathParameters),
    }
    return m
}
// NewV1ItemSitetemplatesItemMacFiltersDenyRequestBuilder instantiates a new V1ItemSitetemplatesItemMacFiltersDenyRequestBuilder and sets the default values.
func NewV1ItemSitetemplatesItemMacFiltersDenyRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitetemplatesItemMacFiltersDenyRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1ItemSitetemplatesItemMacFiltersDenyRequestBuilderInternal(urlParams, requestAdapter)
}
// Get get deny MAC filtering template list.
// returns a OperationResponseGridVOMacFilteringable when successful
func (m *V1ItemSitetemplatesItemMacFiltersDenyRequestBuilder) Get(ctx context.Context, requestConfiguration *V1ItemSitetemplatesItemMacFiltersDenyRequestBuilderGetRequestConfiguration)(i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.OperationResponseGridVOMacFilteringable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.CreateOperationResponseGridVOMacFilteringFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.OperationResponseGridVOMacFilteringable), nil
}
// ToGetRequestInformation get deny MAC filtering template list.
// returns a *RequestInformation when successful
func (m *V1ItemSitetemplatesItemMacFiltersDenyRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *V1ItemSitetemplatesItemMacFiltersDenyRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "*/*")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *V1ItemSitetemplatesItemMacFiltersDenyRequestBuilder when successful
func (m *V1ItemSitetemplatesItemMacFiltersDenyRequestBuilder) WithUrl(rawUrl string)(*V1ItemSitetemplatesItemMacFiltersDenyRequestBuilder) {
    return NewV1ItemSitetemplatesItemMacFiltersDenyRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
