// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package openapi

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V1ItemSitesItemOltsItemSystemSystemToolsRequestBuilder builds and executes requests for operations under \openapi\v1\{omadacId}\sites\{siteId}\olts\{deviceMac}\system\system-tools
type V1ItemSitesItemOltsItemSystemSystemToolsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewV1ItemSitesItemOltsItemSystemSystemToolsRequestBuilderInternal instantiates a new V1ItemSitesItemOltsItemSystemSystemToolsRequestBuilder and sets the default values.
func NewV1ItemSitesItemOltsItemSystemSystemToolsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitesItemOltsItemSystemSystemToolsRequestBuilder) {
    m := &V1ItemSitesItemOltsItemSystemSystemToolsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/openapi/v1/{omadacId}/sites/{siteId}/olts/{deviceMac}/system/system-tools", pathParameters),
    }
    return m
}
// NewV1ItemSitesItemOltsItemSystemSystemToolsRequestBuilder instantiates a new V1ItemSitesItemOltsItemSystemSystemToolsRequestBuilder and sets the default values.
func NewV1ItemSitesItemOltsItemSystemSystemToolsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitesItemOltsItemSystemSystemToolsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1ItemSitesItemOltsItemSystemSystemToolsRequestBuilderInternal(urlParams, requestAdapter)
}
// Reboot the reboot property
// returns a *V1ItemSitesItemOltsItemSystemSystemToolsRebootRequestBuilder when successful
func (m *V1ItemSitesItemOltsItemSystemSystemToolsRequestBuilder) Reboot()(*V1ItemSitesItemOltsItemSystemSystemToolsRebootRequestBuilder) {
    return NewV1ItemSitesItemOltsItemSystemSystemToolsRebootRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
