// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package openapi

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb "github.com/NerdIT-Tech/tplink-omada-sdk-for-go/models"
)

// V1ItemSitesItemFullChannelDetectItemApListRequestBuilder builds and executes requests for operations under \openapi\v1\{omadacId}\sites\{siteId}\full-channel-detect\{historyId}\ap-list
type V1ItemSitesItemFullChannelDetectItemApListRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// V1ItemSitesItemFullChannelDetectItemApListRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type V1ItemSitesItemFullChannelDetectItemApListRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewV1ItemSitesItemFullChannelDetectItemApListRequestBuilderInternal instantiates a new V1ItemSitesItemFullChannelDetectItemApListRequestBuilder and sets the default values.
func NewV1ItemSitesItemFullChannelDetectItemApListRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitesItemFullChannelDetectItemApListRequestBuilder) {
    m := &V1ItemSitesItemFullChannelDetectItemApListRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/openapi/v1/{omadacId}/sites/{siteId}/full-channel-detect/{historyId}/ap-list", pathParameters),
    }
    return m
}
// NewV1ItemSitesItemFullChannelDetectItemApListRequestBuilder instantiates a new V1ItemSitesItemFullChannelDetectItemApListRequestBuilder and sets the default values.
func NewV1ItemSitesItemFullChannelDetectItemApListRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitesItemFullChannelDetectItemApListRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1ItemSitesItemFullChannelDetectItemApListRequestBuilderInternal(urlParams, requestAdapter)
}
// Get get the AP list of batch interference detection
// returns a OperationResponseBatchFullChannelDetectApListOpenApiVOable when successful
func (m *V1ItemSitesItemFullChannelDetectItemApListRequestBuilder) Get(ctx context.Context, requestConfiguration *V1ItemSitesItemFullChannelDetectItemApListRequestBuilderGetRequestConfiguration)(i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.OperationResponseBatchFullChannelDetectApListOpenApiVOable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.CreateOperationResponseBatchFullChannelDetectApListOpenApiVOFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.OperationResponseBatchFullChannelDetectApListOpenApiVOable), nil
}
// ToGetRequestInformation get the AP list of batch interference detection
// returns a *RequestInformation when successful
func (m *V1ItemSitesItemFullChannelDetectItemApListRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *V1ItemSitesItemFullChannelDetectItemApListRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "*/*")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *V1ItemSitesItemFullChannelDetectItemApListRequestBuilder when successful
func (m *V1ItemSitesItemFullChannelDetectItemApListRequestBuilder) WithUrl(rawUrl string)(*V1ItemSitesItemFullChannelDetectItemApListRequestBuilder) {
    return NewV1ItemSitesItemFullChannelDetectItemApListRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
