// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package openapi

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V1ItemSitesItemSwitchesItemInterfaceRequestBuilder builds and executes requests for operations under \openapi\v1\{omadacId}\sites\{siteId}\switches\{switchMac}\interface
type V1ItemSitesItemSwitchesItemInterfaceRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ByOspfInterfaceId gets an item from the github.com/NerdIT-Tech/tplink-omada-sdk-for-go.openapi.v1.item.sites.item.switches.item.interface.item collection
// returns a *V1ItemSitesItemSwitchesItemInterfaceWithOspfInterfaceItemRequestBuilder when successful
func (m *V1ItemSitesItemSwitchesItemInterfaceRequestBuilder) ByOspfInterfaceId(ospfInterfaceId string)(*V1ItemSitesItemSwitchesItemInterfaceWithOspfInterfaceItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if ospfInterfaceId != "" {
        urlTplParams["ospfInterfaceId"] = ospfInterfaceId
    }
    return NewV1ItemSitesItemSwitchesItemInterfaceWithOspfInterfaceItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewV1ItemSitesItemSwitchesItemInterfaceRequestBuilderInternal instantiates a new V1ItemSitesItemSwitchesItemInterfaceRequestBuilder and sets the default values.
func NewV1ItemSitesItemSwitchesItemInterfaceRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitesItemSwitchesItemInterfaceRequestBuilder) {
    m := &V1ItemSitesItemSwitchesItemInterfaceRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/openapi/v1/{omadacId}/sites/{siteId}/switches/{switchMac}/interface", pathParameters),
    }
    return m
}
// NewV1ItemSitesItemSwitchesItemInterfaceRequestBuilder instantiates a new V1ItemSitesItemSwitchesItemInterfaceRequestBuilder and sets the default values.
func NewV1ItemSitesItemSwitchesItemInterfaceRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitesItemSwitchesItemInterfaceRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1ItemSitesItemSwitchesItemInterfaceRequestBuilderInternal(urlParams, requestAdapter)
}
