// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package openapi

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V1ItemSitesItemNatRequestBuilder builds and executes requests for operations under \openapi\v1\{omadacId}\sites\{siteId}\nat
type V1ItemSitesItemNatRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// Alg the alg property
// returns a *V1ItemSitesItemNatAlgRequestBuilder when successful
func (m *V1ItemSitesItemNatRequestBuilder) Alg()(*V1ItemSitesItemNatAlgRequestBuilder) {
    return NewV1ItemSitesItemNatAlgRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// NewV1ItemSitesItemNatRequestBuilderInternal instantiates a new V1ItemSitesItemNatRequestBuilder and sets the default values.
func NewV1ItemSitesItemNatRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitesItemNatRequestBuilder) {
    m := &V1ItemSitesItemNatRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/openapi/v1/{omadacId}/sites/{siteId}/nat", pathParameters),
    }
    return m
}
// NewV1ItemSitesItemNatRequestBuilder instantiates a new V1ItemSitesItemNatRequestBuilder and sets the default values.
func NewV1ItemSitesItemNatRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitesItemNatRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1ItemSitesItemNatRequestBuilderInternal(urlParams, requestAdapter)
}
// OneToOneNat the oneToOneNat property
// returns a *V1ItemSitesItemNatOneToOneNatRequestBuilder when successful
func (m *V1ItemSitesItemNatRequestBuilder) OneToOneNat()(*V1ItemSitesItemNatOneToOneNatRequestBuilder) {
    return NewV1ItemSitesItemNatOneToOneNatRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// PortForwardings the portForwardings property
// returns a *V1ItemSitesItemNatPortForwardingsRequestBuilder when successful
func (m *V1ItemSitesItemNatRequestBuilder) PortForwardings()(*V1ItemSitesItemNatPortForwardingsRequestBuilder) {
    return NewV1ItemSitesItemNatPortForwardingsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
