// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package openapi

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V1ItemSitesItemCmdStacksRequestBuilder builds and executes requests for operations under \openapi\v1\{omadacId}\sites\{siteId}\cmd\stacks
type V1ItemSitesItemCmdStacksRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ByStackId gets an item from the github.com/NerdIT-Tech/tplink-omada-sdk-for-go.openapi.v1.item.sites.item.cmd.stacks.item collection
// returns a *V1ItemSitesItemCmdStacksWithStackItemRequestBuilder when successful
func (m *V1ItemSitesItemCmdStacksRequestBuilder) ByStackId(stackId string)(*V1ItemSitesItemCmdStacksWithStackItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if stackId != "" {
        urlTplParams["stackId"] = stackId
    }
    return NewV1ItemSitesItemCmdStacksWithStackItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewV1ItemSitesItemCmdStacksRequestBuilderInternal instantiates a new V1ItemSitesItemCmdStacksRequestBuilder and sets the default values.
func NewV1ItemSitesItemCmdStacksRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitesItemCmdStacksRequestBuilder) {
    m := &V1ItemSitesItemCmdStacksRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/openapi/v1/{omadacId}/sites/{siteId}/cmd/stacks", pathParameters),
    }
    return m
}
// NewV1ItemSitesItemCmdStacksRequestBuilder instantiates a new V1ItemSitesItemCmdStacksRequestBuilder and sets the default values.
func NewV1ItemSitesItemCmdStacksRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitesItemCmdStacksRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1ItemSitesItemCmdStacksRequestBuilderInternal(urlParams, requestAdapter)
}
