// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package openapi

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb "github.com/NerdIT-Tech/tplink-omada-sdk-for-go/models"
)

// V1ItemSitesItemHotspotSurveysRequestBuilder builds and executes requests for operations under \openapi\v1\{omadacId}\sites\{siteId}\hotspot\surveys
type V1ItemSitesItemHotspotSurveysRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// V1ItemSitesItemHotspotSurveysRequestBuilderGetQueryParameters get authentication survey list in a site by the given omadacId, siteId.
type V1ItemSitesItemHotspotSurveysRequestBuilderGetQueryParameters struct {
    // Sort parameter may be one of asc or desc. Optional parameter. If it is not carried, it means it is not sorted by this field. When there are more than one, the first one takes effect
    SortsAnswerNum *string "uriparametername:\"sorts%2EanswerNum\""
    // Sort parameter may be one of asc or desc. Optional parameter. If it is not carried, it means it is not sorted by this field. When there are more than one, the first one takes effect
    SortsCreateTime *string "uriparametername:\"sorts%2EcreateTime\""
    // Sort parameter may be one of asc or desc. Optional parameter. If it is not carried, it means it is not sorted by this field. When there are more than one, the first one takes effect
    SortsName *string "uriparametername:\"sorts%2Ename\""
}
// V1ItemSitesItemHotspotSurveysRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type V1ItemSitesItemHotspotSurveysRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *V1ItemSitesItemHotspotSurveysRequestBuilderGetQueryParameters
}
// V1ItemSitesItemHotspotSurveysRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type V1ItemSitesItemHotspotSurveysRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// AuthResults the authResults property
// returns a *V1ItemSitesItemHotspotSurveysAuthResultsRequestBuilder when successful
func (m *V1ItemSitesItemHotspotSurveysRequestBuilder) AuthResults()(*V1ItemSitesItemHotspotSurveysAuthResultsRequestBuilder) {
    return NewV1ItemSitesItemHotspotSurveysAuthResultsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// BySurveyId gets an item from the github.com/NerdIT-Tech/tplink-omada-sdk-for-go.openapi.v1.item.sites.item.hotspot.surveys.item collection
// returns a *V1ItemSitesItemHotspotSurveysWithSurveyItemRequestBuilder when successful
func (m *V1ItemSitesItemHotspotSurveysRequestBuilder) BySurveyId(surveyId string)(*V1ItemSitesItemHotspotSurveysWithSurveyItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if surveyId != "" {
        urlTplParams["surveyId"] = surveyId
    }
    return NewV1ItemSitesItemHotspotSurveysWithSurveyItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewV1ItemSitesItemHotspotSurveysRequestBuilderInternal instantiates a new V1ItemSitesItemHotspotSurveysRequestBuilder and sets the default values.
func NewV1ItemSitesItemHotspotSurveysRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitesItemHotspotSurveysRequestBuilder) {
    m := &V1ItemSitesItemHotspotSurveysRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/openapi/v1/{omadacId}/sites/{siteId}/hotspot/surveys{?sorts%2EanswerNum*,sorts%2EcreateTime*,sorts%2Ename*}", pathParameters),
    }
    return m
}
// NewV1ItemSitesItemHotspotSurveysRequestBuilder instantiates a new V1ItemSitesItemHotspotSurveysRequestBuilder and sets the default values.
func NewV1ItemSitesItemHotspotSurveysRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitesItemHotspotSurveysRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1ItemSitesItemHotspotSurveysRequestBuilderInternal(urlParams, requestAdapter)
}
// Get get authentication survey list in a site by the given omadacId, siteId.
// returns a OperationResponseListFormAuthOpenApiVOable when successful
func (m *V1ItemSitesItemHotspotSurveysRequestBuilder) Get(ctx context.Context, requestConfiguration *V1ItemSitesItemHotspotSurveysRequestBuilderGetRequestConfiguration)(i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.OperationResponseListFormAuthOpenApiVOable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.CreateOperationResponseListFormAuthOpenApiVOFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.OperationResponseListFormAuthOpenApiVOable), nil
}
// Post create a authentication survey in a site with the given params.
// returns a OperationResponseCreatedResIdOpenApiVOable when successful
func (m *V1ItemSitesItemHotspotSurveysRequestBuilder) Post(ctx context.Context, body i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.CreateFormAuthOpenApiVOable, requestConfiguration *V1ItemSitesItemHotspotSurveysRequestBuilderPostRequestConfiguration)(i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.OperationResponseCreatedResIdOpenApiVOable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.CreateOperationResponseCreatedResIdOpenApiVOFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.OperationResponseCreatedResIdOpenApiVOable), nil
}
// ToGetRequestInformation get authentication survey list in a site by the given omadacId, siteId.
// returns a *RequestInformation when successful
func (m *V1ItemSitesItemHotspotSurveysRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *V1ItemSitesItemHotspotSurveysRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "*/*")
    return requestInfo, nil
}
// ToPostRequestInformation create a authentication survey in a site with the given params.
// returns a *RequestInformation when successful
func (m *V1ItemSitesItemHotspotSurveysRequestBuilder) ToPostRequestInformation(ctx context.Context, body i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.CreateFormAuthOpenApiVOable, requestConfiguration *V1ItemSitesItemHotspotSurveysRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "*/*")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *V1ItemSitesItemHotspotSurveysRequestBuilder when successful
func (m *V1ItemSitesItemHotspotSurveysRequestBuilder) WithUrl(rawUrl string)(*V1ItemSitesItemHotspotSurveysRequestBuilder) {
    return NewV1ItemSitesItemHotspotSurveysRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
