// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package openapi

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb "github.com/NerdIT-Tech/tplink-omada-sdk-for-go/models"
)

// V1ItemSitesItemMultiDevicesStartManuallyUpgradeRequestBuilder builds and executes requests for operations under \openapi\v1\{omadacId}\sites\{siteId}\multi-devices\start-manually-upgrade
type V1ItemSitesItemMultiDevicesStartManuallyUpgradeRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// V1ItemSitesItemMultiDevicesStartManuallyUpgradeRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type V1ItemSitesItemMultiDevicesStartManuallyUpgradeRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewV1ItemSitesItemMultiDevicesStartManuallyUpgradeRequestBuilderInternal instantiates a new V1ItemSitesItemMultiDevicesStartManuallyUpgradeRequestBuilder and sets the default values.
func NewV1ItemSitesItemMultiDevicesStartManuallyUpgradeRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitesItemMultiDevicesStartManuallyUpgradeRequestBuilder) {
    m := &V1ItemSitesItemMultiDevicesStartManuallyUpgradeRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/openapi/v1/{omadacId}/sites/{siteId}/multi-devices/start-manually-upgrade", pathParameters),
    }
    return m
}
// NewV1ItemSitesItemMultiDevicesStartManuallyUpgradeRequestBuilder instantiates a new V1ItemSitesItemMultiDevicesStartManuallyUpgradeRequestBuilder and sets the default values.
func NewV1ItemSitesItemMultiDevicesStartManuallyUpgradeRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitesItemMultiDevicesStartManuallyUpgradeRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1ItemSitesItemMultiDevicesStartManuallyUpgradeRequestBuilderInternal(urlParams, requestAdapter)
}
// Post manually upgrade the devices of the same model in the site. The firmware needs to be uploaded first. Note: Each site can only execute one multi-device upgrade task at a time, and there is a number limit of the tasks that can be executed simultaneously in the controller.
// returns a OperationResponseUpgradeTaskable when successful
func (m *V1ItemSitesItemMultiDevicesStartManuallyUpgradeRequestBuilder) Post(ctx context.Context, body i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.UpgradeRequestable, requestConfiguration *V1ItemSitesItemMultiDevicesStartManuallyUpgradeRequestBuilderPostRequestConfiguration)(i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.OperationResponseUpgradeTaskable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.CreateOperationResponseUpgradeTaskFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.OperationResponseUpgradeTaskable), nil
}
// ToPostRequestInformation manually upgrade the devices of the same model in the site. The firmware needs to be uploaded first. Note: Each site can only execute one multi-device upgrade task at a time, and there is a number limit of the tasks that can be executed simultaneously in the controller.
// returns a *RequestInformation when successful
func (m *V1ItemSitesItemMultiDevicesStartManuallyUpgradeRequestBuilder) ToPostRequestInformation(ctx context.Context, body i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.UpgradeRequestable, requestConfiguration *V1ItemSitesItemMultiDevicesStartManuallyUpgradeRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "*/*")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *V1ItemSitesItemMultiDevicesStartManuallyUpgradeRequestBuilder when successful
func (m *V1ItemSitesItemMultiDevicesStartManuallyUpgradeRequestBuilder) WithUrl(rawUrl string)(*V1ItemSitesItemMultiDevicesStartManuallyUpgradeRequestBuilder) {
    return NewV1ItemSitesItemMultiDevicesStartManuallyUpgradeRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
