// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package openapi

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V1ItemSitesItemOltsItemPonServicePortsRequestBuilder builds and executes requests for operations under \openapi\v1\{omadacId}\sites\{siteId}\olts\{deviceMac}\pon\service-ports
type V1ItemSitesItemOltsItemPonServicePortsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// Add the add property
// returns a *V1ItemSitesItemOltsItemPonServicePortsAddRequestBuilder when successful
func (m *V1ItemSitesItemOltsItemPonServicePortsRequestBuilder) Add()(*V1ItemSitesItemOltsItemPonServicePortsAddRequestBuilder) {
    return NewV1ItemSitesItemOltsItemPonServicePortsAddRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// NewV1ItemSitesItemOltsItemPonServicePortsRequestBuilderInternal instantiates a new V1ItemSitesItemOltsItemPonServicePortsRequestBuilder and sets the default values.
func NewV1ItemSitesItemOltsItemPonServicePortsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitesItemOltsItemPonServicePortsRequestBuilder) {
    m := &V1ItemSitesItemOltsItemPonServicePortsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/openapi/v1/{omadacId}/sites/{siteId}/olts/{deviceMac}/pon/service-ports", pathParameters),
    }
    return m
}
// NewV1ItemSitesItemOltsItemPonServicePortsRequestBuilder instantiates a new V1ItemSitesItemOltsItemPonServicePortsRequestBuilder and sets the default values.
func NewV1ItemSitesItemOltsItemPonServicePortsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitesItemOltsItemPonServicePortsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1ItemSitesItemOltsItemPonServicePortsRequestBuilderInternal(urlParams, requestAdapter)
}
// DeletePath the deletePath property
// returns a *V1ItemSitesItemOltsItemPonServicePortsDeleteRequestBuilder when successful
func (m *V1ItemSitesItemOltsItemPonServicePortsRequestBuilder) DeletePath()(*V1ItemSitesItemOltsItemPonServicePortsDeleteRequestBuilder) {
    return NewV1ItemSitesItemOltsItemPonServicePortsDeleteRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Edit the edit property
// returns a *V1ItemSitesItemOltsItemPonServicePortsEditRequestBuilder when successful
func (m *V1ItemSitesItemOltsItemPonServicePortsRequestBuilder) Edit()(*V1ItemSitesItemOltsItemPonServicePortsEditRequestBuilder) {
    return NewV1ItemSitesItemOltsItemPonServicePortsEditRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// List the list property
// returns a *V1ItemSitesItemOltsItemPonServicePortsListRequestBuilder when successful
func (m *V1ItemSitesItemOltsItemPonServicePortsRequestBuilder) List()(*V1ItemSitesItemOltsItemPonServicePortsListRequestBuilder) {
    return NewV1ItemSitesItemOltsItemPonServicePortsListRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Page the page property
// returns a *V1ItemSitesItemOltsItemPonServicePortsPageRequestBuilder when successful
func (m *V1ItemSitesItemOltsItemPonServicePortsRequestBuilder) Page()(*V1ItemSitesItemOltsItemPonServicePortsPageRequestBuilder) {
    return NewV1ItemSitesItemOltsItemPonServicePortsPageRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
