// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package openapi

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V1ItemSitesItemCmdSwitchesEsConfigRequestBuilder builds and executes requests for operations under \openapi\v1\{omadacId}\sites\{siteId}\cmd\switches\es\config
type V1ItemSitesItemCmdSwitchesEsConfigRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewV1ItemSitesItemCmdSwitchesEsConfigRequestBuilderInternal instantiates a new V1ItemSitesItemCmdSwitchesEsConfigRequestBuilder and sets the default values.
func NewV1ItemSitesItemCmdSwitchesEsConfigRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitesItemCmdSwitchesEsConfigRequestBuilder) {
    m := &V1ItemSitesItemCmdSwitchesEsConfigRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/openapi/v1/{omadacId}/sites/{siteId}/cmd/switches/es/config", pathParameters),
    }
    return m
}
// NewV1ItemSitesItemCmdSwitchesEsConfigRequestBuilder instantiates a new V1ItemSitesItemCmdSwitchesEsConfigRequestBuilder and sets the default values.
func NewV1ItemSitesItemCmdSwitchesEsConfigRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitesItemCmdSwitchesEsConfigRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1ItemSitesItemCmdSwitchesEsConfigRequestBuilderInternal(urlParams, requestAdapter)
}
// Loopback the loopback property
// returns a *V1ItemSitesItemCmdSwitchesEsConfigLoopbackRequestBuilder when successful
func (m *V1ItemSitesItemCmdSwitchesEsConfigRequestBuilder) Loopback()(*V1ItemSitesItemCmdSwitchesEsConfigLoopbackRequestBuilder) {
    return NewV1ItemSitesItemCmdSwitchesEsConfigLoopbackRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
