// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package openapi

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb "github.com/NerdIT-Tech/tplink-omada-sdk-for-go/models"
)

// V1ItemSitesItemProfilesBonjourServiceBonjourServiceItemRequestBuilder builds and executes requests for operations under \openapi\v1\{omadacId}\sites\{siteId}\profiles\bonjour-service\{id}
type V1ItemSitesItemProfilesBonjourServiceBonjourServiceItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// V1ItemSitesItemProfilesBonjourServiceBonjourServiceItemRequestBuilderDeleteRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type V1ItemSitesItemProfilesBonjourServiceBonjourServiceItemRequestBuilderDeleteRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// V1ItemSitesItemProfilesBonjourServiceBonjourServiceItemRequestBuilderPutRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type V1ItemSitesItemProfilesBonjourServiceBonjourServiceItemRequestBuilderPutRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewV1ItemSitesItemProfilesBonjourServiceBonjourServiceItemRequestBuilderInternal instantiates a new V1ItemSitesItemProfilesBonjourServiceBonjourServiceItemRequestBuilder and sets the default values.
func NewV1ItemSitesItemProfilesBonjourServiceBonjourServiceItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitesItemProfilesBonjourServiceBonjourServiceItemRequestBuilder) {
    m := &V1ItemSitesItemProfilesBonjourServiceBonjourServiceItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/openapi/v1/{omadacId}/sites/{siteId}/profiles/bonjour-service/{id}", pathParameters),
    }
    return m
}
// NewV1ItemSitesItemProfilesBonjourServiceBonjourServiceItemRequestBuilder instantiates a new V1ItemSitesItemProfilesBonjourServiceBonjourServiceItemRequestBuilder and sets the default values.
func NewV1ItemSitesItemProfilesBonjourServiceBonjourServiceItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitesItemProfilesBonjourServiceBonjourServiceItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1ItemSitesItemProfilesBonjourServiceBonjourServiceItemRequestBuilderInternal(urlParams, requestAdapter)
}
// Delete delete an existing Bonjour Service.
// returns a OperationResponseWithoutResultable when successful
func (m *V1ItemSitesItemProfilesBonjourServiceBonjourServiceItemRequestBuilder) Delete(ctx context.Context, requestConfiguration *V1ItemSitesItemProfilesBonjourServiceBonjourServiceItemRequestBuilderDeleteRequestConfiguration)(i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.OperationResponseWithoutResultable, error) {
    requestInfo, err := m.ToDeleteRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.CreateOperationResponseWithoutResultFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.OperationResponseWithoutResultable), nil
}
// Put modify an existing Bonjour Service.
// returns a OperationResponseWithoutResultable when successful
func (m *V1ItemSitesItemProfilesBonjourServiceBonjourServiceItemRequestBuilder) Put(ctx context.Context, body i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.BonjourServiceOpenApiVOable, requestConfiguration *V1ItemSitesItemProfilesBonjourServiceBonjourServiceItemRequestBuilderPutRequestConfiguration)(i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.OperationResponseWithoutResultable, error) {
    requestInfo, err := m.ToPutRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.CreateOperationResponseWithoutResultFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.OperationResponseWithoutResultable), nil
}
// ToDeleteRequestInformation delete an existing Bonjour Service.
// returns a *RequestInformation when successful
func (m *V1ItemSitesItemProfilesBonjourServiceBonjourServiceItemRequestBuilder) ToDeleteRequestInformation(ctx context.Context, requestConfiguration *V1ItemSitesItemProfilesBonjourServiceBonjourServiceItemRequestBuilderDeleteRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DELETE, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "*/*")
    return requestInfo, nil
}
// ToPutRequestInformation modify an existing Bonjour Service.
// returns a *RequestInformation when successful
func (m *V1ItemSitesItemProfilesBonjourServiceBonjourServiceItemRequestBuilder) ToPutRequestInformation(ctx context.Context, body i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.BonjourServiceOpenApiVOable, requestConfiguration *V1ItemSitesItemProfilesBonjourServiceBonjourServiceItemRequestBuilderPutRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.PUT, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "*/*")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *V1ItemSitesItemProfilesBonjourServiceBonjourServiceItemRequestBuilder when successful
func (m *V1ItemSitesItemProfilesBonjourServiceBonjourServiceItemRequestBuilder) WithUrl(rawUrl string)(*V1ItemSitesItemProfilesBonjourServiceBonjourServiceItemRequestBuilder) {
    return NewV1ItemSitesItemProfilesBonjourServiceBonjourServiceItemRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
