// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package openapi

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb "github.com/NerdIT-Tech/tplink-omada-sdk-for-go/models"
)

// V1ItemSitetemplatesItemUrlFiltersGatewayRequestBuilder builds and executes requests for operations under \openapi\v1\{omadacId}\sitetemplates\{siteTemplateId}\url-filters\gateway
type V1ItemSitetemplatesItemUrlFiltersGatewayRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// V1ItemSitetemplatesItemUrlFiltersGatewayRequestBuilderGetQueryParameters get URL filtering template rule list for gateway.
type V1ItemSitetemplatesItemUrlFiltersGatewayRequestBuilderGetQueryParameters struct {
    // Start page number. Start from 1.
    Page *int32 "uriparametername:\"page\""
    // Number of entries per page. It should be within the range of 1–1000.
    PageSize *int32 "uriparametername:\"pageSize\""
}
// V1ItemSitetemplatesItemUrlFiltersGatewayRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type V1ItemSitetemplatesItemUrlFiltersGatewayRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *V1ItemSitetemplatesItemUrlFiltersGatewayRequestBuilderGetQueryParameters
}
// NewV1ItemSitetemplatesItemUrlFiltersGatewayRequestBuilderInternal instantiates a new V1ItemSitetemplatesItemUrlFiltersGatewayRequestBuilder and sets the default values.
func NewV1ItemSitetemplatesItemUrlFiltersGatewayRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitetemplatesItemUrlFiltersGatewayRequestBuilder) {
    m := &V1ItemSitetemplatesItemUrlFiltersGatewayRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/openapi/v1/{omadacId}/sitetemplates/{siteTemplateId}/url-filters/gateway?page={page}&pageSize={pageSize}", pathParameters),
    }
    return m
}
// NewV1ItemSitetemplatesItemUrlFiltersGatewayRequestBuilder instantiates a new V1ItemSitetemplatesItemUrlFiltersGatewayRequestBuilder and sets the default values.
func NewV1ItemSitetemplatesItemUrlFiltersGatewayRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitetemplatesItemUrlFiltersGatewayRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1ItemSitetemplatesItemUrlFiltersGatewayRequestBuilderInternal(urlParams, requestAdapter)
}
// Get get URL filtering template rule list for gateway.
// returns a OperationResponseUrlFilteringOpenApiGridVOQueryUrlFilteringOpenApiVOable when successful
func (m *V1ItemSitetemplatesItemUrlFiltersGatewayRequestBuilder) Get(ctx context.Context, requestConfiguration *V1ItemSitetemplatesItemUrlFiltersGatewayRequestBuilderGetRequestConfiguration)(i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.OperationResponseUrlFilteringOpenApiGridVOQueryUrlFilteringOpenApiVOable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.CreateOperationResponseUrlFilteringOpenApiGridVOQueryUrlFilteringOpenApiVOFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.OperationResponseUrlFilteringOpenApiGridVOQueryUrlFilteringOpenApiVOable), nil
}
// ToGetRequestInformation get URL filtering template rule list for gateway.
// returns a *RequestInformation when successful
func (m *V1ItemSitetemplatesItemUrlFiltersGatewayRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *V1ItemSitetemplatesItemUrlFiltersGatewayRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "*/*")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *V1ItemSitetemplatesItemUrlFiltersGatewayRequestBuilder when successful
func (m *V1ItemSitetemplatesItemUrlFiltersGatewayRequestBuilder) WithUrl(rawUrl string)(*V1ItemSitetemplatesItemUrlFiltersGatewayRequestBuilder) {
    return NewV1ItemSitetemplatesItemUrlFiltersGatewayRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
