// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package openapi

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V1ItemSitetemplatesItemGatewaytemplatesItemConfigRequestBuilder builds and executes requests for operations under \openapi\v1\{omadacId}\sitetemplates\{siteTemplateId}\gatewaytemplates\{deviceTemplateId}\config
type V1ItemSitetemplatesItemGatewaytemplatesItemConfigRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// Advanced the advanced property
// returns a *V1ItemSitetemplatesItemGatewaytemplatesItemConfigAdvancedRequestBuilder when successful
func (m *V1ItemSitetemplatesItemGatewaytemplatesItemConfigRequestBuilder) Advanced()(*V1ItemSitetemplatesItemGatewaytemplatesItemConfigAdvancedRequestBuilder) {
    return NewV1ItemSitetemplatesItemGatewaytemplatesItemConfigAdvancedRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// NewV1ItemSitetemplatesItemGatewaytemplatesItemConfigRequestBuilderInternal instantiates a new V1ItemSitetemplatesItemGatewaytemplatesItemConfigRequestBuilder and sets the default values.
func NewV1ItemSitetemplatesItemGatewaytemplatesItemConfigRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitetemplatesItemGatewaytemplatesItemConfigRequestBuilder) {
    m := &V1ItemSitetemplatesItemGatewaytemplatesItemConfigRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/openapi/v1/{omadacId}/sitetemplates/{siteTemplateId}/gatewaytemplates/{deviceTemplateId}/config", pathParameters),
    }
    return m
}
// NewV1ItemSitetemplatesItemGatewaytemplatesItemConfigRequestBuilder instantiates a new V1ItemSitetemplatesItemGatewaytemplatesItemConfigRequestBuilder and sets the default values.
func NewV1ItemSitetemplatesItemGatewaytemplatesItemConfigRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitetemplatesItemGatewaytemplatesItemConfigRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1ItemSitetemplatesItemGatewaytemplatesItemConfigRequestBuilderInternal(urlParams, requestAdapter)
}
// General the general property
// returns a *V1ItemSitetemplatesItemGatewaytemplatesItemConfigGeneralRequestBuilder when successful
func (m *V1ItemSitetemplatesItemGatewaytemplatesItemConfigRequestBuilder) General()(*V1ItemSitetemplatesItemGatewaytemplatesItemConfigGeneralRequestBuilder) {
    return NewV1ItemSitetemplatesItemGatewaytemplatesItemConfigGeneralRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Radios the radios property
// returns a *V1ItemSitetemplatesItemGatewaytemplatesItemConfigRadiosRequestBuilder when successful
func (m *V1ItemSitetemplatesItemGatewaytemplatesItemConfigRequestBuilder) Radios()(*V1ItemSitetemplatesItemGatewaytemplatesItemConfigRadiosRequestBuilder) {
    return NewV1ItemSitetemplatesItemGatewaytemplatesItemConfigRadiosRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Services the services property
// returns a *V1ItemSitetemplatesItemGatewaytemplatesItemConfigServicesRequestBuilder when successful
func (m *V1ItemSitetemplatesItemGatewaytemplatesItemConfigRequestBuilder) Services()(*V1ItemSitetemplatesItemGatewaytemplatesItemConfigServicesRequestBuilder) {
    return NewV1ItemSitetemplatesItemGatewaytemplatesItemConfigServicesRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Wlans the wlans property
// returns a *V1ItemSitetemplatesItemGatewaytemplatesItemConfigWlansRequestBuilder when successful
func (m *V1ItemSitetemplatesItemGatewaytemplatesItemConfigRequestBuilder) Wlans()(*V1ItemSitetemplatesItemGatewaytemplatesItemConfigWlansRequestBuilder) {
    return NewV1ItemSitetemplatesItemGatewaytemplatesItemConfigWlansRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
