// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package openapi

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb "github.com/NerdIT-Tech/tplink-omada-sdk-for-go/models"
)

// V1ItemSitetemplatesItemMacFiltersRequestBuilder builds and executes requests for operations under \openapi\v1\{omadacId}\sitetemplates\{siteTemplateId}\mac-filters
type V1ItemSitetemplatesItemMacFiltersRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// V1ItemSitetemplatesItemMacFiltersRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type V1ItemSitetemplatesItemMacFiltersRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// Allow the allow property
// returns a *V1ItemSitetemplatesItemMacFiltersAllowRequestBuilder when successful
func (m *V1ItemSitetemplatesItemMacFiltersRequestBuilder) Allow()(*V1ItemSitetemplatesItemMacFiltersAllowRequestBuilder) {
    return NewV1ItemSitetemplatesItemMacFiltersAllowRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// ByFilterId gets an item from the github.com/NerdIT-Tech/tplink-omada-sdk-for-go.openapi.v1.item.sitetemplates.item.macFilters.item collection
// returns a *V1ItemSitetemplatesItemMacFiltersWithFilterItemRequestBuilder when successful
func (m *V1ItemSitetemplatesItemMacFiltersRequestBuilder) ByFilterId(filterId string)(*V1ItemSitetemplatesItemMacFiltersWithFilterItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if filterId != "" {
        urlTplParams["filterId"] = filterId
    }
    return NewV1ItemSitetemplatesItemMacFiltersWithFilterItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewV1ItemSitetemplatesItemMacFiltersRequestBuilderInternal instantiates a new V1ItemSitetemplatesItemMacFiltersRequestBuilder and sets the default values.
func NewV1ItemSitetemplatesItemMacFiltersRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitetemplatesItemMacFiltersRequestBuilder) {
    m := &V1ItemSitetemplatesItemMacFiltersRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/openapi/v1/{omadacId}/sitetemplates/{siteTemplateId}/mac-filters", pathParameters),
    }
    return m
}
// NewV1ItemSitetemplatesItemMacFiltersRequestBuilder instantiates a new V1ItemSitetemplatesItemMacFiltersRequestBuilder and sets the default values.
func NewV1ItemSitetemplatesItemMacFiltersRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitetemplatesItemMacFiltersRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1ItemSitetemplatesItemMacFiltersRequestBuilderInternal(urlParams, requestAdapter)
}
// Deny the deny property
// returns a *V1ItemSitetemplatesItemMacFiltersDenyRequestBuilder when successful
func (m *V1ItemSitetemplatesItemMacFiltersRequestBuilder) Deny()(*V1ItemSitetemplatesItemMacFiltersDenyRequestBuilder) {
    return NewV1ItemSitetemplatesItemMacFiltersDenyRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Post create MAC filtering template.
// returns a OperationResponseWithoutResultable when successful
func (m *V1ItemSitetemplatesItemMacFiltersRequestBuilder) Post(ctx context.Context, body i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.MacFilteringable, requestConfiguration *V1ItemSitetemplatesItemMacFiltersRequestBuilderPostRequestConfiguration)(i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.OperationResponseWithoutResultable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.CreateOperationResponseWithoutResultFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.OperationResponseWithoutResultable), nil
}
// ToPostRequestInformation create MAC filtering template.
// returns a *RequestInformation when successful
func (m *V1ItemSitetemplatesItemMacFiltersRequestBuilder) ToPostRequestInformation(ctx context.Context, body i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.MacFilteringable, requestConfiguration *V1ItemSitetemplatesItemMacFiltersRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "*/*")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *V1ItemSitetemplatesItemMacFiltersRequestBuilder when successful
func (m *V1ItemSitetemplatesItemMacFiltersRequestBuilder) WithUrl(rawUrl string)(*V1ItemSitetemplatesItemMacFiltersRequestBuilder) {
    return NewV1ItemSitetemplatesItemMacFiltersRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
