// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package openapi

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V1ItemSitesItemGridFullChannelDetectRequestBuilder builds and executes requests for operations under \openapi\v1\{omadacId}\sites\{siteId}\grid\full-channel-detect
type V1ItemSitesItemGridFullChannelDetectRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ApList the apList property
// returns a *V1ItemSitesItemGridFullChannelDetectApListRequestBuilder when successful
func (m *V1ItemSitesItemGridFullChannelDetectRequestBuilder) ApList()(*V1ItemSitesItemGridFullChannelDetectApListRequestBuilder) {
    return NewV1ItemSitesItemGridFullChannelDetectApListRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// NewV1ItemSitesItemGridFullChannelDetectRequestBuilderInternal instantiates a new V1ItemSitesItemGridFullChannelDetectRequestBuilder and sets the default values.
func NewV1ItemSitesItemGridFullChannelDetectRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitesItemGridFullChannelDetectRequestBuilder) {
    m := &V1ItemSitesItemGridFullChannelDetectRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/openapi/v1/{omadacId}/sites/{siteId}/grid/full-channel-detect", pathParameters),
    }
    return m
}
// NewV1ItemSitesItemGridFullChannelDetectRequestBuilder instantiates a new V1ItemSitesItemGridFullChannelDetectRequestBuilder and sets the default values.
func NewV1ItemSitesItemGridFullChannelDetectRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitesItemGridFullChannelDetectRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1ItemSitesItemGridFullChannelDetectRequestBuilderInternal(urlParams, requestAdapter)
}
