// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package openapi

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb "github.com/NerdIT-Tech/tplink-omada-sdk-for-go/models"
)

// V1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilder builds and executes requests for operations under \openapi\v1\{omadacId}\sitetemplates\{siteTemplateId}\network-security\ips
type V1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// V1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type V1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// V1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilderPatchRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type V1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilderPatchRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// AllowList the allowList property
// returns a *V1ItemSitetemplatesItemNetworkSecurityIpsAllowListRequestBuilder when successful
func (m *V1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilder) AllowList()(*V1ItemSitetemplatesItemNetworkSecurityIpsAllowListRequestBuilder) {
    return NewV1ItemSitetemplatesItemNetworkSecurityIpsAllowListRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// NewV1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilderInternal instantiates a new V1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilder and sets the default values.
func NewV1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilder) {
    m := &V1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/openapi/v1/{omadacId}/sitetemplates/{siteTemplateId}/network-security/ips", pathParameters),
    }
    return m
}
// NewV1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilder instantiates a new V1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilder and sets the default values.
func NewV1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilderInternal(urlParams, requestAdapter)
}
// Get get site template IDS/IPS config
// returns a OperationResponseIpsInfoable when successful
func (m *V1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilder) Get(ctx context.Context, requestConfiguration *V1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilderGetRequestConfiguration)(i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.OperationResponseIpsInfoable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.CreateOperationResponseIpsInfoFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.OperationResponseIpsInfoable), nil
}
// Patch modify site template IDS/IPS config
// returns a OperationResponseable when successful
func (m *V1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilder) Patch(ctx context.Context, body i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.IpsInfoable, requestConfiguration *V1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilderPatchRequestConfiguration)(i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.OperationResponseable, error) {
    requestInfo, err := m.ToPatchRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.CreateOperationResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.OperationResponseable), nil
}
// ToGetRequestInformation get site template IDS/IPS config
// returns a *RequestInformation when successful
func (m *V1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *V1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "*/*")
    return requestInfo, nil
}
// ToPatchRequestInformation modify site template IDS/IPS config
// returns a *RequestInformation when successful
func (m *V1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilder) ToPatchRequestInformation(ctx context.Context, body i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.IpsInfoable, requestConfiguration *V1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilderPatchRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.PATCH, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "*/*")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *V1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilder when successful
func (m *V1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilder) WithUrl(rawUrl string)(*V1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilder) {
    return NewV1ItemSitetemplatesItemNetworkSecurityIpsRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
