// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package openapi

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb "github.com/NerdIT-Tech/tplink-omada-sdk-for-go/models"
)

// V1ItemUpgradePlanModelsRequestsModelsRequestBuilder builds and executes requests for operations under \openapi\v1\{omadacId}\upgrade\plan\models
type V1ItemUpgradePlanModelsRequestsModelsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// V1ItemUpgradePlanModelsRequestsModelsRequestBuilderGetQueryParameters get the list of models on the Controller upgrade plan page.
type V1ItemUpgradePlanModelsRequestsModelsRequestBuilderGetQueryParameters struct {
    // Start page number. Start from 1.
    Page *int32 "uriparametername:\"page\""
    // Number of entries per page. It should be within the range of 1–1000.
    PageSize *int32 "uriparametername:\"pageSize\""
    // Fuzzy query parameters, support field upgrade
    SearchKey *string "uriparametername:\"searchKey\""
    // Sort parameter may be one of asc or desc. Optional parameter. If it is not carried, it means it is not sorted by this field. When there are more than one, the first one takes effect
    SortsModelTypeInfo *string "uriparametername:\"sorts%2EmodelTypeInfo\""
}
// V1ItemUpgradePlanModelsRequestsModelsRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type V1ItemUpgradePlanModelsRequestsModelsRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *V1ItemUpgradePlanModelsRequestsModelsRequestBuilderGetQueryParameters
}
// NewV1ItemUpgradePlanModelsRequestsModelsRequestBuilderInternal instantiates a new V1ItemUpgradePlanModelsRequestsModelsRequestBuilder and sets the default values.
func NewV1ItemUpgradePlanModelsRequestsModelsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemUpgradePlanModelsRequestsModelsRequestBuilder) {
    m := &V1ItemUpgradePlanModelsRequestsModelsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/openapi/v1/{omadacId}/upgrade/plan/models?page={page}&pageSize={pageSize}{&searchKey*,sorts%2EmodelTypeInfo*}", pathParameters),
    }
    return m
}
// NewV1ItemUpgradePlanModelsRequestsModelsRequestBuilder instantiates a new V1ItemUpgradePlanModelsRequestsModelsRequestBuilder and sets the default values.
func NewV1ItemUpgradePlanModelsRequestsModelsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1ItemUpgradePlanModelsRequestsModelsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1ItemUpgradePlanModelsRequestsModelsRequestBuilderInternal(urlParams, requestAdapter)
}
// Get get the list of models on the Controller upgrade plan page.
// returns a OperationResponseGridVOPlanUpgradeModelListable when successful
func (m *V1ItemUpgradePlanModelsRequestsModelsRequestBuilder) Get(ctx context.Context, requestConfiguration *V1ItemUpgradePlanModelsRequestsModelsRequestBuilderGetRequestConfiguration)(i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.OperationResponseGridVOPlanUpgradeModelListable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.CreateOperationResponseGridVOPlanUpgradeModelListFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i911d746b77a002701c2d6e267373658f70f0f6e4a5ce9a2b4a20fb2dcae77acb.OperationResponseGridVOPlanUpgradeModelListable), nil
}
// ToGetRequestInformation get the list of models on the Controller upgrade plan page.
// returns a *RequestInformation when successful
func (m *V1ItemUpgradePlanModelsRequestsModelsRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *V1ItemUpgradePlanModelsRequestsModelsRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "*/*")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *V1ItemUpgradePlanModelsRequestsModelsRequestBuilder when successful
func (m *V1ItemUpgradePlanModelsRequestsModelsRequestBuilder) WithUrl(rawUrl string)(*V1ItemUpgradePlanModelsRequestsModelsRequestBuilder) {
    return NewV1ItemUpgradePlanModelsRequestsModelsRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
