// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package openapi

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V1MspItemCustomersItemSitesItemOltsItemL2FeatureRequestBuilder builds and executes requests for operations under \openapi\v1\msp\{mspId}\customers\{customerId}\sites\{siteId}\olts\{deviceMac}\l2-feature
type V1MspItemCustomersItemSitesItemOltsItemL2FeatureRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewV1MspItemCustomersItemSitesItemOltsItemL2FeatureRequestBuilderInternal instantiates a new V1MspItemCustomersItemSitesItemOltsItemL2FeatureRequestBuilder and sets the default values.
func NewV1MspItemCustomersItemSitesItemOltsItemL2FeatureRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1MspItemCustomersItemSitesItemOltsItemL2FeatureRequestBuilder) {
    m := &V1MspItemCustomersItemSitesItemOltsItemL2FeatureRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/openapi/v1/msp/{mspId}/customers/{customerId}/sites/{siteId}/olts/{deviceMac}/l2-feature", pathParameters),
    }
    return m
}
// NewV1MspItemCustomersItemSitesItemOltsItemL2FeatureRequestBuilder instantiates a new V1MspItemCustomersItemSitesItemOltsItemL2FeatureRequestBuilder and sets the default values.
func NewV1MspItemCustomersItemSitesItemOltsItemL2FeatureRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1MspItemCustomersItemSitesItemOltsItemL2FeatureRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1MspItemCustomersItemSitesItemOltsItemL2FeatureRequestBuilderInternal(urlParams, requestAdapter)
}
// EthPort the ethPort property
// returns a *V1MspItemCustomersItemSitesItemOltsItemL2FeatureEthPortRequestBuilder when successful
func (m *V1MspItemCustomersItemSitesItemOltsItemL2FeatureRequestBuilder) EthPort()(*V1MspItemCustomersItemSitesItemOltsItemL2FeatureEthPortRequestBuilder) {
    return NewV1MspItemCustomersItemSitesItemOltsItemL2FeatureEthPortRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
