name: Labeler

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

permissions: {}

jobs:
  label:
    name: Apply Path Labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - uses: actions/labeler@b8dd2d9be0f68b860e7dae5dae7d772984eacd6d # v6
        with:
          configuration-path: .github/labeler.yml
          sync-labels: true
