// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ActiveClientsVO struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The mac property
    mac *string
    // The name property
    name *string
    // The traffic property
    traffic *int64
    // The trafficPercent property
    trafficPercent *int32
    // The type property
    typeEscaped *string
}
// NewActiveClientsVO instantiates a new ActiveClientsVO and sets the default values.
func NewActiveClientsVO()(*ActiveClientsVO) {
    m := &ActiveClientsVO{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateActiveClientsVOFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateActiveClientsVOFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewActiveClientsVO(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ActiveClientsVO) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ActiveClientsVO) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["mac"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMac(val)
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["traffic"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTraffic(val)
        }
        return nil
    }
    res["trafficPercent"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTrafficPercent(val)
        }
        return nil
    }
    res["type"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTypeEscaped(val)
        }
        return nil
    }
    return res
}
// GetMac gets the mac property value. The mac property
// returns a *string when successful
func (m *ActiveClientsVO) GetMac()(*string) {
    return m.mac
}
// GetName gets the name property value. The name property
// returns a *string when successful
func (m *ActiveClientsVO) GetName()(*string) {
    return m.name
}
// GetTraffic gets the traffic property value. The traffic property
// returns a *int64 when successful
func (m *ActiveClientsVO) GetTraffic()(*int64) {
    return m.traffic
}
// GetTrafficPercent gets the trafficPercent property value. The trafficPercent property
// returns a *int32 when successful
func (m *ActiveClientsVO) GetTrafficPercent()(*int32) {
    return m.trafficPercent
}
// GetTypeEscaped gets the type property value. The type property
// returns a *string when successful
func (m *ActiveClientsVO) GetTypeEscaped()(*string) {
    return m.typeEscaped
}
// Serialize serializes information the current object
func (m *ActiveClientsVO) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("mac", m.GetMac())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("traffic", m.GetTraffic())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("trafficPercent", m.GetTrafficPercent())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("type", m.GetTypeEscaped())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ActiveClientsVO) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetMac sets the mac property value. The mac property
func (m *ActiveClientsVO) SetMac(value *string)() {
    m.mac = value
}
// SetName sets the name property value. The name property
func (m *ActiveClientsVO) SetName(value *string)() {
    m.name = value
}
// SetTraffic sets the traffic property value. The traffic property
func (m *ActiveClientsVO) SetTraffic(value *int64)() {
    m.traffic = value
}
// SetTrafficPercent sets the trafficPercent property value. The trafficPercent property
func (m *ActiveClientsVO) SetTrafficPercent(value *int32)() {
    m.trafficPercent = value
}
// SetTypeEscaped sets the type property value. The type property
func (m *ActiveClientsVO) SetTypeEscaped(value *string)() {
    m.typeEscaped = value
}
type ActiveClientsVOable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetMac()(*string)
    GetName()(*string)
    GetTraffic()(*int64)
    GetTrafficPercent()(*int32)
    GetTypeEscaped()(*string)
    SetMac(value *string)()
    SetName(value *string)()
    SetTraffic(value *int64)()
    SetTrafficPercent(value *int32)()
    SetTypeEscaped(value *string)()
}
