// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ApInterferences struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // 2GHz device interference intensity information
    apInterference2g []ApInterferenceable
    // 5GHz device interference intensity information
    apInterference5g []ApInterferenceable
    // 5GHz-2 device interference intensity information
    apInterference5g2 []ApInterferenceable
    // 6GHz device interference intensity information
    apInterference6g []ApInterferenceable
}
// NewApInterferences instantiates a new ApInterferences and sets the default values.
func NewApInterferences()(*ApInterferences) {
    m := &ApInterferences{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateApInterferencesFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateApInterferencesFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewApInterferences(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ApInterferences) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetApInterference2g gets the apInterference2g property value. 2GHz device interference intensity information
// returns a []ApInterferenceable when successful
func (m *ApInterferences) GetApInterference2g()([]ApInterferenceable) {
    return m.apInterference2g
}
// GetApInterference5g gets the apInterference5g property value. 5GHz device interference intensity information
// returns a []ApInterferenceable when successful
func (m *ApInterferences) GetApInterference5g()([]ApInterferenceable) {
    return m.apInterference5g
}
// GetApInterference5g2 gets the apInterference5g2 property value. 5GHz-2 device interference intensity information
// returns a []ApInterferenceable when successful
func (m *ApInterferences) GetApInterference5g2()([]ApInterferenceable) {
    return m.apInterference5g2
}
// GetApInterference6g gets the apInterference6g property value. 6GHz device interference intensity information
// returns a []ApInterferenceable when successful
func (m *ApInterferences) GetApInterference6g()([]ApInterferenceable) {
    return m.apInterference6g
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ApInterferences) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["apInterference2g"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateApInterferenceFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]ApInterferenceable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(ApInterferenceable)
                }
            }
            m.SetApInterference2g(res)
        }
        return nil
    }
    res["apInterference5g"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateApInterferenceFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]ApInterferenceable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(ApInterferenceable)
                }
            }
            m.SetApInterference5g(res)
        }
        return nil
    }
    res["apInterference5g2"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateApInterferenceFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]ApInterferenceable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(ApInterferenceable)
                }
            }
            m.SetApInterference5g2(res)
        }
        return nil
    }
    res["apInterference6g"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateApInterferenceFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]ApInterferenceable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(ApInterferenceable)
                }
            }
            m.SetApInterference6g(res)
        }
        return nil
    }
    return res
}
// Serialize serializes information the current object
func (m *ApInterferences) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetApInterference2g() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetApInterference2g()))
        for i, v := range m.GetApInterference2g() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("apInterference2g", cast)
        if err != nil {
            return err
        }
    }
    if m.GetApInterference5g() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetApInterference5g()))
        for i, v := range m.GetApInterference5g() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("apInterference5g", cast)
        if err != nil {
            return err
        }
    }
    if m.GetApInterference5g2() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetApInterference5g2()))
        for i, v := range m.GetApInterference5g2() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("apInterference5g2", cast)
        if err != nil {
            return err
        }
    }
    if m.GetApInterference6g() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetApInterference6g()))
        for i, v := range m.GetApInterference6g() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("apInterference6g", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ApInterferences) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetApInterference2g sets the apInterference2g property value. 2GHz device interference intensity information
func (m *ApInterferences) SetApInterference2g(value []ApInterferenceable)() {
    m.apInterference2g = value
}
// SetApInterference5g sets the apInterference5g property value. 5GHz device interference intensity information
func (m *ApInterferences) SetApInterference5g(value []ApInterferenceable)() {
    m.apInterference5g = value
}
// SetApInterference5g2 sets the apInterference5g2 property value. 5GHz-2 device interference intensity information
func (m *ApInterferences) SetApInterference5g2(value []ApInterferenceable)() {
    m.apInterference5g2 = value
}
// SetApInterference6g sets the apInterference6g property value. 6GHz device interference intensity information
func (m *ApInterferences) SetApInterference6g(value []ApInterferenceable)() {
    m.apInterference6g = value
}
type ApInterferencesable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetApInterference2g()([]ApInterferenceable)
    GetApInterference5g()([]ApInterferenceable)
    GetApInterference5g2()([]ApInterferenceable)
    GetApInterference6g()([]ApInterferenceable)
    SetApInterference2g(value []ApInterferenceable)()
    SetApInterference5g(value []ApInterferenceable)()
    SetApInterference5g2(value []ApInterferenceable)()
    SetApInterference6g(value []ApInterferenceable)()
}
