// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// AuthTimeOpenApiVO authentication timeout time. Display when enabled, otherwise no display.
type AuthTimeOpenApiVO struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Validity period should be a value as follows: 0: Custom; 1: 30 Minutes; 2: 1 Hour; 3: 2 Hours; 4: 4 Hours; 5: 8 Hours; 6: 1 Day; 7: 7 Days integer.
    authTimeout *int32
    // Custom timeout should be within the range of 1 ~ 1,000,000 minutes(when parameter[customTimeoutUnit] value is 1), or 1 ~ 10,000 hours(when parameter[customTimeoutUnit] value is 2), or 1 ~ 1,000 days(when parameter[customTimeoutUnit] value is 3).
    customTimeout *int32
    // Custom timeout unit should be a value as follows: 1: min; 2: hour; 3: day.
    customTimeoutUnit *int32
}
// NewAuthTimeOpenApiVO instantiates a new AuthTimeOpenApiVO and sets the default values.
func NewAuthTimeOpenApiVO()(*AuthTimeOpenApiVO) {
    m := &AuthTimeOpenApiVO{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateAuthTimeOpenApiVOFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAuthTimeOpenApiVOFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAuthTimeOpenApiVO(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *AuthTimeOpenApiVO) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAuthTimeout gets the authTimeout property value. Validity period should be a value as follows: 0: Custom; 1: 30 Minutes; 2: 1 Hour; 3: 2 Hours; 4: 4 Hours; 5: 8 Hours; 6: 1 Day; 7: 7 Days integer.
// returns a *int32 when successful
func (m *AuthTimeOpenApiVO) GetAuthTimeout()(*int32) {
    return m.authTimeout
}
// GetCustomTimeout gets the customTimeout property value. Custom timeout should be within the range of 1 ~ 1,000,000 minutes(when parameter[customTimeoutUnit] value is 1), or 1 ~ 10,000 hours(when parameter[customTimeoutUnit] value is 2), or 1 ~ 1,000 days(when parameter[customTimeoutUnit] value is 3).
// returns a *int32 when successful
func (m *AuthTimeOpenApiVO) GetCustomTimeout()(*int32) {
    return m.customTimeout
}
// GetCustomTimeoutUnit gets the customTimeoutUnit property value. Custom timeout unit should be a value as follows: 1: min; 2: hour; 3: day.
// returns a *int32 when successful
func (m *AuthTimeOpenApiVO) GetCustomTimeoutUnit()(*int32) {
    return m.customTimeoutUnit
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *AuthTimeOpenApiVO) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["authTimeout"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAuthTimeout(val)
        }
        return nil
    }
    res["customTimeout"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCustomTimeout(val)
        }
        return nil
    }
    res["customTimeoutUnit"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCustomTimeoutUnit(val)
        }
        return nil
    }
    return res
}
// Serialize serializes information the current object
func (m *AuthTimeOpenApiVO) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteInt32Value("authTimeout", m.GetAuthTimeout())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("customTimeout", m.GetCustomTimeout())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("customTimeoutUnit", m.GetCustomTimeoutUnit())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *AuthTimeOpenApiVO) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAuthTimeout sets the authTimeout property value. Validity period should be a value as follows: 0: Custom; 1: 30 Minutes; 2: 1 Hour; 3: 2 Hours; 4: 4 Hours; 5: 8 Hours; 6: 1 Day; 7: 7 Days integer.
func (m *AuthTimeOpenApiVO) SetAuthTimeout(value *int32)() {
    m.authTimeout = value
}
// SetCustomTimeout sets the customTimeout property value. Custom timeout should be within the range of 1 ~ 1,000,000 minutes(when parameter[customTimeoutUnit] value is 1), or 1 ~ 10,000 hours(when parameter[customTimeoutUnit] value is 2), or 1 ~ 1,000 days(when parameter[customTimeoutUnit] value is 3).
func (m *AuthTimeOpenApiVO) SetCustomTimeout(value *int32)() {
    m.customTimeout = value
}
// SetCustomTimeoutUnit sets the customTimeoutUnit property value. Custom timeout unit should be a value as follows: 1: min; 2: hour; 3: day.
func (m *AuthTimeOpenApiVO) SetCustomTimeoutUnit(value *int32)() {
    m.customTimeoutUnit = value
}
type AuthTimeOpenApiVOable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAuthTimeout()(*int32)
    GetCustomTimeout()(*int32)
    GetCustomTimeoutUnit()(*int32)
    SetAuthTimeout(value *int32)()
    SetCustomTimeout(value *int32)()
    SetCustomTimeoutUnit(value *int32)()
}
