// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
// EtherType should be a value as follows:NONE,IPV4OE,IPV6OE,PPPOE
type AutoServicePortDTO_etherType int

const (
    NONE_AUTOSERVICEPORTDTO_ETHERTYPE AutoServicePortDTO_etherType = iota
    IPV4OE_AUTOSERVICEPORTDTO_ETHERTYPE
    IPV6OE_AUTOSERVICEPORTDTO_ETHERTYPE
    PPPOE_AUTOSERVICEPORTDTO_ETHERTYPE
)

func (i AutoServicePortDTO_etherType) String() string {
    return []string{"NONE", "IPV4OE", "IPV6OE", "PPPOE"}[i]
}
func ParseAutoServicePortDTO_etherType(v string) (any, error) {
    result := NONE_AUTOSERVICEPORTDTO_ETHERTYPE
    switch v {
        case "NONE":
            result = NONE_AUTOSERVICEPORTDTO_ETHERTYPE
        case "IPV4OE":
            result = IPV4OE_AUTOSERVICEPORTDTO_ETHERTYPE
        case "IPV6OE":
            result = IPV6OE_AUTOSERVICEPORTDTO_ETHERTYPE
        case "PPPOE":
            result = PPPOE_AUTOSERVICEPORTDTO_ETHERTYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeAutoServicePortDTO_etherType(values []AutoServicePortDTO_etherType) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i AutoServicePortDTO_etherType) isMultiValue() bool {
    return false
}
