// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type BatchSyncSitesOpenApiVO struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Site IDs to sync with site template.
    siteIds []string
}
// NewBatchSyncSitesOpenApiVO instantiates a new BatchSyncSitesOpenApiVO and sets the default values.
func NewBatchSyncSitesOpenApiVO()(*BatchSyncSitesOpenApiVO) {
    m := &BatchSyncSitesOpenApiVO{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateBatchSyncSitesOpenApiVOFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateBatchSyncSitesOpenApiVOFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewBatchSyncSitesOpenApiVO(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *BatchSyncSitesOpenApiVO) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *BatchSyncSitesOpenApiVO) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["siteIds"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("string")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]string, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*string))
                }
            }
            m.SetSiteIds(res)
        }
        return nil
    }
    return res
}
// GetSiteIds gets the siteIds property value. Site IDs to sync with site template.
// returns a []string when successful
func (m *BatchSyncSitesOpenApiVO) GetSiteIds()([]string) {
    return m.siteIds
}
// Serialize serializes information the current object
func (m *BatchSyncSitesOpenApiVO) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetSiteIds() != nil {
        err := writer.WriteCollectionOfStringValues("siteIds", m.GetSiteIds())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *BatchSyncSitesOpenApiVO) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetSiteIds sets the siteIds property value. Site IDs to sync with site template.
func (m *BatchSyncSitesOpenApiVO) SetSiteIds(value []string)() {
    m.siteIds = value
}
type BatchSyncSitesOpenApiVOable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetSiteIds()([]string)
    SetSiteIds(value []string)()
}
