// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type BatchSiteImportVO struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // File server configuration.
    fileServerConfig FileServerOpenApiVOable
    // Site import config list. max size 300.
    siteImportConfigList []SiteImportOpenApiVOable
}
// NewBatchSiteImportVO instantiates a new BatchSiteImportVO and sets the default values.
func NewBatchSiteImportVO()(*BatchSiteImportVO) {
    m := &BatchSiteImportVO{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateBatchSiteImportVOFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateBatchSiteImportVOFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewBatchSiteImportVO(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *BatchSiteImportVO) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *BatchSiteImportVO) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["fileServerConfig"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateFileServerOpenApiVOFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFileServerConfig(val.(FileServerOpenApiVOable))
        }
        return nil
    }
    res["siteImportConfigList"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateSiteImportOpenApiVOFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]SiteImportOpenApiVOable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(SiteImportOpenApiVOable)
                }
            }
            m.SetSiteImportConfigList(res)
        }
        return nil
    }
    return res
}
// GetFileServerConfig gets the fileServerConfig property value. File server configuration.
// returns a FileServerOpenApiVOable when successful
func (m *BatchSiteImportVO) GetFileServerConfig()(FileServerOpenApiVOable) {
    return m.fileServerConfig
}
// GetSiteImportConfigList gets the siteImportConfigList property value. Site import config list. max size 300.
// returns a []SiteImportOpenApiVOable when successful
func (m *BatchSiteImportVO) GetSiteImportConfigList()([]SiteImportOpenApiVOable) {
    return m.siteImportConfigList
}
// Serialize serializes information the current object
func (m *BatchSiteImportVO) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("fileServerConfig", m.GetFileServerConfig())
        if err != nil {
            return err
        }
    }
    if m.GetSiteImportConfigList() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetSiteImportConfigList()))
        for i, v := range m.GetSiteImportConfigList() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("siteImportConfigList", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *BatchSiteImportVO) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetFileServerConfig sets the fileServerConfig property value. File server configuration.
func (m *BatchSiteImportVO) SetFileServerConfig(value FileServerOpenApiVOable)() {
    m.fileServerConfig = value
}
// SetSiteImportConfigList sets the siteImportConfigList property value. Site import config list. max size 300.
func (m *BatchSiteImportVO) SetSiteImportConfigList(value []SiteImportOpenApiVOable)() {
    m.siteImportConfigList = value
}
type BatchSiteImportVOable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetFileServerConfig()(FileServerOpenApiVOable)
    GetSiteImportConfigList()([]SiteImportOpenApiVOable)
    SetFileServerConfig(value FileServerOpenApiVOable)()
    SetSiteImportConfigList(value []SiteImportOpenApiVOable)()
}
