// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ClientActiveTimeout struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Client Active Timeout should be within the range of 3-10 minutes
    clientActiveTimeoutMin *int32
}
// NewClientActiveTimeout instantiates a new ClientActiveTimeout and sets the default values.
func NewClientActiveTimeout()(*ClientActiveTimeout) {
    m := &ClientActiveTimeout{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateClientActiveTimeoutFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateClientActiveTimeoutFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewClientActiveTimeout(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ClientActiveTimeout) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetClientActiveTimeoutMin gets the clientActiveTimeoutMin property value. Client Active Timeout should be within the range of 3-10 minutes
// returns a *int32 when successful
func (m *ClientActiveTimeout) GetClientActiveTimeoutMin()(*int32) {
    return m.clientActiveTimeoutMin
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ClientActiveTimeout) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["clientActiveTimeoutMin"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetClientActiveTimeoutMin(val)
        }
        return nil
    }
    return res
}
// Serialize serializes information the current object
func (m *ClientActiveTimeout) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteInt32Value("clientActiveTimeoutMin", m.GetClientActiveTimeoutMin())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ClientActiveTimeout) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetClientActiveTimeoutMin sets the clientActiveTimeoutMin property value. Client Active Timeout should be within the range of 3-10 minutes
func (m *ClientActiveTimeout) SetClientActiveTimeoutMin(value *int32)() {
    m.clientActiveTimeoutMin = value
}
type ClientActiveTimeoutable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetClientActiveTimeoutMin()(*int32)
    SetClientActiveTimeoutMin(value *int32)()
}
