// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ClientLockToApSetting client lock to ap setting.
type ClientLockToApSetting struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // AP name and MAC info list.
    aps []ApBriefInfoVOable
    // Lock to AP enable.
    enable *bool
}
// NewClientLockToApSetting instantiates a new ClientLockToApSetting and sets the default values.
func NewClientLockToApSetting()(*ClientLockToApSetting) {
    m := &ClientLockToApSetting{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateClientLockToApSettingFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateClientLockToApSettingFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewClientLockToApSetting(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ClientLockToApSetting) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAps gets the aps property value. AP name and MAC info list.
// returns a []ApBriefInfoVOable when successful
func (m *ClientLockToApSetting) GetAps()([]ApBriefInfoVOable) {
    return m.aps
}
// GetEnable gets the enable property value. Lock to AP enable.
// returns a *bool when successful
func (m *ClientLockToApSetting) GetEnable()(*bool) {
    return m.enable
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ClientLockToApSetting) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["aps"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateApBriefInfoVOFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]ApBriefInfoVOable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(ApBriefInfoVOable)
                }
            }
            m.SetAps(res)
        }
        return nil
    }
    res["enable"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEnable(val)
        }
        return nil
    }
    return res
}
// Serialize serializes information the current object
func (m *ClientLockToApSetting) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetAps() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetAps()))
        for i, v := range m.GetAps() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("aps", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("enable", m.GetEnable())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ClientLockToApSetting) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAps sets the aps property value. AP name and MAC info list.
func (m *ClientLockToApSetting) SetAps(value []ApBriefInfoVOable)() {
    m.aps = value
}
// SetEnable sets the enable property value. Lock to AP enable.
func (m *ClientLockToApSetting) SetEnable(value *bool)() {
    m.enable = value
}
type ClientLockToApSettingable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAps()([]ApBriefInfoVOable)
    GetEnable()(*bool)
    SetAps(value []ApBriefInfoVOable)()
    SetEnable(value *bool)()
}
