// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ClientGridVOClientInfo struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The clientStat property
    clientStat ClientStatVOable
    // The clientTypeStat property
    clientTypeStat ClientTypeStatVOable
    // Current page number.
    currentPage *int32
    // Number of entries per page.
    currentSize *int32
    // The data property
    data []ClientInfoable
    // Total rows of all items.
    totalRows *int64
}
// NewClientGridVOClientInfo instantiates a new ClientGridVOClientInfo and sets the default values.
func NewClientGridVOClientInfo()(*ClientGridVOClientInfo) {
    m := &ClientGridVOClientInfo{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateClientGridVOClientInfoFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateClientGridVOClientInfoFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewClientGridVOClientInfo(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ClientGridVOClientInfo) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetClientStat gets the clientStat property value. The clientStat property
// returns a ClientStatVOable when successful
func (m *ClientGridVOClientInfo) GetClientStat()(ClientStatVOable) {
    return m.clientStat
}
// GetClientTypeStat gets the clientTypeStat property value. The clientTypeStat property
// returns a ClientTypeStatVOable when successful
func (m *ClientGridVOClientInfo) GetClientTypeStat()(ClientTypeStatVOable) {
    return m.clientTypeStat
}
// GetCurrentPage gets the currentPage property value. Current page number.
// returns a *int32 when successful
func (m *ClientGridVOClientInfo) GetCurrentPage()(*int32) {
    return m.currentPage
}
// GetCurrentSize gets the currentSize property value. Number of entries per page.
// returns a *int32 when successful
func (m *ClientGridVOClientInfo) GetCurrentSize()(*int32) {
    return m.currentSize
}
// GetData gets the data property value. The data property
// returns a []ClientInfoable when successful
func (m *ClientGridVOClientInfo) GetData()([]ClientInfoable) {
    return m.data
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ClientGridVOClientInfo) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["clientStat"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateClientStatVOFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetClientStat(val.(ClientStatVOable))
        }
        return nil
    }
    res["clientTypeStat"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateClientTypeStatVOFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetClientTypeStat(val.(ClientTypeStatVOable))
        }
        return nil
    }
    res["currentPage"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCurrentPage(val)
        }
        return nil
    }
    res["currentSize"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCurrentSize(val)
        }
        return nil
    }
    res["data"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateClientInfoFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]ClientInfoable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(ClientInfoable)
                }
            }
            m.SetData(res)
        }
        return nil
    }
    res["totalRows"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTotalRows(val)
        }
        return nil
    }
    return res
}
// GetTotalRows gets the totalRows property value. Total rows of all items.
// returns a *int64 when successful
func (m *ClientGridVOClientInfo) GetTotalRows()(*int64) {
    return m.totalRows
}
// Serialize serializes information the current object
func (m *ClientGridVOClientInfo) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("clientStat", m.GetClientStat())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("clientTypeStat", m.GetClientTypeStat())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("currentPage", m.GetCurrentPage())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("currentSize", m.GetCurrentSize())
        if err != nil {
            return err
        }
    }
    if m.GetData() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetData()))
        for i, v := range m.GetData() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("data", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("totalRows", m.GetTotalRows())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ClientGridVOClientInfo) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetClientStat sets the clientStat property value. The clientStat property
func (m *ClientGridVOClientInfo) SetClientStat(value ClientStatVOable)() {
    m.clientStat = value
}
// SetClientTypeStat sets the clientTypeStat property value. The clientTypeStat property
func (m *ClientGridVOClientInfo) SetClientTypeStat(value ClientTypeStatVOable)() {
    m.clientTypeStat = value
}
// SetCurrentPage sets the currentPage property value. Current page number.
func (m *ClientGridVOClientInfo) SetCurrentPage(value *int32)() {
    m.currentPage = value
}
// SetCurrentSize sets the currentSize property value. Number of entries per page.
func (m *ClientGridVOClientInfo) SetCurrentSize(value *int32)() {
    m.currentSize = value
}
// SetData sets the data property value. The data property
func (m *ClientGridVOClientInfo) SetData(value []ClientInfoable)() {
    m.data = value
}
// SetTotalRows sets the totalRows property value. Total rows of all items.
func (m *ClientGridVOClientInfo) SetTotalRows(value *int64)() {
    m.totalRows = value
}
type ClientGridVOClientInfoable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetClientStat()(ClientStatVOable)
    GetClientTypeStat()(ClientTypeStatVOable)
    GetCurrentPage()(*int32)
    GetCurrentSize()(*int32)
    GetData()([]ClientInfoable)
    GetTotalRows()(*int64)
    SetClientStat(value ClientStatVOable)()
    SetClientTypeStat(value ClientTypeStatVOable)()
    SetCurrentPage(value *int32)()
    SetCurrentSize(value *int32)()
    SetData(value []ClientInfoable)()
    SetTotalRows(value *int64)()
}
