// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ClientAssociationTimeDistributionVO struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The fails property
    fails *int32
    // The from2To4sNum property
    from2To4sNum *int32
    // The from4To6sNum property
    from4To6sNum *int32
    // The from6To8sNum property
    from6To8sNum *int32
    // The from8To10sNum property
    from8To10sNum *int32
    // The lessThan10sPercent property
    lessThan10sPercent *int32
    // The lessThan2sNum property
    lessThan2sNum *int32
    // The moreThan10sNum property
    moreThan10sNum *int32
}
// NewClientAssociationTimeDistributionVO instantiates a new ClientAssociationTimeDistributionVO and sets the default values.
func NewClientAssociationTimeDistributionVO()(*ClientAssociationTimeDistributionVO) {
    m := &ClientAssociationTimeDistributionVO{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateClientAssociationTimeDistributionVOFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateClientAssociationTimeDistributionVOFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewClientAssociationTimeDistributionVO(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ClientAssociationTimeDistributionVO) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFails gets the fails property value. The fails property
// returns a *int32 when successful
func (m *ClientAssociationTimeDistributionVO) GetFails()(*int32) {
    return m.fails
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ClientAssociationTimeDistributionVO) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["fails"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFails(val)
        }
        return nil
    }
    res["from2To4sNum"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFrom2To4sNum(val)
        }
        return nil
    }
    res["from4To6sNum"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFrom4To6sNum(val)
        }
        return nil
    }
    res["from6To8sNum"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFrom6To8sNum(val)
        }
        return nil
    }
    res["from8To10sNum"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFrom8To10sNum(val)
        }
        return nil
    }
    res["lessThan10sPercent"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLessThan10sPercent(val)
        }
        return nil
    }
    res["lessThan2sNum"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLessThan2sNum(val)
        }
        return nil
    }
    res["moreThan10sNum"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMoreThan10sNum(val)
        }
        return nil
    }
    return res
}
// GetFrom2To4sNum gets the from2To4sNum property value. The from2To4sNum property
// returns a *int32 when successful
func (m *ClientAssociationTimeDistributionVO) GetFrom2To4sNum()(*int32) {
    return m.from2To4sNum
}
// GetFrom4To6sNum gets the from4To6sNum property value. The from4To6sNum property
// returns a *int32 when successful
func (m *ClientAssociationTimeDistributionVO) GetFrom4To6sNum()(*int32) {
    return m.from4To6sNum
}
// GetFrom6To8sNum gets the from6To8sNum property value. The from6To8sNum property
// returns a *int32 when successful
func (m *ClientAssociationTimeDistributionVO) GetFrom6To8sNum()(*int32) {
    return m.from6To8sNum
}
// GetFrom8To10sNum gets the from8To10sNum property value. The from8To10sNum property
// returns a *int32 when successful
func (m *ClientAssociationTimeDistributionVO) GetFrom8To10sNum()(*int32) {
    return m.from8To10sNum
}
// GetLessThan10sPercent gets the lessThan10sPercent property value. The lessThan10sPercent property
// returns a *int32 when successful
func (m *ClientAssociationTimeDistributionVO) GetLessThan10sPercent()(*int32) {
    return m.lessThan10sPercent
}
// GetLessThan2sNum gets the lessThan2sNum property value. The lessThan2sNum property
// returns a *int32 when successful
func (m *ClientAssociationTimeDistributionVO) GetLessThan2sNum()(*int32) {
    return m.lessThan2sNum
}
// GetMoreThan10sNum gets the moreThan10sNum property value. The moreThan10sNum property
// returns a *int32 when successful
func (m *ClientAssociationTimeDistributionVO) GetMoreThan10sNum()(*int32) {
    return m.moreThan10sNum
}
// Serialize serializes information the current object
func (m *ClientAssociationTimeDistributionVO) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteInt32Value("fails", m.GetFails())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("from2To4sNum", m.GetFrom2To4sNum())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("from4To6sNum", m.GetFrom4To6sNum())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("from6To8sNum", m.GetFrom6To8sNum())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("from8To10sNum", m.GetFrom8To10sNum())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("lessThan10sPercent", m.GetLessThan10sPercent())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("lessThan2sNum", m.GetLessThan2sNum())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("moreThan10sNum", m.GetMoreThan10sNum())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ClientAssociationTimeDistributionVO) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetFails sets the fails property value. The fails property
func (m *ClientAssociationTimeDistributionVO) SetFails(value *int32)() {
    m.fails = value
}
// SetFrom2To4sNum sets the from2To4sNum property value. The from2To4sNum property
func (m *ClientAssociationTimeDistributionVO) SetFrom2To4sNum(value *int32)() {
    m.from2To4sNum = value
}
// SetFrom4To6sNum sets the from4To6sNum property value. The from4To6sNum property
func (m *ClientAssociationTimeDistributionVO) SetFrom4To6sNum(value *int32)() {
    m.from4To6sNum = value
}
// SetFrom6To8sNum sets the from6To8sNum property value. The from6To8sNum property
func (m *ClientAssociationTimeDistributionVO) SetFrom6To8sNum(value *int32)() {
    m.from6To8sNum = value
}
// SetFrom8To10sNum sets the from8To10sNum property value. The from8To10sNum property
func (m *ClientAssociationTimeDistributionVO) SetFrom8To10sNum(value *int32)() {
    m.from8To10sNum = value
}
// SetLessThan10sPercent sets the lessThan10sPercent property value. The lessThan10sPercent property
func (m *ClientAssociationTimeDistributionVO) SetLessThan10sPercent(value *int32)() {
    m.lessThan10sPercent = value
}
// SetLessThan2sNum sets the lessThan2sNum property value. The lessThan2sNum property
func (m *ClientAssociationTimeDistributionVO) SetLessThan2sNum(value *int32)() {
    m.lessThan2sNum = value
}
// SetMoreThan10sNum sets the moreThan10sNum property value. The moreThan10sNum property
func (m *ClientAssociationTimeDistributionVO) SetMoreThan10sNum(value *int32)() {
    m.moreThan10sNum = value
}
type ClientAssociationTimeDistributionVOable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetFails()(*int32)
    GetFrom2To4sNum()(*int32)
    GetFrom4To6sNum()(*int32)
    GetFrom6To8sNum()(*int32)
    GetFrom8To10sNum()(*int32)
    GetLessThan10sPercent()(*int32)
    GetLessThan2sNum()(*int32)
    GetMoreThan10sNum()(*int32)
    SetFails(value *int32)()
    SetFrom2To4sNum(value *int32)()
    SetFrom4To6sNum(value *int32)()
    SetFrom6To8sNum(value *int32)()
    SetFrom8To10sNum(value *int32)()
    SetLessThan10sPercent(value *int32)()
    SetLessThan2sNum(value *int32)()
    SetMoreThan10sNum(value *int32)()
}
