// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ClientExportOpenApiVO struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Format should be a value as follows: 0: csv; 1: xlsx.
    format *int32
    // Tables should be a list of follows: 0: online; 1: offline; 2: blocked; 3: past-connection, 4: past-portal-auth.
    tables []int32
}
// NewClientExportOpenApiVO instantiates a new ClientExportOpenApiVO and sets the default values.
func NewClientExportOpenApiVO()(*ClientExportOpenApiVO) {
    m := &ClientExportOpenApiVO{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateClientExportOpenApiVOFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateClientExportOpenApiVOFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewClientExportOpenApiVO(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ClientExportOpenApiVO) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ClientExportOpenApiVO) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["format"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFormat(val)
        }
        return nil
    }
    res["tables"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("int32")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]int32, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*int32))
                }
            }
            m.SetTables(res)
        }
        return nil
    }
    return res
}
// GetFormat gets the format property value. Format should be a value as follows: 0: csv; 1: xlsx.
// returns a *int32 when successful
func (m *ClientExportOpenApiVO) GetFormat()(*int32) {
    return m.format
}
// GetTables gets the tables property value. Tables should be a list of follows: 0: online; 1: offline; 2: blocked; 3: past-connection, 4: past-portal-auth.
// returns a []int32 when successful
func (m *ClientExportOpenApiVO) GetTables()([]int32) {
    return m.tables
}
// Serialize serializes information the current object
func (m *ClientExportOpenApiVO) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteInt32Value("format", m.GetFormat())
        if err != nil {
            return err
        }
    }
    if m.GetTables() != nil {
        err := writer.WriteCollectionOfInt32Values("tables", m.GetTables())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ClientExportOpenApiVO) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetFormat sets the format property value. Format should be a value as follows: 0: csv; 1: xlsx.
func (m *ClientExportOpenApiVO) SetFormat(value *int32)() {
    m.format = value
}
// SetTables sets the tables property value. Tables should be a list of follows: 0: online; 1: offline; 2: blocked; 3: past-connection, 4: past-portal-auth.
func (m *ClientExportOpenApiVO) SetTables(value []int32)() {
    m.tables = value
}
type ClientExportOpenApiVOable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetFormat()(*int32)
    GetTables()([]int32)
    SetFormat(value *int32)()
    SetTables(value []int32)()
}
