// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type CustomerListClientNumVO struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The customerId property
    customerId *string
    // The wiredUser property
    wiredUser *int32
    // The wirelessGuest property
    wirelessGuest *int32
    // The wirelessUser property
    wirelessUser *int32
}
// NewCustomerListClientNumVO instantiates a new CustomerListClientNumVO and sets the default values.
func NewCustomerListClientNumVO()(*CustomerListClientNumVO) {
    m := &CustomerListClientNumVO{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateCustomerListClientNumVOFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCustomerListClientNumVOFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewCustomerListClientNumVO(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *CustomerListClientNumVO) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCustomerId gets the customerId property value. The customerId property
// returns a *string when successful
func (m *CustomerListClientNumVO) GetCustomerId()(*string) {
    return m.customerId
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *CustomerListClientNumVO) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["customerId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCustomerId(val)
        }
        return nil
    }
    res["wiredUser"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetWiredUser(val)
        }
        return nil
    }
    res["wirelessGuest"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetWirelessGuest(val)
        }
        return nil
    }
    res["wirelessUser"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetWirelessUser(val)
        }
        return nil
    }
    return res
}
// GetWiredUser gets the wiredUser property value. The wiredUser property
// returns a *int32 when successful
func (m *CustomerListClientNumVO) GetWiredUser()(*int32) {
    return m.wiredUser
}
// GetWirelessGuest gets the wirelessGuest property value. The wirelessGuest property
// returns a *int32 when successful
func (m *CustomerListClientNumVO) GetWirelessGuest()(*int32) {
    return m.wirelessGuest
}
// GetWirelessUser gets the wirelessUser property value. The wirelessUser property
// returns a *int32 when successful
func (m *CustomerListClientNumVO) GetWirelessUser()(*int32) {
    return m.wirelessUser
}
// Serialize serializes information the current object
func (m *CustomerListClientNumVO) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("customerId", m.GetCustomerId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("wiredUser", m.GetWiredUser())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("wirelessGuest", m.GetWirelessGuest())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("wirelessUser", m.GetWirelessUser())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *CustomerListClientNumVO) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCustomerId sets the customerId property value. The customerId property
func (m *CustomerListClientNumVO) SetCustomerId(value *string)() {
    m.customerId = value
}
// SetWiredUser sets the wiredUser property value. The wiredUser property
func (m *CustomerListClientNumVO) SetWiredUser(value *int32)() {
    m.wiredUser = value
}
// SetWirelessGuest sets the wirelessGuest property value. The wirelessGuest property
func (m *CustomerListClientNumVO) SetWirelessGuest(value *int32)() {
    m.wirelessGuest = value
}
// SetWirelessUser sets the wirelessUser property value. The wirelessUser property
func (m *CustomerListClientNumVO) SetWirelessUser(value *int32)() {
    m.wirelessUser = value
}
type CustomerListClientNumVOable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCustomerId()(*string)
    GetWiredUser()(*int32)
    GetWirelessGuest()(*int32)
    GetWirelessUser()(*int32)
    SetCustomerId(value *string)()
    SetWiredUser(value *int32)()
    SetWirelessGuest(value *int32)()
    SetWirelessUser(value *int32)()
}
