// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type DashboardDistributionVO struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The eapDistribution property
    eapDistribution EapDistributionVOable
    // The switchDistribution property
    switchDistribution SwitchDistributionVOable
}
// NewDashboardDistributionVO instantiates a new DashboardDistributionVO and sets the default values.
func NewDashboardDistributionVO()(*DashboardDistributionVO) {
    m := &DashboardDistributionVO{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateDashboardDistributionVOFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDashboardDistributionVOFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewDashboardDistributionVO(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *DashboardDistributionVO) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetEapDistribution gets the eapDistribution property value. The eapDistribution property
// returns a EapDistributionVOable when successful
func (m *DashboardDistributionVO) GetEapDistribution()(EapDistributionVOable) {
    return m.eapDistribution
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *DashboardDistributionVO) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["eapDistribution"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateEapDistributionVOFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEapDistribution(val.(EapDistributionVOable))
        }
        return nil
    }
    res["switchDistribution"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateSwitchDistributionVOFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSwitchDistribution(val.(SwitchDistributionVOable))
        }
        return nil
    }
    return res
}
// GetSwitchDistribution gets the switchDistribution property value. The switchDistribution property
// returns a SwitchDistributionVOable when successful
func (m *DashboardDistributionVO) GetSwitchDistribution()(SwitchDistributionVOable) {
    return m.switchDistribution
}
// Serialize serializes information the current object
func (m *DashboardDistributionVO) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("eapDistribution", m.GetEapDistribution())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("switchDistribution", m.GetSwitchDistribution())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *DashboardDistributionVO) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetEapDistribution sets the eapDistribution property value. The eapDistribution property
func (m *DashboardDistributionVO) SetEapDistribution(value EapDistributionVOable)() {
    m.eapDistribution = value
}
// SetSwitchDistribution sets the switchDistribution property value. The switchDistribution property
func (m *DashboardDistributionVO) SetSwitchDistribution(value SwitchDistributionVOable)() {
    m.switchDistribution = value
}
type DashboardDistributionVOable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetEapDistribution()(EapDistributionVOable)
    GetSwitchDistribution()(SwitchDistributionVOable)
    SetEapDistribution(value EapDistributionVOable)()
    SetSwitchDistribution(value SwitchDistributionVOable)()
}
