// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type DeviceTelephoneNumber struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The list of telephone number.
    bindNumberList []TelephoneNumberWithStatusOpenApiVOable
    // The ID of voip device.
    id *string
    // The mac of voip device.
    mac *string
}
// NewDeviceTelephoneNumber instantiates a new DeviceTelephoneNumber and sets the default values.
func NewDeviceTelephoneNumber()(*DeviceTelephoneNumber) {
    m := &DeviceTelephoneNumber{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateDeviceTelephoneNumberFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDeviceTelephoneNumberFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewDeviceTelephoneNumber(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *DeviceTelephoneNumber) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetBindNumberList gets the bindNumberList property value. The list of telephone number.
// returns a []TelephoneNumberWithStatusOpenApiVOable when successful
func (m *DeviceTelephoneNumber) GetBindNumberList()([]TelephoneNumberWithStatusOpenApiVOable) {
    return m.bindNumberList
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *DeviceTelephoneNumber) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["bindNumberList"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateTelephoneNumberWithStatusOpenApiVOFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]TelephoneNumberWithStatusOpenApiVOable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(TelephoneNumberWithStatusOpenApiVOable)
                }
            }
            m.SetBindNumberList(res)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["mac"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMac(val)
        }
        return nil
    }
    return res
}
// GetId gets the id property value. The ID of voip device.
// returns a *string when successful
func (m *DeviceTelephoneNumber) GetId()(*string) {
    return m.id
}
// GetMac gets the mac property value. The mac of voip device.
// returns a *string when successful
func (m *DeviceTelephoneNumber) GetMac()(*string) {
    return m.mac
}
// Serialize serializes information the current object
func (m *DeviceTelephoneNumber) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetBindNumberList() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetBindNumberList()))
        for i, v := range m.GetBindNumberList() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("bindNumberList", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("mac", m.GetMac())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *DeviceTelephoneNumber) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetBindNumberList sets the bindNumberList property value. The list of telephone number.
func (m *DeviceTelephoneNumber) SetBindNumberList(value []TelephoneNumberWithStatusOpenApiVOable)() {
    m.bindNumberList = value
}
// SetId sets the id property value. The ID of voip device.
func (m *DeviceTelephoneNumber) SetId(value *string)() {
    m.id = value
}
// SetMac sets the mac property value. The mac of voip device.
func (m *DeviceTelephoneNumber) SetMac(value *string)() {
    m.mac = value
}
type DeviceTelephoneNumberable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetBindNumberList()([]TelephoneNumberWithStatusOpenApiVOable)
    GetId()(*string)
    GetMac()(*string)
    SetBindNumberList(value []TelephoneNumberWithStatusOpenApiVOable)()
    SetId(value *string)()
    SetMac(value *string)()
}
