// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type DeviceVO struct {
    // Mark whether the device is activated: When license (specific to cloud base) is false, the status column shows the pre-bound status. When it is true or null, the status column displays as it originally did.
    active *bool
    // Whether the device is added in advanced.
    addedInAdvanced *bool
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Address
    address *string
    // Adopt fail reason should be a value as follows: -1:adopt timeout;-2:user/password error
    adoptFailType *int32
    // Category of license.When activating in bulk for the pro site, the front end can only select the same type for bulk activation.
    category *string
    // Number of clients.
    clientNum *int32
    // Is it an combined gateway?
    combinedGateway *bool
    // Device firmware and controller compatibility type.Compatible should be a value as follows: 0:COMPATIBLE;1:HIGH_MAJOR_VER;2:LOW_MAJOR_VER;3:HIGH_MINOR_VER;4:LOW_MINOR_VER;7:HIGH_COMPONENT_VER;10:DEVICE_NOT_COMPATIBLE;11:HIGH_ADOPT_COMMPONENT;12:DEVICE_CATEGORY_NOT_COMPATIBLE;14:DEVICE_NOT_COMPATIBLE_IN_CLUSTER
    compatible *int32
    // Model complex used in the backend.Ap：model+(country)+modelVersion,  EAP225(EU) v3.0 Ap: specialModel+modelVersion, EAP225-Outdoor-1a20a950b8d950e8 v1.0  Gateway/Switch：model+modelVersion, Osg v3.0
    compoundModel *string
    // Device configuration synchronization status , including: 0: noConfig (No configuration) 1: success (Success) 2: fail (Failure) 3: info (Information) 4: configuring (Configuring) 5: preConfig (Pre-configuration)
    configSyncStatus *int32
    // Cpu utilization
    cpuUtil *int32
    // Customer ID
    customId *string
    // Customer name displayed in MSP mode
    customName *string
    // Device type should be a value as follows:0:advanced,1:pro
    deviceSeriesType *int32
    // Real-time total downstream traffic (bytes).
    download *int64
    // Expire timestamp of license(cloud base exclusive)
    dueTime *int64
    // Milliseconds from the current moment to the expiration time(cloud base exclusive)
    dueTimeLeft *int64
    // Duplex should be a value as follows:0:Auto,1:Half, 2:Full
    duplex *int32
    // Ecsp first version
    ecspFirstVersion *int32
    // End of support time of device(CBC exclusive)
    eos *int64
    // End of service time of device(CBC exclusive)
    eost *int64
    // Whether it is Agile Series Switch
    es *bool
    // Functions that need to be restricted under the current power supply mode.
    featureLimit ApFeatureLimitVOable
    // Version of firmware,for example:2.5.0 Build 20190118 Rel. 64821
    firmwareVersion *string
    // Whether the device is downloading firmware
    fwDownload *bool
    // 1~3: poor; 4~7: fair; 0: no data; 8~10 good.
    healthScore *int32
    // Version of hardware,for example 1.0
    hwVersion *string
    // Whether the device is in white list
    inWhitelist *bool
    // Ip address,such as 192.168.0.105
    ip *string
    // Whether it is LTE Backup
    ippt *bool
    // Ipv6 address List
    ipv6List []string
    // Last active time.
    lastSeen *int64
    // Latest firmware version
    latestVersion *string
    // License status should be a value as follows:0: unActive 1: Unbind 2: Expired 3: active If there is a value and it is not 3, display the Active button. license (specific to cloud base).
    licenseStatus *int32
    // The licenseStatusStr property
    licenseStatusStr *string
    // Remaining unbind count for license on detail Page of device(cloud base exclusive)
    licenseUnbindingLimit *int32
    // Link speed
    linkSpeed *int32
    // Whether locate function is enabled
    locateEnable *bool
    // Device location information on the map; null indicates unplaced.
    location LocationVOable
    // Mac address
    mac *string
    // Memory utilization
    memUtil *int32
    // Model, such as EAP225.
    model *string
    // Model version of device,for example:3.0
    modelVersion *string
    // Default uses the MAC address as the name.
    name *string
    // Whether the device needs upgrade
    needUpgrade *bool
    // Device online upgrade status should be a value as follows: 0:IDLE,1:DOWNLOADING,2:UPGRADING
    onlineUpgradeStatus *int32
    // The packageCaptureStatus property
    packageCaptureStatus *int32
    // AP power mode.The power supply types are as follows: 0: DC power supply 1: 802.3bt power supply 2: 802.3at power supply 3: 802.3af power supply 4: Switch power supply (display restart)
    powerMode *int32
    // Indicating the power supply modes for AP devices across frequency bands, with array indices corresponding to the frequency bands: 0: 2.4G 1: 5G/5G1 2: 5G2 3: 6G. The corresponding values for power supply modes are: 0: Normal operation 1: Power limited 2: Frequency band disabled
    powerModeList []int32
    // When the pre-added devices cannot properly pass through, an error will be returned.
    preConfigErrorCode *int32
    // When retrying the path through, if there is a value, the front end will display a retry button. The types are: 1:Requires password input.2: No password input needed.
    preConfigRetryType *int32
    // Public ip address
    publicIp *string
    // Data source.Resource should be a value as follows: 0:new created;1:from template;2:override
    resource *int32
    // Model complex shown in the front end.Ap：model+(country)+modelVersion,EAP225(EU) v3.0  Gateway/Switch：model+modelVersion,Osg v3.0
    showModel *string
    // "Site of the device"
    site *string
    // Site name
    siteName *string
    // SN code of device
    sn *string
    // Special device model,for example:EAP225-Outdoor-1a20a950b8d950e8
    specialModel *string
    // Status of device,status should be a value as follows: 0:Disconnected;1:Disconnected(Migrating);10:Provisioning;11:Configuring;12:Upgrading;13:Rebooting;14:Connected;15:Connected(Wireless);16:Connected(Migrating);17:Connected(Wireless,Migrating);20:Pending;21:Pending(Wireless);22:Adopting;23:Adopting(Wireless);24:Adopt Failed;25:Adopt Failed(Wireless);26:Managed By Others;27:Managed By Others(Wireless);30:Heartbeat Missed;31:Heartbeat Missed(Wireless);32:Heartbeat Missed(Migrating);33:Heartbeat Missed(Wireless,Migrating);40:Isolated;41:Isolated(Migrating);50:Slice Configuring
    status *int32
    // Category of device status,statusCategory should be a value as follows: 0:Disconnected;1:Connected;2:Pending;3:Heartbeat Missed;4:Isolated
    statusCategory *int32
    // Device subtype, indicating a special device type for wireless routers. This field is not present for ordinary devices, where 1 represents a wireless router.
    subDevType *int32
    // Whether the device firmware support intelligent anomaly detection
    supportAnomaly *bool
    // The supportIppt property
    supportIppt *bool
    // Whether the device supports show running config.
    supportRunningConfig *bool
    // Whether the device can be adopted by the site.
    switchConsistent *bool
    // Device tag name
    tagName *string
    // Device type:ap、gateway、switch、olt
    typeEscaped *string
    // Uplink device mac
    uplinkDeviceMac *string
    // Uplink device mac name
    uplinkDeviceName *string
    // Uplink device port
    uplinkDevicePort *string
    // Real-time total upstream traffic (bytes).
    upload *int64
    // Device uptime
    uptime *string
    // Runtime duration, in seconds (s).
    uptimeLong *int64
    // Software version, such as "2.5.0," extracted from DeviceDO.firmwareVersion - "2.5.0 Build 20190118 Rel. 64821."
    version *string
    // Indicates whether it is a wireless router; it is true only when this device is a wireless router.
    wirelessRouter *bool
}
// NewDeviceVO instantiates a new DeviceVO and sets the default values.
func NewDeviceVO()(*DeviceVO) {
    m := &DeviceVO{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateDeviceVOFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDeviceVOFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewDeviceVO(), nil
}
// GetActive gets the active property value. Mark whether the device is activated: When license (specific to cloud base) is false, the status column shows the pre-bound status. When it is true or null, the status column displays as it originally did.
// returns a *bool when successful
func (m *DeviceVO) GetActive()(*bool) {
    return m.active
}
// GetAddedInAdvanced gets the addedInAdvanced property value. Whether the device is added in advanced.
// returns a *bool when successful
func (m *DeviceVO) GetAddedInAdvanced()(*bool) {
    return m.addedInAdvanced
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *DeviceVO) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAddress gets the address property value. Address
// returns a *string when successful
func (m *DeviceVO) GetAddress()(*string) {
    return m.address
}
// GetAdoptFailType gets the adoptFailType property value. Adopt fail reason should be a value as follows: -1:adopt timeout;-2:user/password error
// returns a *int32 when successful
func (m *DeviceVO) GetAdoptFailType()(*int32) {
    return m.adoptFailType
}
// GetCategory gets the category property value. Category of license.When activating in bulk for the pro site, the front end can only select the same type for bulk activation.
// returns a *string when successful
func (m *DeviceVO) GetCategory()(*string) {
    return m.category
}
// GetClientNum gets the clientNum property value. Number of clients.
// returns a *int32 when successful
func (m *DeviceVO) GetClientNum()(*int32) {
    return m.clientNum
}
// GetCombinedGateway gets the combinedGateway property value. Is it an combined gateway?
// returns a *bool when successful
func (m *DeviceVO) GetCombinedGateway()(*bool) {
    return m.combinedGateway
}
// GetCompatible gets the compatible property value. Device firmware and controller compatibility type.Compatible should be a value as follows: 0:COMPATIBLE;1:HIGH_MAJOR_VER;2:LOW_MAJOR_VER;3:HIGH_MINOR_VER;4:LOW_MINOR_VER;7:HIGH_COMPONENT_VER;10:DEVICE_NOT_COMPATIBLE;11:HIGH_ADOPT_COMMPONENT;12:DEVICE_CATEGORY_NOT_COMPATIBLE;14:DEVICE_NOT_COMPATIBLE_IN_CLUSTER
// returns a *int32 when successful
func (m *DeviceVO) GetCompatible()(*int32) {
    return m.compatible
}
// GetCompoundModel gets the compoundModel property value. Model complex used in the backend.Ap：model+(country)+modelVersion,  EAP225(EU) v3.0 Ap: specialModel+modelVersion, EAP225-Outdoor-1a20a950b8d950e8 v1.0  Gateway/Switch：model+modelVersion, Osg v3.0
// returns a *string when successful
func (m *DeviceVO) GetCompoundModel()(*string) {
    return m.compoundModel
}
// GetConfigSyncStatus gets the configSyncStatus property value. Device configuration synchronization status , including: 0: noConfig (No configuration) 1: success (Success) 2: fail (Failure) 3: info (Information) 4: configuring (Configuring) 5: preConfig (Pre-configuration)
// returns a *int32 when successful
func (m *DeviceVO) GetConfigSyncStatus()(*int32) {
    return m.configSyncStatus
}
// GetCpuUtil gets the cpuUtil property value. Cpu utilization
// returns a *int32 when successful
func (m *DeviceVO) GetCpuUtil()(*int32) {
    return m.cpuUtil
}
// GetCustomId gets the customId property value. Customer ID
// returns a *string when successful
func (m *DeviceVO) GetCustomId()(*string) {
    return m.customId
}
// GetCustomName gets the customName property value. Customer name displayed in MSP mode
// returns a *string when successful
func (m *DeviceVO) GetCustomName()(*string) {
    return m.customName
}
// GetDeviceSeriesType gets the deviceSeriesType property value. Device type should be a value as follows:0:advanced,1:pro
// returns a *int32 when successful
func (m *DeviceVO) GetDeviceSeriesType()(*int32) {
    return m.deviceSeriesType
}
// GetDownload gets the download property value. Real-time total downstream traffic (bytes).
// returns a *int64 when successful
func (m *DeviceVO) GetDownload()(*int64) {
    return m.download
}
// GetDueTime gets the dueTime property value. Expire timestamp of license(cloud base exclusive)
// returns a *int64 when successful
func (m *DeviceVO) GetDueTime()(*int64) {
    return m.dueTime
}
// GetDueTimeLeft gets the dueTimeLeft property value. Milliseconds from the current moment to the expiration time(cloud base exclusive)
// returns a *int64 when successful
func (m *DeviceVO) GetDueTimeLeft()(*int64) {
    return m.dueTimeLeft
}
// GetDuplex gets the duplex property value. Duplex should be a value as follows:0:Auto,1:Half, 2:Full
// returns a *int32 when successful
func (m *DeviceVO) GetDuplex()(*int32) {
    return m.duplex
}
// GetEcspFirstVersion gets the ecspFirstVersion property value. Ecsp first version
// returns a *int32 when successful
func (m *DeviceVO) GetEcspFirstVersion()(*int32) {
    return m.ecspFirstVersion
}
// GetEos gets the eos property value. End of support time of device(CBC exclusive)
// returns a *int64 when successful
func (m *DeviceVO) GetEos()(*int64) {
    return m.eos
}
// GetEost gets the eost property value. End of service time of device(CBC exclusive)
// returns a *int64 when successful
func (m *DeviceVO) GetEost()(*int64) {
    return m.eost
}
// GetEs gets the es property value. Whether it is Agile Series Switch
// returns a *bool when successful
func (m *DeviceVO) GetEs()(*bool) {
    return m.es
}
// GetFeatureLimit gets the featureLimit property value. Functions that need to be restricted under the current power supply mode.
// returns a ApFeatureLimitVOable when successful
func (m *DeviceVO) GetFeatureLimit()(ApFeatureLimitVOable) {
    return m.featureLimit
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *DeviceVO) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["active"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetActive(val)
        }
        return nil
    }
    res["addedInAdvanced"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAddedInAdvanced(val)
        }
        return nil
    }
    res["address"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAddress(val)
        }
        return nil
    }
    res["adoptFailType"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAdoptFailType(val)
        }
        return nil
    }
    res["category"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCategory(val)
        }
        return nil
    }
    res["clientNum"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetClientNum(val)
        }
        return nil
    }
    res["combinedGateway"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCombinedGateway(val)
        }
        return nil
    }
    res["compatible"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCompatible(val)
        }
        return nil
    }
    res["compoundModel"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCompoundModel(val)
        }
        return nil
    }
    res["configSyncStatus"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetConfigSyncStatus(val)
        }
        return nil
    }
    res["cpuUtil"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCpuUtil(val)
        }
        return nil
    }
    res["customId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCustomId(val)
        }
        return nil
    }
    res["customName"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCustomName(val)
        }
        return nil
    }
    res["deviceSeriesType"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDeviceSeriesType(val)
        }
        return nil
    }
    res["download"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDownload(val)
        }
        return nil
    }
    res["dueTime"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDueTime(val)
        }
        return nil
    }
    res["dueTimeLeft"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDueTimeLeft(val)
        }
        return nil
    }
    res["duplex"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDuplex(val)
        }
        return nil
    }
    res["ecspFirstVersion"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEcspFirstVersion(val)
        }
        return nil
    }
    res["eos"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEos(val)
        }
        return nil
    }
    res["eost"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEost(val)
        }
        return nil
    }
    res["es"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEs(val)
        }
        return nil
    }
    res["featureLimit"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateApFeatureLimitVOFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFeatureLimit(val.(ApFeatureLimitVOable))
        }
        return nil
    }
    res["firmwareVersion"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFirmwareVersion(val)
        }
        return nil
    }
    res["fwDownload"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFwDownload(val)
        }
        return nil
    }
    res["healthScore"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetHealthScore(val)
        }
        return nil
    }
    res["hwVersion"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetHwVersion(val)
        }
        return nil
    }
    res["inWhitelist"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetInWhitelist(val)
        }
        return nil
    }
    res["ip"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIp(val)
        }
        return nil
    }
    res["ippt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIppt(val)
        }
        return nil
    }
    res["ipv6List"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("string")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]string, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*string))
                }
            }
            m.SetIpv6List(res)
        }
        return nil
    }
    res["lastSeen"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLastSeen(val)
        }
        return nil
    }
    res["latestVersion"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLatestVersion(val)
        }
        return nil
    }
    res["licenseStatus"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLicenseStatus(val)
        }
        return nil
    }
    res["licenseStatusStr"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLicenseStatusStr(val)
        }
        return nil
    }
    res["licenseUnbindingLimit"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLicenseUnbindingLimit(val)
        }
        return nil
    }
    res["linkSpeed"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLinkSpeed(val)
        }
        return nil
    }
    res["locateEnable"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLocateEnable(val)
        }
        return nil
    }
    res["location"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateLocationVOFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLocation(val.(LocationVOable))
        }
        return nil
    }
    res["mac"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMac(val)
        }
        return nil
    }
    res["memUtil"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMemUtil(val)
        }
        return nil
    }
    res["model"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetModel(val)
        }
        return nil
    }
    res["modelVersion"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetModelVersion(val)
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["needUpgrade"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNeedUpgrade(val)
        }
        return nil
    }
    res["onlineUpgradeStatus"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOnlineUpgradeStatus(val)
        }
        return nil
    }
    res["packageCaptureStatus"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPackageCaptureStatus(val)
        }
        return nil
    }
    res["powerMode"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPowerMode(val)
        }
        return nil
    }
    res["powerModeList"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("int32")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]int32, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*int32))
                }
            }
            m.SetPowerModeList(res)
        }
        return nil
    }
    res["preConfigErrorCode"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPreConfigErrorCode(val)
        }
        return nil
    }
    res["preConfigRetryType"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPreConfigRetryType(val)
        }
        return nil
    }
    res["publicIp"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPublicIp(val)
        }
        return nil
    }
    res["resource"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetResource(val)
        }
        return nil
    }
    res["showModel"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetShowModel(val)
        }
        return nil
    }
    res["site"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSite(val)
        }
        return nil
    }
    res["siteName"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSiteName(val)
        }
        return nil
    }
    res["sn"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSn(val)
        }
        return nil
    }
    res["specialModel"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSpecialModel(val)
        }
        return nil
    }
    res["status"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStatus(val)
        }
        return nil
    }
    res["statusCategory"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStatusCategory(val)
        }
        return nil
    }
    res["subDevType"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSubDevType(val)
        }
        return nil
    }
    res["supportAnomaly"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSupportAnomaly(val)
        }
        return nil
    }
    res["supportIppt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSupportIppt(val)
        }
        return nil
    }
    res["supportRunningConfig"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSupportRunningConfig(val)
        }
        return nil
    }
    res["switchConsistent"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSwitchConsistent(val)
        }
        return nil
    }
    res["tagName"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTagName(val)
        }
        return nil
    }
    res["type"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTypeEscaped(val)
        }
        return nil
    }
    res["uplinkDeviceMac"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUplinkDeviceMac(val)
        }
        return nil
    }
    res["uplinkDeviceName"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUplinkDeviceName(val)
        }
        return nil
    }
    res["uplinkDevicePort"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUplinkDevicePort(val)
        }
        return nil
    }
    res["upload"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUpload(val)
        }
        return nil
    }
    res["uptime"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUptime(val)
        }
        return nil
    }
    res["uptimeLong"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUptimeLong(val)
        }
        return nil
    }
    res["version"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetVersion(val)
        }
        return nil
    }
    res["wirelessRouter"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetWirelessRouter(val)
        }
        return nil
    }
    return res
}
// GetFirmwareVersion gets the firmwareVersion property value. Version of firmware,for example:2.5.0 Build 20190118 Rel. 64821
// returns a *string when successful
func (m *DeviceVO) GetFirmwareVersion()(*string) {
    return m.firmwareVersion
}
// GetFwDownload gets the fwDownload property value. Whether the device is downloading firmware
// returns a *bool when successful
func (m *DeviceVO) GetFwDownload()(*bool) {
    return m.fwDownload
}
// GetHealthScore gets the healthScore property value. 1~3: poor; 4~7: fair; 0: no data; 8~10 good.
// returns a *int32 when successful
func (m *DeviceVO) GetHealthScore()(*int32) {
    return m.healthScore
}
// GetHwVersion gets the hwVersion property value. Version of hardware,for example 1.0
// returns a *string when successful
func (m *DeviceVO) GetHwVersion()(*string) {
    return m.hwVersion
}
// GetInWhitelist gets the inWhitelist property value. Whether the device is in white list
// returns a *bool when successful
func (m *DeviceVO) GetInWhitelist()(*bool) {
    return m.inWhitelist
}
// GetIp gets the ip property value. Ip address,such as 192.168.0.105
// returns a *string when successful
func (m *DeviceVO) GetIp()(*string) {
    return m.ip
}
// GetIppt gets the ippt property value. Whether it is LTE Backup
// returns a *bool when successful
func (m *DeviceVO) GetIppt()(*bool) {
    return m.ippt
}
// GetIpv6List gets the ipv6List property value. Ipv6 address List
// returns a []string when successful
func (m *DeviceVO) GetIpv6List()([]string) {
    return m.ipv6List
}
// GetLastSeen gets the lastSeen property value. Last active time.
// returns a *int64 when successful
func (m *DeviceVO) GetLastSeen()(*int64) {
    return m.lastSeen
}
// GetLatestVersion gets the latestVersion property value. Latest firmware version
// returns a *string when successful
func (m *DeviceVO) GetLatestVersion()(*string) {
    return m.latestVersion
}
// GetLicenseStatus gets the licenseStatus property value. License status should be a value as follows:0: unActive 1: Unbind 2: Expired 3: active If there is a value and it is not 3, display the Active button. license (specific to cloud base).
// returns a *int32 when successful
func (m *DeviceVO) GetLicenseStatus()(*int32) {
    return m.licenseStatus
}
// GetLicenseStatusStr gets the licenseStatusStr property value. The licenseStatusStr property
// returns a *string when successful
func (m *DeviceVO) GetLicenseStatusStr()(*string) {
    return m.licenseStatusStr
}
// GetLicenseUnbindingLimit gets the licenseUnbindingLimit property value. Remaining unbind count for license on detail Page of device(cloud base exclusive)
// returns a *int32 when successful
func (m *DeviceVO) GetLicenseUnbindingLimit()(*int32) {
    return m.licenseUnbindingLimit
}
// GetLinkSpeed gets the linkSpeed property value. Link speed
// returns a *int32 when successful
func (m *DeviceVO) GetLinkSpeed()(*int32) {
    return m.linkSpeed
}
// GetLocateEnable gets the locateEnable property value. Whether locate function is enabled
// returns a *bool when successful
func (m *DeviceVO) GetLocateEnable()(*bool) {
    return m.locateEnable
}
// GetLocation gets the location property value. Device location information on the map; null indicates unplaced.
// returns a LocationVOable when successful
func (m *DeviceVO) GetLocation()(LocationVOable) {
    return m.location
}
// GetMac gets the mac property value. Mac address
// returns a *string when successful
func (m *DeviceVO) GetMac()(*string) {
    return m.mac
}
// GetMemUtil gets the memUtil property value. Memory utilization
// returns a *int32 when successful
func (m *DeviceVO) GetMemUtil()(*int32) {
    return m.memUtil
}
// GetModel gets the model property value. Model, such as EAP225.
// returns a *string when successful
func (m *DeviceVO) GetModel()(*string) {
    return m.model
}
// GetModelVersion gets the modelVersion property value. Model version of device,for example:3.0
// returns a *string when successful
func (m *DeviceVO) GetModelVersion()(*string) {
    return m.modelVersion
}
// GetName gets the name property value. Default uses the MAC address as the name.
// returns a *string when successful
func (m *DeviceVO) GetName()(*string) {
    return m.name
}
// GetNeedUpgrade gets the needUpgrade property value. Whether the device needs upgrade
// returns a *bool when successful
func (m *DeviceVO) GetNeedUpgrade()(*bool) {
    return m.needUpgrade
}
// GetOnlineUpgradeStatus gets the onlineUpgradeStatus property value. Device online upgrade status should be a value as follows: 0:IDLE,1:DOWNLOADING,2:UPGRADING
// returns a *int32 when successful
func (m *DeviceVO) GetOnlineUpgradeStatus()(*int32) {
    return m.onlineUpgradeStatus
}
// GetPackageCaptureStatus gets the packageCaptureStatus property value. The packageCaptureStatus property
// returns a *int32 when successful
func (m *DeviceVO) GetPackageCaptureStatus()(*int32) {
    return m.packageCaptureStatus
}
// GetPowerMode gets the powerMode property value. AP power mode.The power supply types are as follows: 0: DC power supply 1: 802.3bt power supply 2: 802.3at power supply 3: 802.3af power supply 4: Switch power supply (display restart)
// returns a *int32 when successful
func (m *DeviceVO) GetPowerMode()(*int32) {
    return m.powerMode
}
// GetPowerModeList gets the powerModeList property value. Indicating the power supply modes for AP devices across frequency bands, with array indices corresponding to the frequency bands: 0: 2.4G 1: 5G/5G1 2: 5G2 3: 6G. The corresponding values for power supply modes are: 0: Normal operation 1: Power limited 2: Frequency band disabled
// returns a []int32 when successful
func (m *DeviceVO) GetPowerModeList()([]int32) {
    return m.powerModeList
}
// GetPreConfigErrorCode gets the preConfigErrorCode property value. When the pre-added devices cannot properly pass through, an error will be returned.
// returns a *int32 when successful
func (m *DeviceVO) GetPreConfigErrorCode()(*int32) {
    return m.preConfigErrorCode
}
// GetPreConfigRetryType gets the preConfigRetryType property value. When retrying the path through, if there is a value, the front end will display a retry button. The types are: 1:Requires password input.2: No password input needed.
// returns a *int32 when successful
func (m *DeviceVO) GetPreConfigRetryType()(*int32) {
    return m.preConfigRetryType
}
// GetPublicIp gets the publicIp property value. Public ip address
// returns a *string when successful
func (m *DeviceVO) GetPublicIp()(*string) {
    return m.publicIp
}
// GetResource gets the resource property value. Data source.Resource should be a value as follows: 0:new created;1:from template;2:override
// returns a *int32 when successful
func (m *DeviceVO) GetResource()(*int32) {
    return m.resource
}
// GetShowModel gets the showModel property value. Model complex shown in the front end.Ap：model+(country)+modelVersion,EAP225(EU) v3.0  Gateway/Switch：model+modelVersion,Osg v3.0
// returns a *string when successful
func (m *DeviceVO) GetShowModel()(*string) {
    return m.showModel
}
// GetSite gets the site property value. "Site of the device"
// returns a *string when successful
func (m *DeviceVO) GetSite()(*string) {
    return m.site
}
// GetSiteName gets the siteName property value. Site name
// returns a *string when successful
func (m *DeviceVO) GetSiteName()(*string) {
    return m.siteName
}
// GetSn gets the sn property value. SN code of device
// returns a *string when successful
func (m *DeviceVO) GetSn()(*string) {
    return m.sn
}
// GetSpecialModel gets the specialModel property value. Special device model,for example:EAP225-Outdoor-1a20a950b8d950e8
// returns a *string when successful
func (m *DeviceVO) GetSpecialModel()(*string) {
    return m.specialModel
}
// GetStatus gets the status property value. Status of device,status should be a value as follows: 0:Disconnected;1:Disconnected(Migrating);10:Provisioning;11:Configuring;12:Upgrading;13:Rebooting;14:Connected;15:Connected(Wireless);16:Connected(Migrating);17:Connected(Wireless,Migrating);20:Pending;21:Pending(Wireless);22:Adopting;23:Adopting(Wireless);24:Adopt Failed;25:Adopt Failed(Wireless);26:Managed By Others;27:Managed By Others(Wireless);30:Heartbeat Missed;31:Heartbeat Missed(Wireless);32:Heartbeat Missed(Migrating);33:Heartbeat Missed(Wireless,Migrating);40:Isolated;41:Isolated(Migrating);50:Slice Configuring
// returns a *int32 when successful
func (m *DeviceVO) GetStatus()(*int32) {
    return m.status
}
// GetStatusCategory gets the statusCategory property value. Category of device status,statusCategory should be a value as follows: 0:Disconnected;1:Connected;2:Pending;3:Heartbeat Missed;4:Isolated
// returns a *int32 when successful
func (m *DeviceVO) GetStatusCategory()(*int32) {
    return m.statusCategory
}
// GetSubDevType gets the subDevType property value. Device subtype, indicating a special device type for wireless routers. This field is not present for ordinary devices, where 1 represents a wireless router.
// returns a *int32 when successful
func (m *DeviceVO) GetSubDevType()(*int32) {
    return m.subDevType
}
// GetSupportAnomaly gets the supportAnomaly property value. Whether the device firmware support intelligent anomaly detection
// returns a *bool when successful
func (m *DeviceVO) GetSupportAnomaly()(*bool) {
    return m.supportAnomaly
}
// GetSupportIppt gets the supportIppt property value. The supportIppt property
// returns a *bool when successful
func (m *DeviceVO) GetSupportIppt()(*bool) {
    return m.supportIppt
}
// GetSupportRunningConfig gets the supportRunningConfig property value. Whether the device supports show running config.
// returns a *bool when successful
func (m *DeviceVO) GetSupportRunningConfig()(*bool) {
    return m.supportRunningConfig
}
// GetSwitchConsistent gets the switchConsistent property value. Whether the device can be adopted by the site.
// returns a *bool when successful
func (m *DeviceVO) GetSwitchConsistent()(*bool) {
    return m.switchConsistent
}
// GetTagName gets the tagName property value. Device tag name
// returns a *string when successful
func (m *DeviceVO) GetTagName()(*string) {
    return m.tagName
}
// GetTypeEscaped gets the type property value. Device type:ap、gateway、switch、olt
// returns a *string when successful
func (m *DeviceVO) GetTypeEscaped()(*string) {
    return m.typeEscaped
}
// GetUplinkDeviceMac gets the uplinkDeviceMac property value. Uplink device mac
// returns a *string when successful
func (m *DeviceVO) GetUplinkDeviceMac()(*string) {
    return m.uplinkDeviceMac
}
// GetUplinkDeviceName gets the uplinkDeviceName property value. Uplink device mac name
// returns a *string when successful
func (m *DeviceVO) GetUplinkDeviceName()(*string) {
    return m.uplinkDeviceName
}
// GetUplinkDevicePort gets the uplinkDevicePort property value. Uplink device port
// returns a *string when successful
func (m *DeviceVO) GetUplinkDevicePort()(*string) {
    return m.uplinkDevicePort
}
// GetUpload gets the upload property value. Real-time total upstream traffic (bytes).
// returns a *int64 when successful
func (m *DeviceVO) GetUpload()(*int64) {
    return m.upload
}
// GetUptime gets the uptime property value. Device uptime
// returns a *string when successful
func (m *DeviceVO) GetUptime()(*string) {
    return m.uptime
}
// GetUptimeLong gets the uptimeLong property value. Runtime duration, in seconds (s).
// returns a *int64 when successful
func (m *DeviceVO) GetUptimeLong()(*int64) {
    return m.uptimeLong
}
// GetVersion gets the version property value. Software version, such as "2.5.0," extracted from DeviceDO.firmwareVersion - "2.5.0 Build 20190118 Rel. 64821."
// returns a *string when successful
func (m *DeviceVO) GetVersion()(*string) {
    return m.version
}
// GetWirelessRouter gets the wirelessRouter property value. Indicates whether it is a wireless router; it is true only when this device is a wireless router.
// returns a *bool when successful
func (m *DeviceVO) GetWirelessRouter()(*bool) {
    return m.wirelessRouter
}
// Serialize serializes information the current object
func (m *DeviceVO) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteBoolValue("active", m.GetActive())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("addedInAdvanced", m.GetAddedInAdvanced())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("address", m.GetAddress())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("adoptFailType", m.GetAdoptFailType())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("category", m.GetCategory())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("clientNum", m.GetClientNum())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("combinedGateway", m.GetCombinedGateway())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("compatible", m.GetCompatible())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("compoundModel", m.GetCompoundModel())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("configSyncStatus", m.GetConfigSyncStatus())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("cpuUtil", m.GetCpuUtil())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("customId", m.GetCustomId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("customName", m.GetCustomName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("deviceSeriesType", m.GetDeviceSeriesType())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("download", m.GetDownload())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("dueTime", m.GetDueTime())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("dueTimeLeft", m.GetDueTimeLeft())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("duplex", m.GetDuplex())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("ecspFirstVersion", m.GetEcspFirstVersion())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("eos", m.GetEos())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("eost", m.GetEost())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("es", m.GetEs())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("featureLimit", m.GetFeatureLimit())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("firmwareVersion", m.GetFirmwareVersion())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("fwDownload", m.GetFwDownload())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("healthScore", m.GetHealthScore())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("hwVersion", m.GetHwVersion())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("inWhitelist", m.GetInWhitelist())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("ip", m.GetIp())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("ippt", m.GetIppt())
        if err != nil {
            return err
        }
    }
    if m.GetIpv6List() != nil {
        err := writer.WriteCollectionOfStringValues("ipv6List", m.GetIpv6List())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("lastSeen", m.GetLastSeen())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("latestVersion", m.GetLatestVersion())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("licenseStatus", m.GetLicenseStatus())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("licenseStatusStr", m.GetLicenseStatusStr())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("licenseUnbindingLimit", m.GetLicenseUnbindingLimit())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("linkSpeed", m.GetLinkSpeed())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("locateEnable", m.GetLocateEnable())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("location", m.GetLocation())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("mac", m.GetMac())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("memUtil", m.GetMemUtil())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("model", m.GetModel())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("modelVersion", m.GetModelVersion())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("needUpgrade", m.GetNeedUpgrade())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("onlineUpgradeStatus", m.GetOnlineUpgradeStatus())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("packageCaptureStatus", m.GetPackageCaptureStatus())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("powerMode", m.GetPowerMode())
        if err != nil {
            return err
        }
    }
    if m.GetPowerModeList() != nil {
        err := writer.WriteCollectionOfInt32Values("powerModeList", m.GetPowerModeList())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("preConfigErrorCode", m.GetPreConfigErrorCode())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("preConfigRetryType", m.GetPreConfigRetryType())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("publicIp", m.GetPublicIp())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("resource", m.GetResource())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("showModel", m.GetShowModel())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("site", m.GetSite())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("siteName", m.GetSiteName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("sn", m.GetSn())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("specialModel", m.GetSpecialModel())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("status", m.GetStatus())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("statusCategory", m.GetStatusCategory())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("subDevType", m.GetSubDevType())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("supportAnomaly", m.GetSupportAnomaly())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("supportIppt", m.GetSupportIppt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("supportRunningConfig", m.GetSupportRunningConfig())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("switchConsistent", m.GetSwitchConsistent())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("tagName", m.GetTagName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("type", m.GetTypeEscaped())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("uplinkDeviceMac", m.GetUplinkDeviceMac())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("uplinkDeviceName", m.GetUplinkDeviceName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("uplinkDevicePort", m.GetUplinkDevicePort())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("upload", m.GetUpload())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("uptime", m.GetUptime())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("uptimeLong", m.GetUptimeLong())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("version", m.GetVersion())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("wirelessRouter", m.GetWirelessRouter())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetActive sets the active property value. Mark whether the device is activated: When license (specific to cloud base) is false, the status column shows the pre-bound status. When it is true or null, the status column displays as it originally did.
func (m *DeviceVO) SetActive(value *bool)() {
    m.active = value
}
// SetAddedInAdvanced sets the addedInAdvanced property value. Whether the device is added in advanced.
func (m *DeviceVO) SetAddedInAdvanced(value *bool)() {
    m.addedInAdvanced = value
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *DeviceVO) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAddress sets the address property value. Address
func (m *DeviceVO) SetAddress(value *string)() {
    m.address = value
}
// SetAdoptFailType sets the adoptFailType property value. Adopt fail reason should be a value as follows: -1:adopt timeout;-2:user/password error
func (m *DeviceVO) SetAdoptFailType(value *int32)() {
    m.adoptFailType = value
}
// SetCategory sets the category property value. Category of license.When activating in bulk for the pro site, the front end can only select the same type for bulk activation.
func (m *DeviceVO) SetCategory(value *string)() {
    m.category = value
}
// SetClientNum sets the clientNum property value. Number of clients.
func (m *DeviceVO) SetClientNum(value *int32)() {
    m.clientNum = value
}
// SetCombinedGateway sets the combinedGateway property value. Is it an combined gateway?
func (m *DeviceVO) SetCombinedGateway(value *bool)() {
    m.combinedGateway = value
}
// SetCompatible sets the compatible property value. Device firmware and controller compatibility type.Compatible should be a value as follows: 0:COMPATIBLE;1:HIGH_MAJOR_VER;2:LOW_MAJOR_VER;3:HIGH_MINOR_VER;4:LOW_MINOR_VER;7:HIGH_COMPONENT_VER;10:DEVICE_NOT_COMPATIBLE;11:HIGH_ADOPT_COMMPONENT;12:DEVICE_CATEGORY_NOT_COMPATIBLE;14:DEVICE_NOT_COMPATIBLE_IN_CLUSTER
func (m *DeviceVO) SetCompatible(value *int32)() {
    m.compatible = value
}
// SetCompoundModel sets the compoundModel property value. Model complex used in the backend.Ap：model+(country)+modelVersion,  EAP225(EU) v3.0 Ap: specialModel+modelVersion, EAP225-Outdoor-1a20a950b8d950e8 v1.0  Gateway/Switch：model+modelVersion, Osg v3.0
func (m *DeviceVO) SetCompoundModel(value *string)() {
    m.compoundModel = value
}
// SetConfigSyncStatus sets the configSyncStatus property value. Device configuration synchronization status , including: 0: noConfig (No configuration) 1: success (Success) 2: fail (Failure) 3: info (Information) 4: configuring (Configuring) 5: preConfig (Pre-configuration)
func (m *DeviceVO) SetConfigSyncStatus(value *int32)() {
    m.configSyncStatus = value
}
// SetCpuUtil sets the cpuUtil property value. Cpu utilization
func (m *DeviceVO) SetCpuUtil(value *int32)() {
    m.cpuUtil = value
}
// SetCustomId sets the customId property value. Customer ID
func (m *DeviceVO) SetCustomId(value *string)() {
    m.customId = value
}
// SetCustomName sets the customName property value. Customer name displayed in MSP mode
func (m *DeviceVO) SetCustomName(value *string)() {
    m.customName = value
}
// SetDeviceSeriesType sets the deviceSeriesType property value. Device type should be a value as follows:0:advanced,1:pro
func (m *DeviceVO) SetDeviceSeriesType(value *int32)() {
    m.deviceSeriesType = value
}
// SetDownload sets the download property value. Real-time total downstream traffic (bytes).
func (m *DeviceVO) SetDownload(value *int64)() {
    m.download = value
}
// SetDueTime sets the dueTime property value. Expire timestamp of license(cloud base exclusive)
func (m *DeviceVO) SetDueTime(value *int64)() {
    m.dueTime = value
}
// SetDueTimeLeft sets the dueTimeLeft property value. Milliseconds from the current moment to the expiration time(cloud base exclusive)
func (m *DeviceVO) SetDueTimeLeft(value *int64)() {
    m.dueTimeLeft = value
}
// SetDuplex sets the duplex property value. Duplex should be a value as follows:0:Auto,1:Half, 2:Full
func (m *DeviceVO) SetDuplex(value *int32)() {
    m.duplex = value
}
// SetEcspFirstVersion sets the ecspFirstVersion property value. Ecsp first version
func (m *DeviceVO) SetEcspFirstVersion(value *int32)() {
    m.ecspFirstVersion = value
}
// SetEos sets the eos property value. End of support time of device(CBC exclusive)
func (m *DeviceVO) SetEos(value *int64)() {
    m.eos = value
}
// SetEost sets the eost property value. End of service time of device(CBC exclusive)
func (m *DeviceVO) SetEost(value *int64)() {
    m.eost = value
}
// SetEs sets the es property value. Whether it is Agile Series Switch
func (m *DeviceVO) SetEs(value *bool)() {
    m.es = value
}
// SetFeatureLimit sets the featureLimit property value. Functions that need to be restricted under the current power supply mode.
func (m *DeviceVO) SetFeatureLimit(value ApFeatureLimitVOable)() {
    m.featureLimit = value
}
// SetFirmwareVersion sets the firmwareVersion property value. Version of firmware,for example:2.5.0 Build 20190118 Rel. 64821
func (m *DeviceVO) SetFirmwareVersion(value *string)() {
    m.firmwareVersion = value
}
// SetFwDownload sets the fwDownload property value. Whether the device is downloading firmware
func (m *DeviceVO) SetFwDownload(value *bool)() {
    m.fwDownload = value
}
// SetHealthScore sets the healthScore property value. 1~3: poor; 4~7: fair; 0: no data; 8~10 good.
func (m *DeviceVO) SetHealthScore(value *int32)() {
    m.healthScore = value
}
// SetHwVersion sets the hwVersion property value. Version of hardware,for example 1.0
func (m *DeviceVO) SetHwVersion(value *string)() {
    m.hwVersion = value
}
// SetInWhitelist sets the inWhitelist property value. Whether the device is in white list
func (m *DeviceVO) SetInWhitelist(value *bool)() {
    m.inWhitelist = value
}
// SetIp sets the ip property value. Ip address,such as 192.168.0.105
func (m *DeviceVO) SetIp(value *string)() {
    m.ip = value
}
// SetIppt sets the ippt property value. Whether it is LTE Backup
func (m *DeviceVO) SetIppt(value *bool)() {
    m.ippt = value
}
// SetIpv6List sets the ipv6List property value. Ipv6 address List
func (m *DeviceVO) SetIpv6List(value []string)() {
    m.ipv6List = value
}
// SetLastSeen sets the lastSeen property value. Last active time.
func (m *DeviceVO) SetLastSeen(value *int64)() {
    m.lastSeen = value
}
// SetLatestVersion sets the latestVersion property value. Latest firmware version
func (m *DeviceVO) SetLatestVersion(value *string)() {
    m.latestVersion = value
}
// SetLicenseStatus sets the licenseStatus property value. License status should be a value as follows:0: unActive 1: Unbind 2: Expired 3: active If there is a value and it is not 3, display the Active button. license (specific to cloud base).
func (m *DeviceVO) SetLicenseStatus(value *int32)() {
    m.licenseStatus = value
}
// SetLicenseStatusStr sets the licenseStatusStr property value. The licenseStatusStr property
func (m *DeviceVO) SetLicenseStatusStr(value *string)() {
    m.licenseStatusStr = value
}
// SetLicenseUnbindingLimit sets the licenseUnbindingLimit property value. Remaining unbind count for license on detail Page of device(cloud base exclusive)
func (m *DeviceVO) SetLicenseUnbindingLimit(value *int32)() {
    m.licenseUnbindingLimit = value
}
// SetLinkSpeed sets the linkSpeed property value. Link speed
func (m *DeviceVO) SetLinkSpeed(value *int32)() {
    m.linkSpeed = value
}
// SetLocateEnable sets the locateEnable property value. Whether locate function is enabled
func (m *DeviceVO) SetLocateEnable(value *bool)() {
    m.locateEnable = value
}
// SetLocation sets the location property value. Device location information on the map; null indicates unplaced.
func (m *DeviceVO) SetLocation(value LocationVOable)() {
    m.location = value
}
// SetMac sets the mac property value. Mac address
func (m *DeviceVO) SetMac(value *string)() {
    m.mac = value
}
// SetMemUtil sets the memUtil property value. Memory utilization
func (m *DeviceVO) SetMemUtil(value *int32)() {
    m.memUtil = value
}
// SetModel sets the model property value. Model, such as EAP225.
func (m *DeviceVO) SetModel(value *string)() {
    m.model = value
}
// SetModelVersion sets the modelVersion property value. Model version of device,for example:3.0
func (m *DeviceVO) SetModelVersion(value *string)() {
    m.modelVersion = value
}
// SetName sets the name property value. Default uses the MAC address as the name.
func (m *DeviceVO) SetName(value *string)() {
    m.name = value
}
// SetNeedUpgrade sets the needUpgrade property value. Whether the device needs upgrade
func (m *DeviceVO) SetNeedUpgrade(value *bool)() {
    m.needUpgrade = value
}
// SetOnlineUpgradeStatus sets the onlineUpgradeStatus property value. Device online upgrade status should be a value as follows: 0:IDLE,1:DOWNLOADING,2:UPGRADING
func (m *DeviceVO) SetOnlineUpgradeStatus(value *int32)() {
    m.onlineUpgradeStatus = value
}
// SetPackageCaptureStatus sets the packageCaptureStatus property value. The packageCaptureStatus property
func (m *DeviceVO) SetPackageCaptureStatus(value *int32)() {
    m.packageCaptureStatus = value
}
// SetPowerMode sets the powerMode property value. AP power mode.The power supply types are as follows: 0: DC power supply 1: 802.3bt power supply 2: 802.3at power supply 3: 802.3af power supply 4: Switch power supply (display restart)
func (m *DeviceVO) SetPowerMode(value *int32)() {
    m.powerMode = value
}
// SetPowerModeList sets the powerModeList property value. Indicating the power supply modes for AP devices across frequency bands, with array indices corresponding to the frequency bands: 0: 2.4G 1: 5G/5G1 2: 5G2 3: 6G. The corresponding values for power supply modes are: 0: Normal operation 1: Power limited 2: Frequency band disabled
func (m *DeviceVO) SetPowerModeList(value []int32)() {
    m.powerModeList = value
}
// SetPreConfigErrorCode sets the preConfigErrorCode property value. When the pre-added devices cannot properly pass through, an error will be returned.
func (m *DeviceVO) SetPreConfigErrorCode(value *int32)() {
    m.preConfigErrorCode = value
}
// SetPreConfigRetryType sets the preConfigRetryType property value. When retrying the path through, if there is a value, the front end will display a retry button. The types are: 1:Requires password input.2: No password input needed.
func (m *DeviceVO) SetPreConfigRetryType(value *int32)() {
    m.preConfigRetryType = value
}
// SetPublicIp sets the publicIp property value. Public ip address
func (m *DeviceVO) SetPublicIp(value *string)() {
    m.publicIp = value
}
// SetResource sets the resource property value. Data source.Resource should be a value as follows: 0:new created;1:from template;2:override
func (m *DeviceVO) SetResource(value *int32)() {
    m.resource = value
}
// SetShowModel sets the showModel property value. Model complex shown in the front end.Ap：model+(country)+modelVersion,EAP225(EU) v3.0  Gateway/Switch：model+modelVersion,Osg v3.0
func (m *DeviceVO) SetShowModel(value *string)() {
    m.showModel = value
}
// SetSite sets the site property value. "Site of the device"
func (m *DeviceVO) SetSite(value *string)() {
    m.site = value
}
// SetSiteName sets the siteName property value. Site name
func (m *DeviceVO) SetSiteName(value *string)() {
    m.siteName = value
}
// SetSn sets the sn property value. SN code of device
func (m *DeviceVO) SetSn(value *string)() {
    m.sn = value
}
// SetSpecialModel sets the specialModel property value. Special device model,for example:EAP225-Outdoor-1a20a950b8d950e8
func (m *DeviceVO) SetSpecialModel(value *string)() {
    m.specialModel = value
}
// SetStatus sets the status property value. Status of device,status should be a value as follows: 0:Disconnected;1:Disconnected(Migrating);10:Provisioning;11:Configuring;12:Upgrading;13:Rebooting;14:Connected;15:Connected(Wireless);16:Connected(Migrating);17:Connected(Wireless,Migrating);20:Pending;21:Pending(Wireless);22:Adopting;23:Adopting(Wireless);24:Adopt Failed;25:Adopt Failed(Wireless);26:Managed By Others;27:Managed By Others(Wireless);30:Heartbeat Missed;31:Heartbeat Missed(Wireless);32:Heartbeat Missed(Migrating);33:Heartbeat Missed(Wireless,Migrating);40:Isolated;41:Isolated(Migrating);50:Slice Configuring
func (m *DeviceVO) SetStatus(value *int32)() {
    m.status = value
}
// SetStatusCategory sets the statusCategory property value. Category of device status,statusCategory should be a value as follows: 0:Disconnected;1:Connected;2:Pending;3:Heartbeat Missed;4:Isolated
func (m *DeviceVO) SetStatusCategory(value *int32)() {
    m.statusCategory = value
}
// SetSubDevType sets the subDevType property value. Device subtype, indicating a special device type for wireless routers. This field is not present for ordinary devices, where 1 represents a wireless router.
func (m *DeviceVO) SetSubDevType(value *int32)() {
    m.subDevType = value
}
// SetSupportAnomaly sets the supportAnomaly property value. Whether the device firmware support intelligent anomaly detection
func (m *DeviceVO) SetSupportAnomaly(value *bool)() {
    m.supportAnomaly = value
}
// SetSupportIppt sets the supportIppt property value. The supportIppt property
func (m *DeviceVO) SetSupportIppt(value *bool)() {
    m.supportIppt = value
}
// SetSupportRunningConfig sets the supportRunningConfig property value. Whether the device supports show running config.
func (m *DeviceVO) SetSupportRunningConfig(value *bool)() {
    m.supportRunningConfig = value
}
// SetSwitchConsistent sets the switchConsistent property value. Whether the device can be adopted by the site.
func (m *DeviceVO) SetSwitchConsistent(value *bool)() {
    m.switchConsistent = value
}
// SetTagName sets the tagName property value. Device tag name
func (m *DeviceVO) SetTagName(value *string)() {
    m.tagName = value
}
// SetTypeEscaped sets the type property value. Device type:ap、gateway、switch、olt
func (m *DeviceVO) SetTypeEscaped(value *string)() {
    m.typeEscaped = value
}
// SetUplinkDeviceMac sets the uplinkDeviceMac property value. Uplink device mac
func (m *DeviceVO) SetUplinkDeviceMac(value *string)() {
    m.uplinkDeviceMac = value
}
// SetUplinkDeviceName sets the uplinkDeviceName property value. Uplink device mac name
func (m *DeviceVO) SetUplinkDeviceName(value *string)() {
    m.uplinkDeviceName = value
}
// SetUplinkDevicePort sets the uplinkDevicePort property value. Uplink device port
func (m *DeviceVO) SetUplinkDevicePort(value *string)() {
    m.uplinkDevicePort = value
}
// SetUpload sets the upload property value. Real-time total upstream traffic (bytes).
func (m *DeviceVO) SetUpload(value *int64)() {
    m.upload = value
}
// SetUptime sets the uptime property value. Device uptime
func (m *DeviceVO) SetUptime(value *string)() {
    m.uptime = value
}
// SetUptimeLong sets the uptimeLong property value. Runtime duration, in seconds (s).
func (m *DeviceVO) SetUptimeLong(value *int64)() {
    m.uptimeLong = value
}
// SetVersion sets the version property value. Software version, such as "2.5.0," extracted from DeviceDO.firmwareVersion - "2.5.0 Build 20190118 Rel. 64821."
func (m *DeviceVO) SetVersion(value *string)() {
    m.version = value
}
// SetWirelessRouter sets the wirelessRouter property value. Indicates whether it is a wireless router; it is true only when this device is a wireless router.
func (m *DeviceVO) SetWirelessRouter(value *bool)() {
    m.wirelessRouter = value
}
type DeviceVOable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetActive()(*bool)
    GetAddedInAdvanced()(*bool)
    GetAddress()(*string)
    GetAdoptFailType()(*int32)
    GetCategory()(*string)
    GetClientNum()(*int32)
    GetCombinedGateway()(*bool)
    GetCompatible()(*int32)
    GetCompoundModel()(*string)
    GetConfigSyncStatus()(*int32)
    GetCpuUtil()(*int32)
    GetCustomId()(*string)
    GetCustomName()(*string)
    GetDeviceSeriesType()(*int32)
    GetDownload()(*int64)
    GetDueTime()(*int64)
    GetDueTimeLeft()(*int64)
    GetDuplex()(*int32)
    GetEcspFirstVersion()(*int32)
    GetEos()(*int64)
    GetEost()(*int64)
    GetEs()(*bool)
    GetFeatureLimit()(ApFeatureLimitVOable)
    GetFirmwareVersion()(*string)
    GetFwDownload()(*bool)
    GetHealthScore()(*int32)
    GetHwVersion()(*string)
    GetInWhitelist()(*bool)
    GetIp()(*string)
    GetIppt()(*bool)
    GetIpv6List()([]string)
    GetLastSeen()(*int64)
    GetLatestVersion()(*string)
    GetLicenseStatus()(*int32)
    GetLicenseStatusStr()(*string)
    GetLicenseUnbindingLimit()(*int32)
    GetLinkSpeed()(*int32)
    GetLocateEnable()(*bool)
    GetLocation()(LocationVOable)
    GetMac()(*string)
    GetMemUtil()(*int32)
    GetModel()(*string)
    GetModelVersion()(*string)
    GetName()(*string)
    GetNeedUpgrade()(*bool)
    GetOnlineUpgradeStatus()(*int32)
    GetPackageCaptureStatus()(*int32)
    GetPowerMode()(*int32)
    GetPowerModeList()([]int32)
    GetPreConfigErrorCode()(*int32)
    GetPreConfigRetryType()(*int32)
    GetPublicIp()(*string)
    GetResource()(*int32)
    GetShowModel()(*string)
    GetSite()(*string)
    GetSiteName()(*string)
    GetSn()(*string)
    GetSpecialModel()(*string)
    GetStatus()(*int32)
    GetStatusCategory()(*int32)
    GetSubDevType()(*int32)
    GetSupportAnomaly()(*bool)
    GetSupportIppt()(*bool)
    GetSupportRunningConfig()(*bool)
    GetSwitchConsistent()(*bool)
    GetTagName()(*string)
    GetTypeEscaped()(*string)
    GetUplinkDeviceMac()(*string)
    GetUplinkDeviceName()(*string)
    GetUplinkDevicePort()(*string)
    GetUpload()(*int64)
    GetUptime()(*string)
    GetUptimeLong()(*int64)
    GetVersion()(*string)
    GetWirelessRouter()(*bool)
    SetActive(value *bool)()
    SetAddedInAdvanced(value *bool)()
    SetAddress(value *string)()
    SetAdoptFailType(value *int32)()
    SetCategory(value *string)()
    SetClientNum(value *int32)()
    SetCombinedGateway(value *bool)()
    SetCompatible(value *int32)()
    SetCompoundModel(value *string)()
    SetConfigSyncStatus(value *int32)()
    SetCpuUtil(value *int32)()
    SetCustomId(value *string)()
    SetCustomName(value *string)()
    SetDeviceSeriesType(value *int32)()
    SetDownload(value *int64)()
    SetDueTime(value *int64)()
    SetDueTimeLeft(value *int64)()
    SetDuplex(value *int32)()
    SetEcspFirstVersion(value *int32)()
    SetEos(value *int64)()
    SetEost(value *int64)()
    SetEs(value *bool)()
    SetFeatureLimit(value ApFeatureLimitVOable)()
    SetFirmwareVersion(value *string)()
    SetFwDownload(value *bool)()
    SetHealthScore(value *int32)()
    SetHwVersion(value *string)()
    SetInWhitelist(value *bool)()
    SetIp(value *string)()
    SetIppt(value *bool)()
    SetIpv6List(value []string)()
    SetLastSeen(value *int64)()
    SetLatestVersion(value *string)()
    SetLicenseStatus(value *int32)()
    SetLicenseStatusStr(value *string)()
    SetLicenseUnbindingLimit(value *int32)()
    SetLinkSpeed(value *int32)()
    SetLocateEnable(value *bool)()
    SetLocation(value LocationVOable)()
    SetMac(value *string)()
    SetMemUtil(value *int32)()
    SetModel(value *string)()
    SetModelVersion(value *string)()
    SetName(value *string)()
    SetNeedUpgrade(value *bool)()
    SetOnlineUpgradeStatus(value *int32)()
    SetPackageCaptureStatus(value *int32)()
    SetPowerMode(value *int32)()
    SetPowerModeList(value []int32)()
    SetPreConfigErrorCode(value *int32)()
    SetPreConfigRetryType(value *int32)()
    SetPublicIp(value *string)()
    SetResource(value *int32)()
    SetShowModel(value *string)()
    SetSite(value *string)()
    SetSiteName(value *string)()
    SetSn(value *string)()
    SetSpecialModel(value *string)()
    SetStatus(value *int32)()
    SetStatusCategory(value *int32)()
    SetSubDevType(value *int32)()
    SetSupportAnomaly(value *bool)()
    SetSupportIppt(value *bool)()
    SetSupportRunningConfig(value *bool)()
    SetSwitchConsistent(value *bool)()
    SetTagName(value *string)()
    SetTypeEscaped(value *string)()
    SetUplinkDeviceMac(value *string)()
    SetUplinkDeviceName(value *string)()
    SetUplinkDevicePort(value *string)()
    SetUpload(value *int64)()
    SetUptime(value *string)()
    SetUptimeLong(value *int64)()
    SetVersion(value *string)()
    SetWirelessRouter(value *bool)()
}
