// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ExportMessage struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The timeStamp of the message end time.
    endTime *int64
    // Message parameter [format] should be 0 or 1. 0:csv; 1:xlsx.
    format *int32
    // When the device supports Dual-SIM cardm parameter [simCard] should be 1 or 2. 1: SIM1; 2: SIM2.
    simCard *int32
    // The timeStamp of the message start time.
    startTime *int64
    // Message parameter [type] should be 0 or 1. 0:inbox; 1:outbox.
    typeEscaped *int32
}
// NewExportMessage instantiates a new ExportMessage and sets the default values.
func NewExportMessage()(*ExportMessage) {
    m := &ExportMessage{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateExportMessageFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateExportMessageFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewExportMessage(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ExportMessage) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetEndTime gets the endTime property value. The timeStamp of the message end time.
// returns a *int64 when successful
func (m *ExportMessage) GetEndTime()(*int64) {
    return m.endTime
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ExportMessage) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["endTime"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEndTime(val)
        }
        return nil
    }
    res["format"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFormat(val)
        }
        return nil
    }
    res["simCard"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSimCard(val)
        }
        return nil
    }
    res["startTime"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStartTime(val)
        }
        return nil
    }
    res["type"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTypeEscaped(val)
        }
        return nil
    }
    return res
}
// GetFormat gets the format property value. Message parameter [format] should be 0 or 1. 0:csv; 1:xlsx.
// returns a *int32 when successful
func (m *ExportMessage) GetFormat()(*int32) {
    return m.format
}
// GetSimCard gets the simCard property value. When the device supports Dual-SIM cardm parameter [simCard] should be 1 or 2. 1: SIM1; 2: SIM2.
// returns a *int32 when successful
func (m *ExportMessage) GetSimCard()(*int32) {
    return m.simCard
}
// GetStartTime gets the startTime property value. The timeStamp of the message start time.
// returns a *int64 when successful
func (m *ExportMessage) GetStartTime()(*int64) {
    return m.startTime
}
// GetTypeEscaped gets the type property value. Message parameter [type] should be 0 or 1. 0:inbox; 1:outbox.
// returns a *int32 when successful
func (m *ExportMessage) GetTypeEscaped()(*int32) {
    return m.typeEscaped
}
// Serialize serializes information the current object
func (m *ExportMessage) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteInt64Value("endTime", m.GetEndTime())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("format", m.GetFormat())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("simCard", m.GetSimCard())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("startTime", m.GetStartTime())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("type", m.GetTypeEscaped())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ExportMessage) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetEndTime sets the endTime property value. The timeStamp of the message end time.
func (m *ExportMessage) SetEndTime(value *int64)() {
    m.endTime = value
}
// SetFormat sets the format property value. Message parameter [format] should be 0 or 1. 0:csv; 1:xlsx.
func (m *ExportMessage) SetFormat(value *int32)() {
    m.format = value
}
// SetSimCard sets the simCard property value. When the device supports Dual-SIM cardm parameter [simCard] should be 1 or 2. 1: SIM1; 2: SIM2.
func (m *ExportMessage) SetSimCard(value *int32)() {
    m.simCard = value
}
// SetStartTime sets the startTime property value. The timeStamp of the message start time.
func (m *ExportMessage) SetStartTime(value *int64)() {
    m.startTime = value
}
// SetTypeEscaped sets the type property value. Message parameter [type] should be 0 or 1. 0:inbox; 1:outbox.
func (m *ExportMessage) SetTypeEscaped(value *int32)() {
    m.typeEscaped = value
}
type ExportMessageable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetEndTime()(*int64)
    GetFormat()(*int32)
    GetSimCard()(*int32)
    GetStartTime()(*int64)
    GetTypeEscaped()(*int32)
    SetEndTime(value *int64)()
    SetFormat(value *int32)()
    SetSimCard(value *int32)()
    SetStartTime(value *int64)()
    SetTypeEscaped(value *int32)()
}
