// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type GridVOUpgradeableDevices struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Current page number.
    currentPage *int32
    // Number of entries per page.
    currentSize *int32
    // The data property
    data []UpgradeableDevicesable
    // Total rows of all items.
    totalRows *int64
}
// NewGridVOUpgradeableDevices instantiates a new GridVOUpgradeableDevices and sets the default values.
func NewGridVOUpgradeableDevices()(*GridVOUpgradeableDevices) {
    m := &GridVOUpgradeableDevices{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateGridVOUpgradeableDevicesFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateGridVOUpgradeableDevicesFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewGridVOUpgradeableDevices(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *GridVOUpgradeableDevices) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCurrentPage gets the currentPage property value. Current page number.
// returns a *int32 when successful
func (m *GridVOUpgradeableDevices) GetCurrentPage()(*int32) {
    return m.currentPage
}
// GetCurrentSize gets the currentSize property value. Number of entries per page.
// returns a *int32 when successful
func (m *GridVOUpgradeableDevices) GetCurrentSize()(*int32) {
    return m.currentSize
}
// GetData gets the data property value. The data property
// returns a []UpgradeableDevicesable when successful
func (m *GridVOUpgradeableDevices) GetData()([]UpgradeableDevicesable) {
    return m.data
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *GridVOUpgradeableDevices) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["currentPage"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCurrentPage(val)
        }
        return nil
    }
    res["currentSize"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCurrentSize(val)
        }
        return nil
    }
    res["data"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateUpgradeableDevicesFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]UpgradeableDevicesable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(UpgradeableDevicesable)
                }
            }
            m.SetData(res)
        }
        return nil
    }
    res["totalRows"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTotalRows(val)
        }
        return nil
    }
    return res
}
// GetTotalRows gets the totalRows property value. Total rows of all items.
// returns a *int64 when successful
func (m *GridVOUpgradeableDevices) GetTotalRows()(*int64) {
    return m.totalRows
}
// Serialize serializes information the current object
func (m *GridVOUpgradeableDevices) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteInt32Value("currentPage", m.GetCurrentPage())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("currentSize", m.GetCurrentSize())
        if err != nil {
            return err
        }
    }
    if m.GetData() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetData()))
        for i, v := range m.GetData() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("data", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("totalRows", m.GetTotalRows())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *GridVOUpgradeableDevices) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCurrentPage sets the currentPage property value. Current page number.
func (m *GridVOUpgradeableDevices) SetCurrentPage(value *int32)() {
    m.currentPage = value
}
// SetCurrentSize sets the currentSize property value. Number of entries per page.
func (m *GridVOUpgradeableDevices) SetCurrentSize(value *int32)() {
    m.currentSize = value
}
// SetData sets the data property value. The data property
func (m *GridVOUpgradeableDevices) SetData(value []UpgradeableDevicesable)() {
    m.data = value
}
// SetTotalRows sets the totalRows property value. Total rows of all items.
func (m *GridVOUpgradeableDevices) SetTotalRows(value *int64)() {
    m.totalRows = value
}
type GridVOUpgradeableDevicesable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCurrentPage()(*int32)
    GetCurrentSize()(*int32)
    GetData()([]UpgradeableDevicesable)
    GetTotalRows()(*int64)
    SetCurrentPage(value *int32)()
    SetCurrentSize(value *int32)()
    SetData(value []UpgradeableDevicesable)()
    SetTotalRows(value *int64)()
}
