// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type IdpMetadataOpenApiVO struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // IdP description should contain 0 to 128 characters.
    description *string
    // The IdP entity id which must be unique in same Omadac.
    entityId *string
    // Login url
    loginUrl *string
    // IdP name should contain 1 to 32 characters.
    name *string
    // BASE64 encoded string of x509 certificate.
    x509Certificate *string
}
// NewIdpMetadataOpenApiVO instantiates a new IdpMetadataOpenApiVO and sets the default values.
func NewIdpMetadataOpenApiVO()(*IdpMetadataOpenApiVO) {
    m := &IdpMetadataOpenApiVO{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateIdpMetadataOpenApiVOFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateIdpMetadataOpenApiVOFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewIdpMetadataOpenApiVO(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *IdpMetadataOpenApiVO) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetDescription gets the description property value. IdP description should contain 0 to 128 characters.
// returns a *string when successful
func (m *IdpMetadataOpenApiVO) GetDescription()(*string) {
    return m.description
}
// GetEntityId gets the entityId property value. The IdP entity id which must be unique in same Omadac.
// returns a *string when successful
func (m *IdpMetadataOpenApiVO) GetEntityId()(*string) {
    return m.entityId
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *IdpMetadataOpenApiVO) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["description"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDescription(val)
        }
        return nil
    }
    res["entityId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEntityId(val)
        }
        return nil
    }
    res["loginUrl"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLoginUrl(val)
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["x509Certificate"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetX509Certificate(val)
        }
        return nil
    }
    return res
}
// GetLoginUrl gets the loginUrl property value. Login url
// returns a *string when successful
func (m *IdpMetadataOpenApiVO) GetLoginUrl()(*string) {
    return m.loginUrl
}
// GetName gets the name property value. IdP name should contain 1 to 32 characters.
// returns a *string when successful
func (m *IdpMetadataOpenApiVO) GetName()(*string) {
    return m.name
}
// GetX509Certificate gets the x509Certificate property value. BASE64 encoded string of x509 certificate.
// returns a *string when successful
func (m *IdpMetadataOpenApiVO) GetX509Certificate()(*string) {
    return m.x509Certificate
}
// Serialize serializes information the current object
func (m *IdpMetadataOpenApiVO) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("description", m.GetDescription())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("entityId", m.GetEntityId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("loginUrl", m.GetLoginUrl())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("x509Certificate", m.GetX509Certificate())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *IdpMetadataOpenApiVO) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetDescription sets the description property value. IdP description should contain 0 to 128 characters.
func (m *IdpMetadataOpenApiVO) SetDescription(value *string)() {
    m.description = value
}
// SetEntityId sets the entityId property value. The IdP entity id which must be unique in same Omadac.
func (m *IdpMetadataOpenApiVO) SetEntityId(value *string)() {
    m.entityId = value
}
// SetLoginUrl sets the loginUrl property value. Login url
func (m *IdpMetadataOpenApiVO) SetLoginUrl(value *string)() {
    m.loginUrl = value
}
// SetName sets the name property value. IdP name should contain 1 to 32 characters.
func (m *IdpMetadataOpenApiVO) SetName(value *string)() {
    m.name = value
}
// SetX509Certificate sets the x509Certificate property value. BASE64 encoded string of x509 certificate.
func (m *IdpMetadataOpenApiVO) SetX509Certificate(value *string)() {
    m.x509Certificate = value
}
type IdpMetadataOpenApiVOable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetDescription()(*string)
    GetEntityId()(*string)
    GetLoginUrl()(*string)
    GetName()(*string)
    GetX509Certificate()(*string)
    SetDescription(value *string)()
    SetEntityId(value *string)()
    SetLoginUrl(value *string)()
    SetName(value *string)()
    SetX509Certificate(value *string)()
}
