// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Interference at most two types of interference data are reported in Inter, sorted in descending order of interference intensity
type Interference struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Interference should be within the range of -96 ~ -48
    inf *int32
    // Interference data, the data refer to the interference intensity and the times of interferences, and they are used to create histograms.
    infData InterferenceDataEntityable
    // Interference Type should be a value as follows: 0: invalid parameter; 1: MWO; 2: CW; 3: WLAN; 4: FHSS.
    infType *int32
}
// NewInterference instantiates a new Interference and sets the default values.
func NewInterference()(*Interference) {
    m := &Interference{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateInterferenceFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateInterferenceFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewInterference(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Interference) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Interference) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["inf"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetInf(val)
        }
        return nil
    }
    res["infData"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateInterferenceDataEntityFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetInfData(val.(InterferenceDataEntityable))
        }
        return nil
    }
    res["infType"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetInfType(val)
        }
        return nil
    }
    return res
}
// GetInf gets the inf property value. Interference should be within the range of -96 ~ -48
// returns a *int32 when successful
func (m *Interference) GetInf()(*int32) {
    return m.inf
}
// GetInfData gets the infData property value. Interference data, the data refer to the interference intensity and the times of interferences, and they are used to create histograms.
// returns a InterferenceDataEntityable when successful
func (m *Interference) GetInfData()(InterferenceDataEntityable) {
    return m.infData
}
// GetInfType gets the infType property value. Interference Type should be a value as follows: 0: invalid parameter; 1: MWO; 2: CW; 3: WLAN; 4: FHSS.
// returns a *int32 when successful
func (m *Interference) GetInfType()(*int32) {
    return m.infType
}
// Serialize serializes information the current object
func (m *Interference) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteInt32Value("inf", m.GetInf())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("infData", m.GetInfData())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("infType", m.GetInfType())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Interference) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetInf sets the inf property value. Interference should be within the range of -96 ~ -48
func (m *Interference) SetInf(value *int32)() {
    m.inf = value
}
// SetInfData sets the infData property value. Interference data, the data refer to the interference intensity and the times of interferences, and they are used to create histograms.
func (m *Interference) SetInfData(value InterferenceDataEntityable)() {
    m.infData = value
}
// SetInfType sets the infType property value. Interference Type should be a value as follows: 0: invalid parameter; 1: MWO; 2: CW; 3: WLAN; 4: FHSS.
func (m *Interference) SetInfType(value *int32)() {
    m.infType = value
}
type Interferenceable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetInf()(*int32)
    GetInfData()(InterferenceDataEntityable)
    GetInfType()(*int32)
    SetInf(value *int32)()
    SetInfData(value InterferenceDataEntityable)()
    SetInfType(value *int32)()
}
