// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Ipv6TunnelOpenApiVO it is required when protoType is 6to4Tunnel
type Ipv6TunnelOpenApiVO struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // DNS Address Type should be a value as follows: 0: Get from ISP Dynamically; 1: Static.
    dnsType *int32
    // It takes effect when [dnsType] is 1.
    primaryDns *string
}
// NewIpv6TunnelOpenApiVO instantiates a new Ipv6TunnelOpenApiVO and sets the default values.
func NewIpv6TunnelOpenApiVO()(*Ipv6TunnelOpenApiVO) {
    m := &Ipv6TunnelOpenApiVO{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateIpv6TunnelOpenApiVOFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateIpv6TunnelOpenApiVOFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewIpv6TunnelOpenApiVO(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Ipv6TunnelOpenApiVO) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetDnsType gets the dnsType property value. DNS Address Type should be a value as follows: 0: Get from ISP Dynamically; 1: Static.
// returns a *int32 when successful
func (m *Ipv6TunnelOpenApiVO) GetDnsType()(*int32) {
    return m.dnsType
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Ipv6TunnelOpenApiVO) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["dnsType"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDnsType(val)
        }
        return nil
    }
    res["primaryDns"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPrimaryDns(val)
        }
        return nil
    }
    return res
}
// GetPrimaryDns gets the primaryDns property value. It takes effect when [dnsType] is 1.
// returns a *string when successful
func (m *Ipv6TunnelOpenApiVO) GetPrimaryDns()(*string) {
    return m.primaryDns
}
// Serialize serializes information the current object
func (m *Ipv6TunnelOpenApiVO) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteInt32Value("dnsType", m.GetDnsType())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("primaryDns", m.GetPrimaryDns())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Ipv6TunnelOpenApiVO) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetDnsType sets the dnsType property value. DNS Address Type should be a value as follows: 0: Get from ISP Dynamically; 1: Static.
func (m *Ipv6TunnelOpenApiVO) SetDnsType(value *int32)() {
    m.dnsType = value
}
// SetPrimaryDns sets the primaryDns property value. It takes effect when [dnsType] is 1.
func (m *Ipv6TunnelOpenApiVO) SetPrimaryDns(value *string)() {
    m.primaryDns = value
}
type Ipv6TunnelOpenApiVOable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetDnsType()(*int32)
    GetPrimaryDns()(*string)
    SetDnsType(value *int32)()
    SetPrimaryDns(value *string)()
}
