// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type LanProfileConfigOpenApiVO struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // BandCtrl
    bandCtrl BandCtrlVOable
    // BandWidthCtrlType should be a value as follows: 0: off, 1: rate limit, 2: storming control
    bandWidthCtrlType *int32
    // DHCPL2RelaySettings
    dhcpL2RelaySettings DhcpL2RelayVOable
    // 802.1p Priority
    dot1pPriority *int32
    // Dot1x should be a value as follows: 0: force unauthorized, 1: force authorized, 2:auto
    dot1x *int32
    // EEE enable status
    eeeEnable *bool
    // IGMP Snooping fast leave enable status
    fastLeaveEnable *bool
    // FlowControl enable status
    flowControlEnable *bool
    // Indicates whether igmp fast leave is enabled
    igmpFastLeaveEnable *bool
    // LLDP-MED enable status
    lldpMedEnable *bool
    // LoopbackDetect enable status
    loopbackDetectEnable *bool
    // LoopbackDetectVLANBased enable status
    loopbackDetectVlanBasedEnable *bool
    // Indicates whether mld fast leave is enabled
    mldFastLeaveEnable *bool
    // Name should contain 1 to 128 characters.
    name *string
    // Native network ID, Native Network cannot be selected from Tagged Networks or Untagged Networks.
    nativeNetworkId *string
    // PoE should be a value as follows: 0: on, 1: off, 2: "do not modify"
    poe *int32
    // Port-isolation enable status
    portIsolationEnable *bool
    // SpanningTree enable status
    spanningTreeEnable *bool
    // SpanningTree Setting
    spanningTreeSetting SpanningTreeSettingVOable
    // StormCtrl
    stormCtrl StormCtrlVOable
    // Tag network IDs
    tagNetworkIds []string
    // Trust mode
    trustMode *int32
    // Untag network IDs
    untagNetworkIds []string
    // Voice Network ID
    voiceNetworkId *string
}
// NewLanProfileConfigOpenApiVO instantiates a new LanProfileConfigOpenApiVO and sets the default values.
func NewLanProfileConfigOpenApiVO()(*LanProfileConfigOpenApiVO) {
    m := &LanProfileConfigOpenApiVO{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateLanProfileConfigOpenApiVOFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateLanProfileConfigOpenApiVOFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewLanProfileConfigOpenApiVO(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *LanProfileConfigOpenApiVO) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetBandCtrl gets the bandCtrl property value. BandCtrl
// returns a BandCtrlVOable when successful
func (m *LanProfileConfigOpenApiVO) GetBandCtrl()(BandCtrlVOable) {
    return m.bandCtrl
}
// GetBandWidthCtrlType gets the bandWidthCtrlType property value. BandWidthCtrlType should be a value as follows: 0: off, 1: rate limit, 2: storming control
// returns a *int32 when successful
func (m *LanProfileConfigOpenApiVO) GetBandWidthCtrlType()(*int32) {
    return m.bandWidthCtrlType
}
// GetDhcpL2RelaySettings gets the dhcpL2RelaySettings property value. DHCPL2RelaySettings
// returns a DhcpL2RelayVOable when successful
func (m *LanProfileConfigOpenApiVO) GetDhcpL2RelaySettings()(DhcpL2RelayVOable) {
    return m.dhcpL2RelaySettings
}
// GetDot1pPriority gets the dot1pPriority property value. 802.1p Priority
// returns a *int32 when successful
func (m *LanProfileConfigOpenApiVO) GetDot1pPriority()(*int32) {
    return m.dot1pPriority
}
// GetDot1x gets the dot1x property value. Dot1x should be a value as follows: 0: force unauthorized, 1: force authorized, 2:auto
// returns a *int32 when successful
func (m *LanProfileConfigOpenApiVO) GetDot1x()(*int32) {
    return m.dot1x
}
// GetEeeEnable gets the eeeEnable property value. EEE enable status
// returns a *bool when successful
func (m *LanProfileConfigOpenApiVO) GetEeeEnable()(*bool) {
    return m.eeeEnable
}
// GetFastLeaveEnable gets the fastLeaveEnable property value. IGMP Snooping fast leave enable status
// returns a *bool when successful
func (m *LanProfileConfigOpenApiVO) GetFastLeaveEnable()(*bool) {
    return m.fastLeaveEnable
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *LanProfileConfigOpenApiVO) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["bandCtrl"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateBandCtrlVOFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetBandCtrl(val.(BandCtrlVOable))
        }
        return nil
    }
    res["bandWidthCtrlType"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetBandWidthCtrlType(val)
        }
        return nil
    }
    res["dhcpL2RelaySettings"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateDhcpL2RelayVOFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDhcpL2RelaySettings(val.(DhcpL2RelayVOable))
        }
        return nil
    }
    res["dot1pPriority"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDot1pPriority(val)
        }
        return nil
    }
    res["dot1x"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDot1x(val)
        }
        return nil
    }
    res["eeeEnable"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEeeEnable(val)
        }
        return nil
    }
    res["fastLeaveEnable"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFastLeaveEnable(val)
        }
        return nil
    }
    res["flowControlEnable"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFlowControlEnable(val)
        }
        return nil
    }
    res["igmpFastLeaveEnable"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIgmpFastLeaveEnable(val)
        }
        return nil
    }
    res["lldpMedEnable"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLldpMedEnable(val)
        }
        return nil
    }
    res["loopbackDetectEnable"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLoopbackDetectEnable(val)
        }
        return nil
    }
    res["loopbackDetectVlanBasedEnable"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLoopbackDetectVlanBasedEnable(val)
        }
        return nil
    }
    res["mldFastLeaveEnable"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMldFastLeaveEnable(val)
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["nativeNetworkId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNativeNetworkId(val)
        }
        return nil
    }
    res["poe"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPoe(val)
        }
        return nil
    }
    res["portIsolationEnable"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPortIsolationEnable(val)
        }
        return nil
    }
    res["spanningTreeEnable"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSpanningTreeEnable(val)
        }
        return nil
    }
    res["spanningTreeSetting"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateSpanningTreeSettingVOFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSpanningTreeSetting(val.(SpanningTreeSettingVOable))
        }
        return nil
    }
    res["stormCtrl"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateStormCtrlVOFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStormCtrl(val.(StormCtrlVOable))
        }
        return nil
    }
    res["tagNetworkIds"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("string")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]string, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*string))
                }
            }
            m.SetTagNetworkIds(res)
        }
        return nil
    }
    res["trustMode"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTrustMode(val)
        }
        return nil
    }
    res["untagNetworkIds"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("string")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]string, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*string))
                }
            }
            m.SetUntagNetworkIds(res)
        }
        return nil
    }
    res["voiceNetworkId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetVoiceNetworkId(val)
        }
        return nil
    }
    return res
}
// GetFlowControlEnable gets the flowControlEnable property value. FlowControl enable status
// returns a *bool when successful
func (m *LanProfileConfigOpenApiVO) GetFlowControlEnable()(*bool) {
    return m.flowControlEnable
}
// GetIgmpFastLeaveEnable gets the igmpFastLeaveEnable property value. Indicates whether igmp fast leave is enabled
// returns a *bool when successful
func (m *LanProfileConfigOpenApiVO) GetIgmpFastLeaveEnable()(*bool) {
    return m.igmpFastLeaveEnable
}
// GetLldpMedEnable gets the lldpMedEnable property value. LLDP-MED enable status
// returns a *bool when successful
func (m *LanProfileConfigOpenApiVO) GetLldpMedEnable()(*bool) {
    return m.lldpMedEnable
}
// GetLoopbackDetectEnable gets the loopbackDetectEnable property value. LoopbackDetect enable status
// returns a *bool when successful
func (m *LanProfileConfigOpenApiVO) GetLoopbackDetectEnable()(*bool) {
    return m.loopbackDetectEnable
}
// GetLoopbackDetectVlanBasedEnable gets the loopbackDetectVlanBasedEnable property value. LoopbackDetectVLANBased enable status
// returns a *bool when successful
func (m *LanProfileConfigOpenApiVO) GetLoopbackDetectVlanBasedEnable()(*bool) {
    return m.loopbackDetectVlanBasedEnable
}
// GetMldFastLeaveEnable gets the mldFastLeaveEnable property value. Indicates whether mld fast leave is enabled
// returns a *bool when successful
func (m *LanProfileConfigOpenApiVO) GetMldFastLeaveEnable()(*bool) {
    return m.mldFastLeaveEnable
}
// GetName gets the name property value. Name should contain 1 to 128 characters.
// returns a *string when successful
func (m *LanProfileConfigOpenApiVO) GetName()(*string) {
    return m.name
}
// GetNativeNetworkId gets the nativeNetworkId property value. Native network ID, Native Network cannot be selected from Tagged Networks or Untagged Networks.
// returns a *string when successful
func (m *LanProfileConfigOpenApiVO) GetNativeNetworkId()(*string) {
    return m.nativeNetworkId
}
// GetPoe gets the poe property value. PoE should be a value as follows: 0: on, 1: off, 2: "do not modify"
// returns a *int32 when successful
func (m *LanProfileConfigOpenApiVO) GetPoe()(*int32) {
    return m.poe
}
// GetPortIsolationEnable gets the portIsolationEnable property value. Port-isolation enable status
// returns a *bool when successful
func (m *LanProfileConfigOpenApiVO) GetPortIsolationEnable()(*bool) {
    return m.portIsolationEnable
}
// GetSpanningTreeEnable gets the spanningTreeEnable property value. SpanningTree enable status
// returns a *bool when successful
func (m *LanProfileConfigOpenApiVO) GetSpanningTreeEnable()(*bool) {
    return m.spanningTreeEnable
}
// GetSpanningTreeSetting gets the spanningTreeSetting property value. SpanningTree Setting
// returns a SpanningTreeSettingVOable when successful
func (m *LanProfileConfigOpenApiVO) GetSpanningTreeSetting()(SpanningTreeSettingVOable) {
    return m.spanningTreeSetting
}
// GetStormCtrl gets the stormCtrl property value. StormCtrl
// returns a StormCtrlVOable when successful
func (m *LanProfileConfigOpenApiVO) GetStormCtrl()(StormCtrlVOable) {
    return m.stormCtrl
}
// GetTagNetworkIds gets the tagNetworkIds property value. Tag network IDs
// returns a []string when successful
func (m *LanProfileConfigOpenApiVO) GetTagNetworkIds()([]string) {
    return m.tagNetworkIds
}
// GetTrustMode gets the trustMode property value. Trust mode
// returns a *int32 when successful
func (m *LanProfileConfigOpenApiVO) GetTrustMode()(*int32) {
    return m.trustMode
}
// GetUntagNetworkIds gets the untagNetworkIds property value. Untag network IDs
// returns a []string when successful
func (m *LanProfileConfigOpenApiVO) GetUntagNetworkIds()([]string) {
    return m.untagNetworkIds
}
// GetVoiceNetworkId gets the voiceNetworkId property value. Voice Network ID
// returns a *string when successful
func (m *LanProfileConfigOpenApiVO) GetVoiceNetworkId()(*string) {
    return m.voiceNetworkId
}
// Serialize serializes information the current object
func (m *LanProfileConfigOpenApiVO) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("bandCtrl", m.GetBandCtrl())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("bandWidthCtrlType", m.GetBandWidthCtrlType())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("dhcpL2RelaySettings", m.GetDhcpL2RelaySettings())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("dot1pPriority", m.GetDot1pPriority())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("dot1x", m.GetDot1x())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("eeeEnable", m.GetEeeEnable())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("fastLeaveEnable", m.GetFastLeaveEnable())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("flowControlEnable", m.GetFlowControlEnable())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("igmpFastLeaveEnable", m.GetIgmpFastLeaveEnable())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("lldpMedEnable", m.GetLldpMedEnable())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("loopbackDetectEnable", m.GetLoopbackDetectEnable())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("loopbackDetectVlanBasedEnable", m.GetLoopbackDetectVlanBasedEnable())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("mldFastLeaveEnable", m.GetMldFastLeaveEnable())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("nativeNetworkId", m.GetNativeNetworkId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("poe", m.GetPoe())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("portIsolationEnable", m.GetPortIsolationEnable())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("spanningTreeEnable", m.GetSpanningTreeEnable())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("spanningTreeSetting", m.GetSpanningTreeSetting())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("stormCtrl", m.GetStormCtrl())
        if err != nil {
            return err
        }
    }
    if m.GetTagNetworkIds() != nil {
        err := writer.WriteCollectionOfStringValues("tagNetworkIds", m.GetTagNetworkIds())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("trustMode", m.GetTrustMode())
        if err != nil {
            return err
        }
    }
    if m.GetUntagNetworkIds() != nil {
        err := writer.WriteCollectionOfStringValues("untagNetworkIds", m.GetUntagNetworkIds())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("voiceNetworkId", m.GetVoiceNetworkId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *LanProfileConfigOpenApiVO) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetBandCtrl sets the bandCtrl property value. BandCtrl
func (m *LanProfileConfigOpenApiVO) SetBandCtrl(value BandCtrlVOable)() {
    m.bandCtrl = value
}
// SetBandWidthCtrlType sets the bandWidthCtrlType property value. BandWidthCtrlType should be a value as follows: 0: off, 1: rate limit, 2: storming control
func (m *LanProfileConfigOpenApiVO) SetBandWidthCtrlType(value *int32)() {
    m.bandWidthCtrlType = value
}
// SetDhcpL2RelaySettings sets the dhcpL2RelaySettings property value. DHCPL2RelaySettings
func (m *LanProfileConfigOpenApiVO) SetDhcpL2RelaySettings(value DhcpL2RelayVOable)() {
    m.dhcpL2RelaySettings = value
}
// SetDot1pPriority sets the dot1pPriority property value. 802.1p Priority
func (m *LanProfileConfigOpenApiVO) SetDot1pPriority(value *int32)() {
    m.dot1pPriority = value
}
// SetDot1x sets the dot1x property value. Dot1x should be a value as follows: 0: force unauthorized, 1: force authorized, 2:auto
func (m *LanProfileConfigOpenApiVO) SetDot1x(value *int32)() {
    m.dot1x = value
}
// SetEeeEnable sets the eeeEnable property value. EEE enable status
func (m *LanProfileConfigOpenApiVO) SetEeeEnable(value *bool)() {
    m.eeeEnable = value
}
// SetFastLeaveEnable sets the fastLeaveEnable property value. IGMP Snooping fast leave enable status
func (m *LanProfileConfigOpenApiVO) SetFastLeaveEnable(value *bool)() {
    m.fastLeaveEnable = value
}
// SetFlowControlEnable sets the flowControlEnable property value. FlowControl enable status
func (m *LanProfileConfigOpenApiVO) SetFlowControlEnable(value *bool)() {
    m.flowControlEnable = value
}
// SetIgmpFastLeaveEnable sets the igmpFastLeaveEnable property value. Indicates whether igmp fast leave is enabled
func (m *LanProfileConfigOpenApiVO) SetIgmpFastLeaveEnable(value *bool)() {
    m.igmpFastLeaveEnable = value
}
// SetLldpMedEnable sets the lldpMedEnable property value. LLDP-MED enable status
func (m *LanProfileConfigOpenApiVO) SetLldpMedEnable(value *bool)() {
    m.lldpMedEnable = value
}
// SetLoopbackDetectEnable sets the loopbackDetectEnable property value. LoopbackDetect enable status
func (m *LanProfileConfigOpenApiVO) SetLoopbackDetectEnable(value *bool)() {
    m.loopbackDetectEnable = value
}
// SetLoopbackDetectVlanBasedEnable sets the loopbackDetectVlanBasedEnable property value. LoopbackDetectVLANBased enable status
func (m *LanProfileConfigOpenApiVO) SetLoopbackDetectVlanBasedEnable(value *bool)() {
    m.loopbackDetectVlanBasedEnable = value
}
// SetMldFastLeaveEnable sets the mldFastLeaveEnable property value. Indicates whether mld fast leave is enabled
func (m *LanProfileConfigOpenApiVO) SetMldFastLeaveEnable(value *bool)() {
    m.mldFastLeaveEnable = value
}
// SetName sets the name property value. Name should contain 1 to 128 characters.
func (m *LanProfileConfigOpenApiVO) SetName(value *string)() {
    m.name = value
}
// SetNativeNetworkId sets the nativeNetworkId property value. Native network ID, Native Network cannot be selected from Tagged Networks or Untagged Networks.
func (m *LanProfileConfigOpenApiVO) SetNativeNetworkId(value *string)() {
    m.nativeNetworkId = value
}
// SetPoe sets the poe property value. PoE should be a value as follows: 0: on, 1: off, 2: "do not modify"
func (m *LanProfileConfigOpenApiVO) SetPoe(value *int32)() {
    m.poe = value
}
// SetPortIsolationEnable sets the portIsolationEnable property value. Port-isolation enable status
func (m *LanProfileConfigOpenApiVO) SetPortIsolationEnable(value *bool)() {
    m.portIsolationEnable = value
}
// SetSpanningTreeEnable sets the spanningTreeEnable property value. SpanningTree enable status
func (m *LanProfileConfigOpenApiVO) SetSpanningTreeEnable(value *bool)() {
    m.spanningTreeEnable = value
}
// SetSpanningTreeSetting sets the spanningTreeSetting property value. SpanningTree Setting
func (m *LanProfileConfigOpenApiVO) SetSpanningTreeSetting(value SpanningTreeSettingVOable)() {
    m.spanningTreeSetting = value
}
// SetStormCtrl sets the stormCtrl property value. StormCtrl
func (m *LanProfileConfigOpenApiVO) SetStormCtrl(value StormCtrlVOable)() {
    m.stormCtrl = value
}
// SetTagNetworkIds sets the tagNetworkIds property value. Tag network IDs
func (m *LanProfileConfigOpenApiVO) SetTagNetworkIds(value []string)() {
    m.tagNetworkIds = value
}
// SetTrustMode sets the trustMode property value. Trust mode
func (m *LanProfileConfigOpenApiVO) SetTrustMode(value *int32)() {
    m.trustMode = value
}
// SetUntagNetworkIds sets the untagNetworkIds property value. Untag network IDs
func (m *LanProfileConfigOpenApiVO) SetUntagNetworkIds(value []string)() {
    m.untagNetworkIds = value
}
// SetVoiceNetworkId sets the voiceNetworkId property value. Voice Network ID
func (m *LanProfileConfigOpenApiVO) SetVoiceNetworkId(value *string)() {
    m.voiceNetworkId = value
}
type LanProfileConfigOpenApiVOable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetBandCtrl()(BandCtrlVOable)
    GetBandWidthCtrlType()(*int32)
    GetDhcpL2RelaySettings()(DhcpL2RelayVOable)
    GetDot1pPriority()(*int32)
    GetDot1x()(*int32)
    GetEeeEnable()(*bool)
    GetFastLeaveEnable()(*bool)
    GetFlowControlEnable()(*bool)
    GetIgmpFastLeaveEnable()(*bool)
    GetLldpMedEnable()(*bool)
    GetLoopbackDetectEnable()(*bool)
    GetLoopbackDetectVlanBasedEnable()(*bool)
    GetMldFastLeaveEnable()(*bool)
    GetName()(*string)
    GetNativeNetworkId()(*string)
    GetPoe()(*int32)
    GetPortIsolationEnable()(*bool)
    GetSpanningTreeEnable()(*bool)
    GetSpanningTreeSetting()(SpanningTreeSettingVOable)
    GetStormCtrl()(StormCtrlVOable)
    GetTagNetworkIds()([]string)
    GetTrustMode()(*int32)
    GetUntagNetworkIds()([]string)
    GetVoiceNetworkId()(*string)
    SetBandCtrl(value BandCtrlVOable)()
    SetBandWidthCtrlType(value *int32)()
    SetDhcpL2RelaySettings(value DhcpL2RelayVOable)()
    SetDot1pPriority(value *int32)()
    SetDot1x(value *int32)()
    SetEeeEnable(value *bool)()
    SetFastLeaveEnable(value *bool)()
    SetFlowControlEnable(value *bool)()
    SetIgmpFastLeaveEnable(value *bool)()
    SetLldpMedEnable(value *bool)()
    SetLoopbackDetectEnable(value *bool)()
    SetLoopbackDetectVlanBasedEnable(value *bool)()
    SetMldFastLeaveEnable(value *bool)()
    SetName(value *string)()
    SetNativeNetworkId(value *string)()
    SetPoe(value *int32)()
    SetPortIsolationEnable(value *bool)()
    SetSpanningTreeEnable(value *bool)()
    SetSpanningTreeSetting(value SpanningTreeSettingVOable)()
    SetStormCtrl(value StormCtrlVOable)()
    SetTagNetworkIds(value []string)()
    SetTrustMode(value *int32)()
    SetUntagNetworkIds(value []string)()
    SetVoiceNetworkId(value *string)()
}
