// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type MspExternalUserGroupDetailOpenApiVO struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Whether having all customer permissions.
    allCustomer *bool
    // Customer role ID.
    customerRoleId *string
    // Customer role name.
    customerRoleName *string
    // Customer role type.
    customerRoleType *int32
    // The customers which can be accessed. Required when allCustomer is false.
    customers []OmadacInfoOpenApiVOable
    // The end time of the user's validity period. time range: end timestamp (Millisecond).
    endTime *int64
    // Msp external user group ID.
    id *string
    // Msp external user group name.
    name *string
    // Msp role ID.
    roleId *string
    // Msp role name.
    roleName *string
    // Msp role type.
    roleType *int32
    // The start time of the user's validity period. time range: start timestamp (Millisecond).
    startTime *int64
    // Whether the user wants to enable the temporary worker permission
    temporaryEnable *bool
    // Whether the temporary user is still valid
    temporaryValidity *int32
}
// NewMspExternalUserGroupDetailOpenApiVO instantiates a new MspExternalUserGroupDetailOpenApiVO and sets the default values.
func NewMspExternalUserGroupDetailOpenApiVO()(*MspExternalUserGroupDetailOpenApiVO) {
    m := &MspExternalUserGroupDetailOpenApiVO{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateMspExternalUserGroupDetailOpenApiVOFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateMspExternalUserGroupDetailOpenApiVOFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewMspExternalUserGroupDetailOpenApiVO(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *MspExternalUserGroupDetailOpenApiVO) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAllCustomer gets the allCustomer property value. Whether having all customer permissions.
// returns a *bool when successful
func (m *MspExternalUserGroupDetailOpenApiVO) GetAllCustomer()(*bool) {
    return m.allCustomer
}
// GetCustomerRoleId gets the customerRoleId property value. Customer role ID.
// returns a *string when successful
func (m *MspExternalUserGroupDetailOpenApiVO) GetCustomerRoleId()(*string) {
    return m.customerRoleId
}
// GetCustomerRoleName gets the customerRoleName property value. Customer role name.
// returns a *string when successful
func (m *MspExternalUserGroupDetailOpenApiVO) GetCustomerRoleName()(*string) {
    return m.customerRoleName
}
// GetCustomerRoleType gets the customerRoleType property value. Customer role type.
// returns a *int32 when successful
func (m *MspExternalUserGroupDetailOpenApiVO) GetCustomerRoleType()(*int32) {
    return m.customerRoleType
}
// GetCustomers gets the customers property value. The customers which can be accessed. Required when allCustomer is false.
// returns a []OmadacInfoOpenApiVOable when successful
func (m *MspExternalUserGroupDetailOpenApiVO) GetCustomers()([]OmadacInfoOpenApiVOable) {
    return m.customers
}
// GetEndTime gets the endTime property value. The end time of the user's validity period. time range: end timestamp (Millisecond).
// returns a *int64 when successful
func (m *MspExternalUserGroupDetailOpenApiVO) GetEndTime()(*int64) {
    return m.endTime
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *MspExternalUserGroupDetailOpenApiVO) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["allCustomer"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAllCustomer(val)
        }
        return nil
    }
    res["customerRoleId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCustomerRoleId(val)
        }
        return nil
    }
    res["customerRoleName"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCustomerRoleName(val)
        }
        return nil
    }
    res["customerRoleType"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCustomerRoleType(val)
        }
        return nil
    }
    res["customers"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateOmadacInfoOpenApiVOFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]OmadacInfoOpenApiVOable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(OmadacInfoOpenApiVOable)
                }
            }
            m.SetCustomers(res)
        }
        return nil
    }
    res["endTime"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEndTime(val)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["roleId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRoleId(val)
        }
        return nil
    }
    res["roleName"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRoleName(val)
        }
        return nil
    }
    res["roleType"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRoleType(val)
        }
        return nil
    }
    res["startTime"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStartTime(val)
        }
        return nil
    }
    res["temporaryEnable"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTemporaryEnable(val)
        }
        return nil
    }
    res["temporaryValidity"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTemporaryValidity(val)
        }
        return nil
    }
    return res
}
// GetId gets the id property value. Msp external user group ID.
// returns a *string when successful
func (m *MspExternalUserGroupDetailOpenApiVO) GetId()(*string) {
    return m.id
}
// GetName gets the name property value. Msp external user group name.
// returns a *string when successful
func (m *MspExternalUserGroupDetailOpenApiVO) GetName()(*string) {
    return m.name
}
// GetRoleId gets the roleId property value. Msp role ID.
// returns a *string when successful
func (m *MspExternalUserGroupDetailOpenApiVO) GetRoleId()(*string) {
    return m.roleId
}
// GetRoleName gets the roleName property value. Msp role name.
// returns a *string when successful
func (m *MspExternalUserGroupDetailOpenApiVO) GetRoleName()(*string) {
    return m.roleName
}
// GetRoleType gets the roleType property value. Msp role type.
// returns a *int32 when successful
func (m *MspExternalUserGroupDetailOpenApiVO) GetRoleType()(*int32) {
    return m.roleType
}
// GetStartTime gets the startTime property value. The start time of the user's validity period. time range: start timestamp (Millisecond).
// returns a *int64 when successful
func (m *MspExternalUserGroupDetailOpenApiVO) GetStartTime()(*int64) {
    return m.startTime
}
// GetTemporaryEnable gets the temporaryEnable property value. Whether the user wants to enable the temporary worker permission
// returns a *bool when successful
func (m *MspExternalUserGroupDetailOpenApiVO) GetTemporaryEnable()(*bool) {
    return m.temporaryEnable
}
// GetTemporaryValidity gets the temporaryValidity property value. Whether the temporary user is still valid
// returns a *int32 when successful
func (m *MspExternalUserGroupDetailOpenApiVO) GetTemporaryValidity()(*int32) {
    return m.temporaryValidity
}
// Serialize serializes information the current object
func (m *MspExternalUserGroupDetailOpenApiVO) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteBoolValue("allCustomer", m.GetAllCustomer())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("customerRoleId", m.GetCustomerRoleId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("customerRoleName", m.GetCustomerRoleName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("customerRoleType", m.GetCustomerRoleType())
        if err != nil {
            return err
        }
    }
    if m.GetCustomers() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetCustomers()))
        for i, v := range m.GetCustomers() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("customers", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("endTime", m.GetEndTime())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("roleId", m.GetRoleId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("roleName", m.GetRoleName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("roleType", m.GetRoleType())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("startTime", m.GetStartTime())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("temporaryEnable", m.GetTemporaryEnable())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("temporaryValidity", m.GetTemporaryValidity())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *MspExternalUserGroupDetailOpenApiVO) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAllCustomer sets the allCustomer property value. Whether having all customer permissions.
func (m *MspExternalUserGroupDetailOpenApiVO) SetAllCustomer(value *bool)() {
    m.allCustomer = value
}
// SetCustomerRoleId sets the customerRoleId property value. Customer role ID.
func (m *MspExternalUserGroupDetailOpenApiVO) SetCustomerRoleId(value *string)() {
    m.customerRoleId = value
}
// SetCustomerRoleName sets the customerRoleName property value. Customer role name.
func (m *MspExternalUserGroupDetailOpenApiVO) SetCustomerRoleName(value *string)() {
    m.customerRoleName = value
}
// SetCustomerRoleType sets the customerRoleType property value. Customer role type.
func (m *MspExternalUserGroupDetailOpenApiVO) SetCustomerRoleType(value *int32)() {
    m.customerRoleType = value
}
// SetCustomers sets the customers property value. The customers which can be accessed. Required when allCustomer is false.
func (m *MspExternalUserGroupDetailOpenApiVO) SetCustomers(value []OmadacInfoOpenApiVOable)() {
    m.customers = value
}
// SetEndTime sets the endTime property value. The end time of the user's validity period. time range: end timestamp (Millisecond).
func (m *MspExternalUserGroupDetailOpenApiVO) SetEndTime(value *int64)() {
    m.endTime = value
}
// SetId sets the id property value. Msp external user group ID.
func (m *MspExternalUserGroupDetailOpenApiVO) SetId(value *string)() {
    m.id = value
}
// SetName sets the name property value. Msp external user group name.
func (m *MspExternalUserGroupDetailOpenApiVO) SetName(value *string)() {
    m.name = value
}
// SetRoleId sets the roleId property value. Msp role ID.
func (m *MspExternalUserGroupDetailOpenApiVO) SetRoleId(value *string)() {
    m.roleId = value
}
// SetRoleName sets the roleName property value. Msp role name.
func (m *MspExternalUserGroupDetailOpenApiVO) SetRoleName(value *string)() {
    m.roleName = value
}
// SetRoleType sets the roleType property value. Msp role type.
func (m *MspExternalUserGroupDetailOpenApiVO) SetRoleType(value *int32)() {
    m.roleType = value
}
// SetStartTime sets the startTime property value. The start time of the user's validity period. time range: start timestamp (Millisecond).
func (m *MspExternalUserGroupDetailOpenApiVO) SetStartTime(value *int64)() {
    m.startTime = value
}
// SetTemporaryEnable sets the temporaryEnable property value. Whether the user wants to enable the temporary worker permission
func (m *MspExternalUserGroupDetailOpenApiVO) SetTemporaryEnable(value *bool)() {
    m.temporaryEnable = value
}
// SetTemporaryValidity sets the temporaryValidity property value. Whether the temporary user is still valid
func (m *MspExternalUserGroupDetailOpenApiVO) SetTemporaryValidity(value *int32)() {
    m.temporaryValidity = value
}
type MspExternalUserGroupDetailOpenApiVOable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAllCustomer()(*bool)
    GetCustomerRoleId()(*string)
    GetCustomerRoleName()(*string)
    GetCustomerRoleType()(*int32)
    GetCustomers()([]OmadacInfoOpenApiVOable)
    GetEndTime()(*int64)
    GetId()(*string)
    GetName()(*string)
    GetRoleId()(*string)
    GetRoleName()(*string)
    GetRoleType()(*int32)
    GetStartTime()(*int64)
    GetTemporaryEnable()(*bool)
    GetTemporaryValidity()(*int32)
    SetAllCustomer(value *bool)()
    SetCustomerRoleId(value *string)()
    SetCustomerRoleName(value *string)()
    SetCustomerRoleType(value *int32)()
    SetCustomers(value []OmadacInfoOpenApiVOable)()
    SetEndTime(value *int64)()
    SetId(value *string)()
    SetName(value *string)()
    SetRoleId(value *string)()
    SetRoleName(value *string)()
    SetRoleType(value *int32)()
    SetStartTime(value *int64)()
    SetTemporaryEnable(value *bool)()
    SetTemporaryValidity(value *int32)()
}
