// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type OperationResponseListDot1xEapInfoOpenApiVO struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The errorCode property
    errorCode *int32
    // The msg property
    msg *string
    // The result property
    result []Dot1xEapInfoOpenApiVOable
}
// NewOperationResponseListDot1xEapInfoOpenApiVO instantiates a new OperationResponseListDot1xEapInfoOpenApiVO and sets the default values.
func NewOperationResponseListDot1xEapInfoOpenApiVO()(*OperationResponseListDot1xEapInfoOpenApiVO) {
    m := &OperationResponseListDot1xEapInfoOpenApiVO{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateOperationResponseListDot1xEapInfoOpenApiVOFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateOperationResponseListDot1xEapInfoOpenApiVOFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewOperationResponseListDot1xEapInfoOpenApiVO(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *OperationResponseListDot1xEapInfoOpenApiVO) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetErrorCode gets the errorCode property value. The errorCode property
// returns a *int32 when successful
func (m *OperationResponseListDot1xEapInfoOpenApiVO) GetErrorCode()(*int32) {
    return m.errorCode
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *OperationResponseListDot1xEapInfoOpenApiVO) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["errorCode"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetErrorCode(val)
        }
        return nil
    }
    res["msg"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMsg(val)
        }
        return nil
    }
    res["result"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateDot1xEapInfoOpenApiVOFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]Dot1xEapInfoOpenApiVOable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(Dot1xEapInfoOpenApiVOable)
                }
            }
            m.SetResult(res)
        }
        return nil
    }
    return res
}
// GetMsg gets the msg property value. The msg property
// returns a *string when successful
func (m *OperationResponseListDot1xEapInfoOpenApiVO) GetMsg()(*string) {
    return m.msg
}
// GetResult gets the result property value. The result property
// returns a []Dot1xEapInfoOpenApiVOable when successful
func (m *OperationResponseListDot1xEapInfoOpenApiVO) GetResult()([]Dot1xEapInfoOpenApiVOable) {
    return m.result
}
// Serialize serializes information the current object
func (m *OperationResponseListDot1xEapInfoOpenApiVO) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteInt32Value("errorCode", m.GetErrorCode())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("msg", m.GetMsg())
        if err != nil {
            return err
        }
    }
    if m.GetResult() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetResult()))
        for i, v := range m.GetResult() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("result", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *OperationResponseListDot1xEapInfoOpenApiVO) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetErrorCode sets the errorCode property value. The errorCode property
func (m *OperationResponseListDot1xEapInfoOpenApiVO) SetErrorCode(value *int32)() {
    m.errorCode = value
}
// SetMsg sets the msg property value. The msg property
func (m *OperationResponseListDot1xEapInfoOpenApiVO) SetMsg(value *string)() {
    m.msg = value
}
// SetResult sets the result property value. The result property
func (m *OperationResponseListDot1xEapInfoOpenApiVO) SetResult(value []Dot1xEapInfoOpenApiVOable)() {
    m.result = value
}
type OperationResponseListDot1xEapInfoOpenApiVOable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetErrorCode()(*int32)
    GetMsg()(*string)
    GetResult()([]Dot1xEapInfoOpenApiVOable)
    SetErrorCode(value *int32)()
    SetMsg(value *string)()
    SetResult(value []Dot1xEapInfoOpenApiVOable)()
}
