// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type OswProfileOpenApiVO struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Switch MAC
    mac *string
    // Switch name
    name *string
    // Switch port profiles
    profiles OswProfileOpenApiVO_profilesable
}
// NewOswProfileOpenApiVO instantiates a new OswProfileOpenApiVO and sets the default values.
func NewOswProfileOpenApiVO()(*OswProfileOpenApiVO) {
    m := &OswProfileOpenApiVO{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateOswProfileOpenApiVOFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateOswProfileOpenApiVOFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewOswProfileOpenApiVO(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *OswProfileOpenApiVO) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *OswProfileOpenApiVO) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["mac"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMac(val)
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["profiles"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateOswProfileOpenApiVO_profilesFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetProfiles(val.(OswProfileOpenApiVO_profilesable))
        }
        return nil
    }
    return res
}
// GetMac gets the mac property value. Switch MAC
// returns a *string when successful
func (m *OswProfileOpenApiVO) GetMac()(*string) {
    return m.mac
}
// GetName gets the name property value. Switch name
// returns a *string when successful
func (m *OswProfileOpenApiVO) GetName()(*string) {
    return m.name
}
// GetProfiles gets the profiles property value. Switch port profiles
// returns a OswProfileOpenApiVO_profilesable when successful
func (m *OswProfileOpenApiVO) GetProfiles()(OswProfileOpenApiVO_profilesable) {
    return m.profiles
}
// Serialize serializes information the current object
func (m *OswProfileOpenApiVO) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("mac", m.GetMac())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("profiles", m.GetProfiles())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *OswProfileOpenApiVO) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetMac sets the mac property value. Switch MAC
func (m *OswProfileOpenApiVO) SetMac(value *string)() {
    m.mac = value
}
// SetName sets the name property value. Switch name
func (m *OswProfileOpenApiVO) SetName(value *string)() {
    m.name = value
}
// SetProfiles sets the profiles property value. Switch port profiles
func (m *OswProfileOpenApiVO) SetProfiles(value OswProfileOpenApiVO_profilesable)() {
    m.profiles = value
}
type OswProfileOpenApiVOable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetMac()(*string)
    GetName()(*string)
    GetProfiles()(OswProfileOpenApiVO_profilesable)
    SetMac(value *string)()
    SetName(value *string)()
    SetProfiles(value OswProfileOpenApiVO_profilesable)()
}
