// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type PolicyRoutingOpenApiGridVOPolicyRoutingInfo struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Current page number.
    currentPage *int32
    // Number of entries per page.
    currentSize *int32
    // The data property
    data []PolicyRoutingInfoable
    // Whether Domain Group is supported as Interface in Policy Routing.
    supportDomainGroupDest *bool
    // Whether Location Group is supported as Destination in Policy Routing.
    supportLocationGroupDest *bool
    // Whether multiple WAN interface is supported in Policy Routing.
    supportMulti *bool
    // Whether Vpn Client is supported as Interface in Policy Routing.
    supportVpnClient *bool
    // Total rows of all items.
    totalRows *int64
}
// NewPolicyRoutingOpenApiGridVOPolicyRoutingInfo instantiates a new PolicyRoutingOpenApiGridVOPolicyRoutingInfo and sets the default values.
func NewPolicyRoutingOpenApiGridVOPolicyRoutingInfo()(*PolicyRoutingOpenApiGridVOPolicyRoutingInfo) {
    m := &PolicyRoutingOpenApiGridVOPolicyRoutingInfo{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreatePolicyRoutingOpenApiGridVOPolicyRoutingInfoFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePolicyRoutingOpenApiGridVOPolicyRoutingInfoFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPolicyRoutingOpenApiGridVOPolicyRoutingInfo(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *PolicyRoutingOpenApiGridVOPolicyRoutingInfo) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCurrentPage gets the currentPage property value. Current page number.
// returns a *int32 when successful
func (m *PolicyRoutingOpenApiGridVOPolicyRoutingInfo) GetCurrentPage()(*int32) {
    return m.currentPage
}
// GetCurrentSize gets the currentSize property value. Number of entries per page.
// returns a *int32 when successful
func (m *PolicyRoutingOpenApiGridVOPolicyRoutingInfo) GetCurrentSize()(*int32) {
    return m.currentSize
}
// GetData gets the data property value. The data property
// returns a []PolicyRoutingInfoable when successful
func (m *PolicyRoutingOpenApiGridVOPolicyRoutingInfo) GetData()([]PolicyRoutingInfoable) {
    return m.data
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *PolicyRoutingOpenApiGridVOPolicyRoutingInfo) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["currentPage"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCurrentPage(val)
        }
        return nil
    }
    res["currentSize"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCurrentSize(val)
        }
        return nil
    }
    res["data"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreatePolicyRoutingInfoFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]PolicyRoutingInfoable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(PolicyRoutingInfoable)
                }
            }
            m.SetData(res)
        }
        return nil
    }
    res["supportDomainGroupDest"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSupportDomainGroupDest(val)
        }
        return nil
    }
    res["supportLocationGroupDest"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSupportLocationGroupDest(val)
        }
        return nil
    }
    res["supportMulti"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSupportMulti(val)
        }
        return nil
    }
    res["supportVpnClient"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSupportVpnClient(val)
        }
        return nil
    }
    res["totalRows"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTotalRows(val)
        }
        return nil
    }
    return res
}
// GetSupportDomainGroupDest gets the supportDomainGroupDest property value. Whether Domain Group is supported as Interface in Policy Routing.
// returns a *bool when successful
func (m *PolicyRoutingOpenApiGridVOPolicyRoutingInfo) GetSupportDomainGroupDest()(*bool) {
    return m.supportDomainGroupDest
}
// GetSupportLocationGroupDest gets the supportLocationGroupDest property value. Whether Location Group is supported as Destination in Policy Routing.
// returns a *bool when successful
func (m *PolicyRoutingOpenApiGridVOPolicyRoutingInfo) GetSupportLocationGroupDest()(*bool) {
    return m.supportLocationGroupDest
}
// GetSupportMulti gets the supportMulti property value. Whether multiple WAN interface is supported in Policy Routing.
// returns a *bool when successful
func (m *PolicyRoutingOpenApiGridVOPolicyRoutingInfo) GetSupportMulti()(*bool) {
    return m.supportMulti
}
// GetSupportVpnClient gets the supportVpnClient property value. Whether Vpn Client is supported as Interface in Policy Routing.
// returns a *bool when successful
func (m *PolicyRoutingOpenApiGridVOPolicyRoutingInfo) GetSupportVpnClient()(*bool) {
    return m.supportVpnClient
}
// GetTotalRows gets the totalRows property value. Total rows of all items.
// returns a *int64 when successful
func (m *PolicyRoutingOpenApiGridVOPolicyRoutingInfo) GetTotalRows()(*int64) {
    return m.totalRows
}
// Serialize serializes information the current object
func (m *PolicyRoutingOpenApiGridVOPolicyRoutingInfo) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteInt32Value("currentPage", m.GetCurrentPage())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("currentSize", m.GetCurrentSize())
        if err != nil {
            return err
        }
    }
    if m.GetData() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetData()))
        for i, v := range m.GetData() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("data", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("supportDomainGroupDest", m.GetSupportDomainGroupDest())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("supportLocationGroupDest", m.GetSupportLocationGroupDest())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("supportMulti", m.GetSupportMulti())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("supportVpnClient", m.GetSupportVpnClient())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("totalRows", m.GetTotalRows())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *PolicyRoutingOpenApiGridVOPolicyRoutingInfo) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCurrentPage sets the currentPage property value. Current page number.
func (m *PolicyRoutingOpenApiGridVOPolicyRoutingInfo) SetCurrentPage(value *int32)() {
    m.currentPage = value
}
// SetCurrentSize sets the currentSize property value. Number of entries per page.
func (m *PolicyRoutingOpenApiGridVOPolicyRoutingInfo) SetCurrentSize(value *int32)() {
    m.currentSize = value
}
// SetData sets the data property value. The data property
func (m *PolicyRoutingOpenApiGridVOPolicyRoutingInfo) SetData(value []PolicyRoutingInfoable)() {
    m.data = value
}
// SetSupportDomainGroupDest sets the supportDomainGroupDest property value. Whether Domain Group is supported as Interface in Policy Routing.
func (m *PolicyRoutingOpenApiGridVOPolicyRoutingInfo) SetSupportDomainGroupDest(value *bool)() {
    m.supportDomainGroupDest = value
}
// SetSupportLocationGroupDest sets the supportLocationGroupDest property value. Whether Location Group is supported as Destination in Policy Routing.
func (m *PolicyRoutingOpenApiGridVOPolicyRoutingInfo) SetSupportLocationGroupDest(value *bool)() {
    m.supportLocationGroupDest = value
}
// SetSupportMulti sets the supportMulti property value. Whether multiple WAN interface is supported in Policy Routing.
func (m *PolicyRoutingOpenApiGridVOPolicyRoutingInfo) SetSupportMulti(value *bool)() {
    m.supportMulti = value
}
// SetSupportVpnClient sets the supportVpnClient property value. Whether Vpn Client is supported as Interface in Policy Routing.
func (m *PolicyRoutingOpenApiGridVOPolicyRoutingInfo) SetSupportVpnClient(value *bool)() {
    m.supportVpnClient = value
}
// SetTotalRows sets the totalRows property value. Total rows of all items.
func (m *PolicyRoutingOpenApiGridVOPolicyRoutingInfo) SetTotalRows(value *int64)() {
    m.totalRows = value
}
type PolicyRoutingOpenApiGridVOPolicyRoutingInfoable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCurrentPage()(*int32)
    GetCurrentSize()(*int32)
    GetData()([]PolicyRoutingInfoable)
    GetSupportDomainGroupDest()(*bool)
    GetSupportLocationGroupDest()(*bool)
    GetSupportMulti()(*bool)
    GetSupportVpnClient()(*bool)
    GetTotalRows()(*int64)
    SetCurrentPage(value *int32)()
    SetCurrentSize(value *int32)()
    SetData(value []PolicyRoutingInfoable)()
    SetSupportDomainGroupDest(value *bool)()
    SetSupportLocationGroupDest(value *bool)()
    SetSupportMulti(value *bool)()
    SetSupportVpnClient(value *bool)()
    SetTotalRows(value *int64)()
}
