// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ReportCardQueryVO struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // card info
    cards []TabCardVOable
    // end time, unit: seconds
    end *int64
    // omadacId
    omadacId *string
    // site id
    siteId *string
    // start time, unit: seconds
    start *int64
    // The token property
    token *string
}
// NewReportCardQueryVO instantiates a new ReportCardQueryVO and sets the default values.
func NewReportCardQueryVO()(*ReportCardQueryVO) {
    m := &ReportCardQueryVO{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateReportCardQueryVOFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateReportCardQueryVOFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewReportCardQueryVO(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ReportCardQueryVO) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCards gets the cards property value. card info
// returns a []TabCardVOable when successful
func (m *ReportCardQueryVO) GetCards()([]TabCardVOable) {
    return m.cards
}
// GetEnd gets the end property value. end time, unit: seconds
// returns a *int64 when successful
func (m *ReportCardQueryVO) GetEnd()(*int64) {
    return m.end
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ReportCardQueryVO) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["cards"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateTabCardVOFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]TabCardVOable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(TabCardVOable)
                }
            }
            m.SetCards(res)
        }
        return nil
    }
    res["end"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEnd(val)
        }
        return nil
    }
    res["omadacId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOmadacId(val)
        }
        return nil
    }
    res["siteId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSiteId(val)
        }
        return nil
    }
    res["start"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStart(val)
        }
        return nil
    }
    res["token"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetToken(val)
        }
        return nil
    }
    return res
}
// GetOmadacId gets the omadacId property value. omadacId
// returns a *string when successful
func (m *ReportCardQueryVO) GetOmadacId()(*string) {
    return m.omadacId
}
// GetSiteId gets the siteId property value. site id
// returns a *string when successful
func (m *ReportCardQueryVO) GetSiteId()(*string) {
    return m.siteId
}
// GetStart gets the start property value. start time, unit: seconds
// returns a *int64 when successful
func (m *ReportCardQueryVO) GetStart()(*int64) {
    return m.start
}
// GetToken gets the token property value. The token property
// returns a *string when successful
func (m *ReportCardQueryVO) GetToken()(*string) {
    return m.token
}
// Serialize serializes information the current object
func (m *ReportCardQueryVO) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetCards() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetCards()))
        for i, v := range m.GetCards() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("cards", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("end", m.GetEnd())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("omadacId", m.GetOmadacId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("siteId", m.GetSiteId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("start", m.GetStart())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("token", m.GetToken())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ReportCardQueryVO) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCards sets the cards property value. card info
func (m *ReportCardQueryVO) SetCards(value []TabCardVOable)() {
    m.cards = value
}
// SetEnd sets the end property value. end time, unit: seconds
func (m *ReportCardQueryVO) SetEnd(value *int64)() {
    m.end = value
}
// SetOmadacId sets the omadacId property value. omadacId
func (m *ReportCardQueryVO) SetOmadacId(value *string)() {
    m.omadacId = value
}
// SetSiteId sets the siteId property value. site id
func (m *ReportCardQueryVO) SetSiteId(value *string)() {
    m.siteId = value
}
// SetStart sets the start property value. start time, unit: seconds
func (m *ReportCardQueryVO) SetStart(value *int64)() {
    m.start = value
}
// SetToken sets the token property value. The token property
func (m *ReportCardQueryVO) SetToken(value *string)() {
    m.token = value
}
type ReportCardQueryVOable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCards()([]TabCardVOable)
    GetEnd()(*int64)
    GetOmadacId()(*string)
    GetSiteId()(*string)
    GetStart()(*int64)
    GetToken()(*string)
    SetCards(value []TabCardVOable)()
    SetEnd(value *int64)()
    SetOmadacId(value *string)()
    SetSiteId(value *string)()
    SetStart(value *int64)()
    SetToken(value *string)()
}
