// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// SelectPortForVlanVO device Ports
type SelectPortForVlanVO struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Whether the port needs to be automatically selected.
    autoSelect *bool
    // The vlan of default network.
    defaultVlan *int32
    // The downlink devices of the port
    downlinkDevices []DeviceBriefVOable
    // Whether the port is selectable.
    editEnable *bool
    // Whether the port is affected.
    enable *bool
    // port number, for example: 1
    id *int32
    // Lag ID. It indicates the lag id of the port when the port is in a lag.
    lagId *int32
    // Mode, 0:WAN,1:LAN;
    mode *int32
    // Name.
    name *string
    // It indicates whether the native network of the port is default.
    nativeIsDefault *bool
    // The native network name of the port.
    nativeNetworkName *string
    // The native network vlan of the port.
    nativeNetworkVlan *int32
    // Whether the port needs confirm for binding non-default vlan.
    needConfirm *bool
    // Whether the port needs confirm for being cascade port.
    needConfirmCascadePort *bool
    // When creating single vlan and the port's voice network is enabled, needConfirmVoiceNetwork is true.
    needConfirmVoiceNetwork *bool
    // The port network tag setting. 0:allow all, 1:block all, 2:custom
    oswPortNetworkTagsSetting *int32
    // ID, for example: "1/0/1" (for switch port), "3_e3f176e1c95a49849477636c43a49d3f" (for gateway port).
    portId *string
    // Only valid when editEnable is false. It indicates the reason why the port is not selectable.Each Item should be a value as follows: -2: The port has been added to LAG. Lag member port can not be selected; -8: The port is wan port. Wan port can not be selected; -10: The AP’s LAN port cannot be configured; -12: The port's tags setting is not custom and therefore it can not be selected when creating multi vlan; -13: The port is stack port. Stack port can not be selected; -14: The number of VLANs has reached the limit of the Easy Managed Switch.
    reasons []int32
    // Whether the port is selected by user.
    selectByUser *bool
    // Type. 1: Copper, 2: Combo, 3: SFP
    typeEscaped *int32
    // Whether the auto-select port is unselected by user.
    unSelectByUser *bool
    // The upper device of the port
    upperDevice DeviceBriefVOable
}
// NewSelectPortForVlanVO instantiates a new SelectPortForVlanVO and sets the default values.
func NewSelectPortForVlanVO()(*SelectPortForVlanVO) {
    m := &SelectPortForVlanVO{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateSelectPortForVlanVOFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateSelectPortForVlanVOFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewSelectPortForVlanVO(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *SelectPortForVlanVO) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAutoSelect gets the autoSelect property value. Whether the port needs to be automatically selected.
// returns a *bool when successful
func (m *SelectPortForVlanVO) GetAutoSelect()(*bool) {
    return m.autoSelect
}
// GetDefaultVlan gets the defaultVlan property value. The vlan of default network.
// returns a *int32 when successful
func (m *SelectPortForVlanVO) GetDefaultVlan()(*int32) {
    return m.defaultVlan
}
// GetDownlinkDevices gets the downlinkDevices property value. The downlink devices of the port
// returns a []DeviceBriefVOable when successful
func (m *SelectPortForVlanVO) GetDownlinkDevices()([]DeviceBriefVOable) {
    return m.downlinkDevices
}
// GetEditEnable gets the editEnable property value. Whether the port is selectable.
// returns a *bool when successful
func (m *SelectPortForVlanVO) GetEditEnable()(*bool) {
    return m.editEnable
}
// GetEnable gets the Enable property value. Whether the port is affected.
// returns a *bool when successful
func (m *SelectPortForVlanVO) GetEnable()(*bool) {
    return m.enable
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *SelectPortForVlanVO) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["autoSelect"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAutoSelect(val)
        }
        return nil
    }
    res["defaultVlan"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDefaultVlan(val)
        }
        return nil
    }
    res["downlinkDevices"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateDeviceBriefVOFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]DeviceBriefVOable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(DeviceBriefVOable)
                }
            }
            m.SetDownlinkDevices(res)
        }
        return nil
    }
    res["editEnable"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEditEnable(val)
        }
        return nil
    }
    res["Enable"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEnable(val)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["lagId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLagId(val)
        }
        return nil
    }
    res["mode"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMode(val)
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["nativeIsDefault"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNativeIsDefault(val)
        }
        return nil
    }
    res["nativeNetworkName"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNativeNetworkName(val)
        }
        return nil
    }
    res["nativeNetworkVlan"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNativeNetworkVlan(val)
        }
        return nil
    }
    res["needConfirm"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNeedConfirm(val)
        }
        return nil
    }
    res["needConfirmCascadePort"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNeedConfirmCascadePort(val)
        }
        return nil
    }
    res["needConfirmVoiceNetwork"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNeedConfirmVoiceNetwork(val)
        }
        return nil
    }
    res["oswPortNetworkTagsSetting"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOswPortNetworkTagsSetting(val)
        }
        return nil
    }
    res["portId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPortId(val)
        }
        return nil
    }
    res["reasons"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("int32")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]int32, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*int32))
                }
            }
            m.SetReasons(res)
        }
        return nil
    }
    res["selectByUser"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSelectByUser(val)
        }
        return nil
    }
    res["type"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTypeEscaped(val)
        }
        return nil
    }
    res["unSelectByUser"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUnSelectByUser(val)
        }
        return nil
    }
    res["upperDevice"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateDeviceBriefVOFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUpperDevice(val.(DeviceBriefVOable))
        }
        return nil
    }
    return res
}
// GetId gets the id property value. port number, for example: 1
// returns a *int32 when successful
func (m *SelectPortForVlanVO) GetId()(*int32) {
    return m.id
}
// GetLagId gets the lagId property value. Lag ID. It indicates the lag id of the port when the port is in a lag.
// returns a *int32 when successful
func (m *SelectPortForVlanVO) GetLagId()(*int32) {
    return m.lagId
}
// GetMode gets the mode property value. Mode, 0:WAN,1:LAN;
// returns a *int32 when successful
func (m *SelectPortForVlanVO) GetMode()(*int32) {
    return m.mode
}
// GetName gets the name property value. Name.
// returns a *string when successful
func (m *SelectPortForVlanVO) GetName()(*string) {
    return m.name
}
// GetNativeIsDefault gets the nativeIsDefault property value. It indicates whether the native network of the port is default.
// returns a *bool when successful
func (m *SelectPortForVlanVO) GetNativeIsDefault()(*bool) {
    return m.nativeIsDefault
}
// GetNativeNetworkName gets the nativeNetworkName property value. The native network name of the port.
// returns a *string when successful
func (m *SelectPortForVlanVO) GetNativeNetworkName()(*string) {
    return m.nativeNetworkName
}
// GetNativeNetworkVlan gets the nativeNetworkVlan property value. The native network vlan of the port.
// returns a *int32 when successful
func (m *SelectPortForVlanVO) GetNativeNetworkVlan()(*int32) {
    return m.nativeNetworkVlan
}
// GetNeedConfirm gets the needConfirm property value. Whether the port needs confirm for binding non-default vlan.
// returns a *bool when successful
func (m *SelectPortForVlanVO) GetNeedConfirm()(*bool) {
    return m.needConfirm
}
// GetNeedConfirmCascadePort gets the needConfirmCascadePort property value. Whether the port needs confirm for being cascade port.
// returns a *bool when successful
func (m *SelectPortForVlanVO) GetNeedConfirmCascadePort()(*bool) {
    return m.needConfirmCascadePort
}
// GetNeedConfirmVoiceNetwork gets the needConfirmVoiceNetwork property value. When creating single vlan and the port's voice network is enabled, needConfirmVoiceNetwork is true.
// returns a *bool when successful
func (m *SelectPortForVlanVO) GetNeedConfirmVoiceNetwork()(*bool) {
    return m.needConfirmVoiceNetwork
}
// GetOswPortNetworkTagsSetting gets the oswPortNetworkTagsSetting property value. The port network tag setting. 0:allow all, 1:block all, 2:custom
// returns a *int32 when successful
func (m *SelectPortForVlanVO) GetOswPortNetworkTagsSetting()(*int32) {
    return m.oswPortNetworkTagsSetting
}
// GetPortId gets the portId property value. ID, for example: "1/0/1" (for switch port), "3_e3f176e1c95a49849477636c43a49d3f" (for gateway port).
// returns a *string when successful
func (m *SelectPortForVlanVO) GetPortId()(*string) {
    return m.portId
}
// GetReasons gets the reasons property value. Only valid when editEnable is false. It indicates the reason why the port is not selectable.Each Item should be a value as follows: -2: The port has been added to LAG. Lag member port can not be selected; -8: The port is wan port. Wan port can not be selected; -10: The AP’s LAN port cannot be configured; -12: The port's tags setting is not custom and therefore it can not be selected when creating multi vlan; -13: The port is stack port. Stack port can not be selected; -14: The number of VLANs has reached the limit of the Easy Managed Switch.
// returns a []int32 when successful
func (m *SelectPortForVlanVO) GetReasons()([]int32) {
    return m.reasons
}
// GetSelectByUser gets the selectByUser property value. Whether the port is selected by user.
// returns a *bool when successful
func (m *SelectPortForVlanVO) GetSelectByUser()(*bool) {
    return m.selectByUser
}
// GetTypeEscaped gets the type property value. Type. 1: Copper, 2: Combo, 3: SFP
// returns a *int32 when successful
func (m *SelectPortForVlanVO) GetTypeEscaped()(*int32) {
    return m.typeEscaped
}
// GetUnSelectByUser gets the unSelectByUser property value. Whether the auto-select port is unselected by user.
// returns a *bool when successful
func (m *SelectPortForVlanVO) GetUnSelectByUser()(*bool) {
    return m.unSelectByUser
}
// GetUpperDevice gets the upperDevice property value. The upper device of the port
// returns a DeviceBriefVOable when successful
func (m *SelectPortForVlanVO) GetUpperDevice()(DeviceBriefVOable) {
    return m.upperDevice
}
// Serialize serializes information the current object
func (m *SelectPortForVlanVO) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteBoolValue("autoSelect", m.GetAutoSelect())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("defaultVlan", m.GetDefaultVlan())
        if err != nil {
            return err
        }
    }
    if m.GetDownlinkDevices() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetDownlinkDevices()))
        for i, v := range m.GetDownlinkDevices() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("downlinkDevices", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("editEnable", m.GetEditEnable())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("Enable", m.GetEnable())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("lagId", m.GetLagId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("mode", m.GetMode())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("nativeIsDefault", m.GetNativeIsDefault())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("nativeNetworkName", m.GetNativeNetworkName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("nativeNetworkVlan", m.GetNativeNetworkVlan())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("needConfirm", m.GetNeedConfirm())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("needConfirmCascadePort", m.GetNeedConfirmCascadePort())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("needConfirmVoiceNetwork", m.GetNeedConfirmVoiceNetwork())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("oswPortNetworkTagsSetting", m.GetOswPortNetworkTagsSetting())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("portId", m.GetPortId())
        if err != nil {
            return err
        }
    }
    if m.GetReasons() != nil {
        err := writer.WriteCollectionOfInt32Values("reasons", m.GetReasons())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("selectByUser", m.GetSelectByUser())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("type", m.GetTypeEscaped())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("unSelectByUser", m.GetUnSelectByUser())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("upperDevice", m.GetUpperDevice())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *SelectPortForVlanVO) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAutoSelect sets the autoSelect property value. Whether the port needs to be automatically selected.
func (m *SelectPortForVlanVO) SetAutoSelect(value *bool)() {
    m.autoSelect = value
}
// SetDefaultVlan sets the defaultVlan property value. The vlan of default network.
func (m *SelectPortForVlanVO) SetDefaultVlan(value *int32)() {
    m.defaultVlan = value
}
// SetDownlinkDevices sets the downlinkDevices property value. The downlink devices of the port
func (m *SelectPortForVlanVO) SetDownlinkDevices(value []DeviceBriefVOable)() {
    m.downlinkDevices = value
}
// SetEditEnable sets the editEnable property value. Whether the port is selectable.
func (m *SelectPortForVlanVO) SetEditEnable(value *bool)() {
    m.editEnable = value
}
// SetEnable sets the Enable property value. Whether the port is affected.
func (m *SelectPortForVlanVO) SetEnable(value *bool)() {
    m.enable = value
}
// SetId sets the id property value. port number, for example: 1
func (m *SelectPortForVlanVO) SetId(value *int32)() {
    m.id = value
}
// SetLagId sets the lagId property value. Lag ID. It indicates the lag id of the port when the port is in a lag.
func (m *SelectPortForVlanVO) SetLagId(value *int32)() {
    m.lagId = value
}
// SetMode sets the mode property value. Mode, 0:WAN,1:LAN;
func (m *SelectPortForVlanVO) SetMode(value *int32)() {
    m.mode = value
}
// SetName sets the name property value. Name.
func (m *SelectPortForVlanVO) SetName(value *string)() {
    m.name = value
}
// SetNativeIsDefault sets the nativeIsDefault property value. It indicates whether the native network of the port is default.
func (m *SelectPortForVlanVO) SetNativeIsDefault(value *bool)() {
    m.nativeIsDefault = value
}
// SetNativeNetworkName sets the nativeNetworkName property value. The native network name of the port.
func (m *SelectPortForVlanVO) SetNativeNetworkName(value *string)() {
    m.nativeNetworkName = value
}
// SetNativeNetworkVlan sets the nativeNetworkVlan property value. The native network vlan of the port.
func (m *SelectPortForVlanVO) SetNativeNetworkVlan(value *int32)() {
    m.nativeNetworkVlan = value
}
// SetNeedConfirm sets the needConfirm property value. Whether the port needs confirm for binding non-default vlan.
func (m *SelectPortForVlanVO) SetNeedConfirm(value *bool)() {
    m.needConfirm = value
}
// SetNeedConfirmCascadePort sets the needConfirmCascadePort property value. Whether the port needs confirm for being cascade port.
func (m *SelectPortForVlanVO) SetNeedConfirmCascadePort(value *bool)() {
    m.needConfirmCascadePort = value
}
// SetNeedConfirmVoiceNetwork sets the needConfirmVoiceNetwork property value. When creating single vlan and the port's voice network is enabled, needConfirmVoiceNetwork is true.
func (m *SelectPortForVlanVO) SetNeedConfirmVoiceNetwork(value *bool)() {
    m.needConfirmVoiceNetwork = value
}
// SetOswPortNetworkTagsSetting sets the oswPortNetworkTagsSetting property value. The port network tag setting. 0:allow all, 1:block all, 2:custom
func (m *SelectPortForVlanVO) SetOswPortNetworkTagsSetting(value *int32)() {
    m.oswPortNetworkTagsSetting = value
}
// SetPortId sets the portId property value. ID, for example: "1/0/1" (for switch port), "3_e3f176e1c95a49849477636c43a49d3f" (for gateway port).
func (m *SelectPortForVlanVO) SetPortId(value *string)() {
    m.portId = value
}
// SetReasons sets the reasons property value. Only valid when editEnable is false. It indicates the reason why the port is not selectable.Each Item should be a value as follows: -2: The port has been added to LAG. Lag member port can not be selected; -8: The port is wan port. Wan port can not be selected; -10: The AP’s LAN port cannot be configured; -12: The port's tags setting is not custom and therefore it can not be selected when creating multi vlan; -13: The port is stack port. Stack port can not be selected; -14: The number of VLANs has reached the limit of the Easy Managed Switch.
func (m *SelectPortForVlanVO) SetReasons(value []int32)() {
    m.reasons = value
}
// SetSelectByUser sets the selectByUser property value. Whether the port is selected by user.
func (m *SelectPortForVlanVO) SetSelectByUser(value *bool)() {
    m.selectByUser = value
}
// SetTypeEscaped sets the type property value. Type. 1: Copper, 2: Combo, 3: SFP
func (m *SelectPortForVlanVO) SetTypeEscaped(value *int32)() {
    m.typeEscaped = value
}
// SetUnSelectByUser sets the unSelectByUser property value. Whether the auto-select port is unselected by user.
func (m *SelectPortForVlanVO) SetUnSelectByUser(value *bool)() {
    m.unSelectByUser = value
}
// SetUpperDevice sets the upperDevice property value. The upper device of the port
func (m *SelectPortForVlanVO) SetUpperDevice(value DeviceBriefVOable)() {
    m.upperDevice = value
}
type SelectPortForVlanVOable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAutoSelect()(*bool)
    GetDefaultVlan()(*int32)
    GetDownlinkDevices()([]DeviceBriefVOable)
    GetEditEnable()(*bool)
    GetEnable()(*bool)
    GetId()(*int32)
    GetLagId()(*int32)
    GetMode()(*int32)
    GetName()(*string)
    GetNativeIsDefault()(*bool)
    GetNativeNetworkName()(*string)
    GetNativeNetworkVlan()(*int32)
    GetNeedConfirm()(*bool)
    GetNeedConfirmCascadePort()(*bool)
    GetNeedConfirmVoiceNetwork()(*bool)
    GetOswPortNetworkTagsSetting()(*int32)
    GetPortId()(*string)
    GetReasons()([]int32)
    GetSelectByUser()(*bool)
    GetTypeEscaped()(*int32)
    GetUnSelectByUser()(*bool)
    GetUpperDevice()(DeviceBriefVOable)
    SetAutoSelect(value *bool)()
    SetDefaultVlan(value *int32)()
    SetDownlinkDevices(value []DeviceBriefVOable)()
    SetEditEnable(value *bool)()
    SetEnable(value *bool)()
    SetId(value *int32)()
    SetLagId(value *int32)()
    SetMode(value *int32)()
    SetName(value *string)()
    SetNativeIsDefault(value *bool)()
    SetNativeNetworkName(value *string)()
    SetNativeNetworkVlan(value *int32)()
    SetNeedConfirm(value *bool)()
    SetNeedConfirmCascadePort(value *bool)()
    SetNeedConfirmVoiceNetwork(value *bool)()
    SetOswPortNetworkTagsSetting(value *int32)()
    SetPortId(value *string)()
    SetReasons(value []int32)()
    SetSelectByUser(value *bool)()
    SetTypeEscaped(value *int32)()
    SetUnSelectByUser(value *bool)()
    SetUpperDevice(value DeviceBriefVOable)()
}
