// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type TelephoneNumberListUpdateOpenApiVO struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Telephone numbers to be added.
    addTelephoneNumbers []TelephoneNumberWithoutStatusOpenApiVOable
    // Telephone number IDs to be deleted.
    deleteTelephoneNumberIds []string
    // Telephone numbers to be modified.
    modifyTelephoneNumbers []TelephoneNumberWithoutStatusOpenApiVOable
}
// NewTelephoneNumberListUpdateOpenApiVO instantiates a new TelephoneNumberListUpdateOpenApiVO and sets the default values.
func NewTelephoneNumberListUpdateOpenApiVO()(*TelephoneNumberListUpdateOpenApiVO) {
    m := &TelephoneNumberListUpdateOpenApiVO{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateTelephoneNumberListUpdateOpenApiVOFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateTelephoneNumberListUpdateOpenApiVOFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewTelephoneNumberListUpdateOpenApiVO(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *TelephoneNumberListUpdateOpenApiVO) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAddTelephoneNumbers gets the addTelephoneNumbers property value. Telephone numbers to be added.
// returns a []TelephoneNumberWithoutStatusOpenApiVOable when successful
func (m *TelephoneNumberListUpdateOpenApiVO) GetAddTelephoneNumbers()([]TelephoneNumberWithoutStatusOpenApiVOable) {
    return m.addTelephoneNumbers
}
// GetDeleteTelephoneNumberIds gets the deleteTelephoneNumberIds property value. Telephone number IDs to be deleted.
// returns a []string when successful
func (m *TelephoneNumberListUpdateOpenApiVO) GetDeleteTelephoneNumberIds()([]string) {
    return m.deleteTelephoneNumberIds
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *TelephoneNumberListUpdateOpenApiVO) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["addTelephoneNumbers"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateTelephoneNumberWithoutStatusOpenApiVOFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]TelephoneNumberWithoutStatusOpenApiVOable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(TelephoneNumberWithoutStatusOpenApiVOable)
                }
            }
            m.SetAddTelephoneNumbers(res)
        }
        return nil
    }
    res["deleteTelephoneNumberIds"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("string")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]string, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*string))
                }
            }
            m.SetDeleteTelephoneNumberIds(res)
        }
        return nil
    }
    res["modifyTelephoneNumbers"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateTelephoneNumberWithoutStatusOpenApiVOFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]TelephoneNumberWithoutStatusOpenApiVOable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(TelephoneNumberWithoutStatusOpenApiVOable)
                }
            }
            m.SetModifyTelephoneNumbers(res)
        }
        return nil
    }
    return res
}
// GetModifyTelephoneNumbers gets the modifyTelephoneNumbers property value. Telephone numbers to be modified.
// returns a []TelephoneNumberWithoutStatusOpenApiVOable when successful
func (m *TelephoneNumberListUpdateOpenApiVO) GetModifyTelephoneNumbers()([]TelephoneNumberWithoutStatusOpenApiVOable) {
    return m.modifyTelephoneNumbers
}
// Serialize serializes information the current object
func (m *TelephoneNumberListUpdateOpenApiVO) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetAddTelephoneNumbers() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetAddTelephoneNumbers()))
        for i, v := range m.GetAddTelephoneNumbers() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("addTelephoneNumbers", cast)
        if err != nil {
            return err
        }
    }
    if m.GetDeleteTelephoneNumberIds() != nil {
        err := writer.WriteCollectionOfStringValues("deleteTelephoneNumberIds", m.GetDeleteTelephoneNumberIds())
        if err != nil {
            return err
        }
    }
    if m.GetModifyTelephoneNumbers() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetModifyTelephoneNumbers()))
        for i, v := range m.GetModifyTelephoneNumbers() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("modifyTelephoneNumbers", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *TelephoneNumberListUpdateOpenApiVO) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAddTelephoneNumbers sets the addTelephoneNumbers property value. Telephone numbers to be added.
func (m *TelephoneNumberListUpdateOpenApiVO) SetAddTelephoneNumbers(value []TelephoneNumberWithoutStatusOpenApiVOable)() {
    m.addTelephoneNumbers = value
}
// SetDeleteTelephoneNumberIds sets the deleteTelephoneNumberIds property value. Telephone number IDs to be deleted.
func (m *TelephoneNumberListUpdateOpenApiVO) SetDeleteTelephoneNumberIds(value []string)() {
    m.deleteTelephoneNumberIds = value
}
// SetModifyTelephoneNumbers sets the modifyTelephoneNumbers property value. Telephone numbers to be modified.
func (m *TelephoneNumberListUpdateOpenApiVO) SetModifyTelephoneNumbers(value []TelephoneNumberWithoutStatusOpenApiVOable)() {
    m.modifyTelephoneNumbers = value
}
type TelephoneNumberListUpdateOpenApiVOable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAddTelephoneNumbers()([]TelephoneNumberWithoutStatusOpenApiVOable)
    GetDeleteTelephoneNumberIds()([]string)
    GetModifyTelephoneNumbers()([]TelephoneNumberWithoutStatusOpenApiVOable)
    SetAddTelephoneNumbers(value []TelephoneNumberWithoutStatusOpenApiVOable)()
    SetDeleteTelephoneNumberIds(value []string)()
    SetModifyTelephoneNumbers(value []TelephoneNumberWithoutStatusOpenApiVOable)()
}
